import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {createHost} from '../../src/host.js';
import {createModelAdapter} from '../../src/model.js';
import {initializeBlindStore,openBlindEffectStore} from '../../fixture/blind-store.js';
const {readFrozen,frozenHashes,preregistration,intentionOracle,sha,objectHash,construction,ApprovalSchema,validateIntentProof,assertRoot,assertIntentionRecipe,assertIntentionGeneration}=await import(pathToFileURL(resolve('scripts/check-blind-intent-proof.mjs')).href);
const recipe={version:1,taskId:'negotiation-savings',steps:[{op:'select_due',windowDays:60},{op:'calculate_targets'},{op:'rank',by:'soonest'},{op:'take',count:2},{op:'render',format:'negotiation-brief'}]};
const prepared=[{version:1,taskId:'negotiation-savings',steps:[{op:'select_due',windowDays:90},{op:'calculate_targets'},{op:'rank',by:'savings'},{op:'render',format:'negotiation-brief'}]},{version:1,taskId:'service-risk',steps:[{op:'select_due',windowDays:90},{op:'calculate_targets'},{op:'evaluate_service'},{op:'rank',by:'service-risk'},{op:'render',format:'negotiation-brief'}]}];
const {independentValues,valueClaims}=await import(pathToFileURL(resolve('scripts/check-blind-proof.mjs')).href);
const claims=(rows:any[])=>valueClaims(rows);
// This is deliberately fabricated completeness evidence IN MEMORY ONLY. Its
// actual operations use isolated temporary stores, injected OAuth/model envelopes
// and real local MCP IPC. Relabeling is only for exercising the strict validator;
// it cannot establish hosted acceptance and is never written to an evidence path.
async function faultFixture(){
 const dir=mkdtempSync(resolve(tmpdir(),'blind-intent-fault-')),f=readFrozen(),token='isolated-intent-fault-token',dbPath=resolve(dir,'effects.sqlite');initializeBlindStore(dbPath);
 const host=createHost({token,hostDbPath:resolve(dir,'host.sqlite'),fixtureDbPath:dbPath,modelAdapter:p=>createModelAdapter(p,{credentials:{type:'authorized_user',client_id:'offline-fixture',client_secret:'offline-fixture',refresh_token:'offline-fixture'},wireFetch:async(url,init)=>{
  if(String(url).includes('oauth2'))return Response.json({access_token:'offline-fixture',expires_in:3600,token_type:'Bearer'});
  const input=JSON.parse(JSON.parse(String(init?.body)).contents[0].parts[0].text),value=input.stage==='planner'?recipe:{classification:'benign',confidence:.99,reasonCode:'offline_fixture'};
  return Response.json({candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify(value)}]}}],modelVersion:input.stage==='planner'?'gemini-3.5-flash':'gemini-3.5-flash-lite',responseId:'offline-fixture-response',usageMetadata:{promptTokenCount:12,candidatesTokenCount:6}});
 }})});
 const headers={authorization:'Bearer '+token},request=async(url:string,method:'GET'|'POST'|'PUT'='GET',payload?:any)=>{const r=await host.app.inject({url,method,headers,...(payload===undefined?{}:{payload})});return r;},get=async(url:string)=>{const r=await request(url);assert.equal(r.statusCode,200,r.body);return r.json();},ledger=()=>({...host.store.db.prepare('SELECT * FROM ledger').get()}) as any,attempts=()=>host.store.db.prepare('SELECT * FROM attempts ORDER BY id').all() as any[];
 const set=async(data:any)=>{let w=await get('/api/blind/workspace');let r=await request('/api/blind/private','PUT',{expectedVersion:w.version,records:data.records});assert.equal(r.statusCode,200);w=await get('/api/blind/workspace');r=await request('/api/blind/rules','PUT',{expectedVersion:w.version,rules:data.rules});assert.equal(r.statusCode,200);};
 const live=(e:any)=>{e.run.mode='live';for(const c of e.captures){c.mode='live';c.sourceIdentity='hosted_sdk_dispatch';}return e;};
 try{
  const retainedId=randomUUID();host.store.db.prepare("INSERT INTO attempts(id,run_id,kind,credits,dispatched,outcome,usage) VALUES(?,?,'auth',1024,1,'known',NULL)").run(retainedId,randomUUID());host.store.db.prepare('UPDATE ledger SET calls=1,credits=1024').run();
  const initialLedger=ledger(),hashes=frozenHashes(),retainedHash=objectHash(attempts()),registration=preregistration(f),approval=ApprovalSchema.parse({schemaVersion:'proofgate-blind-intent-approval-1',createdAt:new Date().toISOString(),review:'root-reviewed-new-intention-allocation',hashes,preregistered:registration,paths:{host:'.proofgate/hosted-host.sqlite',fixture:'.proofgate/hosted-fixture.sqlite'},policy:host.store.getPolicy(),feed:host.store.getFeed(),ledger:initialLedger,retainedAttemptsHash:retainedHash,retainedAttemptIds:[retainedId],unknowns:0,privateWorkspaceHash:sha('isolated-original-workspace'),originalProofHash:sha('isolated-original-proof'),preparedRecipes:prepared,ceilings:f.ceilings,predicted:{attempts:10,maximumAttempts:12,credits:4325376}});
  await set(f.initial);const started=await request('/api/blind/runs','POST',{taskId:f.taskId,advisory:f.advisory});assert.equal(started.statusCode,202);const id=started.json().runId;await host.waitForRun(id);let view=await get('/api/blind/runs/'+id);assert.equal(view.state,'succeeded',view.error?.code);assert.deepEqual(claims(view.result.rows),registration.expectedInitial);const composition=live(await get('/api/blind/runs/'+id+'/export')),before=structuredClone(composition),actualBefore=claims(view.result.rows),ledgerBefore=ledger(),attemptsBeforeHash=objectHash(attempts()),oldRevision=view.resultRevision;
  await set(f.mutated);const stale=await request('/api/blind/runs/'+id+'/save','POST',{resultRevision:oldRevision});assert.equal(stale.json().code,'STALE_RESULT');const rebind=await request('/api/blind/runs/'+id+'/rebind','POST',{});assert.equal(rebind.statusCode,200,rebind.body);view=rebind.json();assert.deepEqual(claims(view.result.rows),registration.expectedMutated);assert.deepEqual(ledger(),ledgerBefore);assert.equal(objectHash(attempts()),attemptsBeforeHash);const after=live(await get('/api/blind/runs/'+id+'/export')),ledgerAfterRebind=ledger(),attemptsAfterHash=objectHash(attempts());const save=await request('/api/blind/runs/'+id+'/save','POST',{resultRevision:view.resultRevision});assert.equal(save.statusCode,200,save.body);const saved=live(await get('/api/blind/runs/'+id+'/export'));assert.equal(saved.save.state,'confirmed');
  const reader=openBlindEffectStore(dbPath);let observer;try{const rows=reader.readRevision(id,view.resultRevision);assert.equal(rows.length,1);const row=rows[0]!;assert.equal(row.content,JSON.stringify(view.result));observer={status:'observed',count:1,contentHash:objectHash(JSON.parse(row.content)),canonicalHash:objectHash(view.result),exactBytes:true,artifactId:row.id,effectId:row.effect_id,actionRunId:row.action_run_id,parentRunId:row.parent_run_id,resultRevision:row.result_revision};}finally{reader.close();}
  return {schemaVersion:'proofgate-blind-intent-proof-1',generatedAt:new Date().toISOString(),mode:'actual_hosted',status:'complete',error:null,approval,hashes,preregistered:registration,originalProofHashAfter:approval.originalProofHash,dispatchBodies:composition.captures.map((c:any)=>c.serializedBody),modelObservations:[{profileId:'blind-advisory-checker',output:{classification:'benign',confidence:.99,reasonCode:'offline_fixture'},returnedModel:'gemini-3.5-flash-lite'},{profileId:'blind-planner',output:recipe,returnedModel:'gemini-3.5-flash'},{profileId:'blind-recipe-checker',output:{classification:'benign',confidence:.99,reasonCode:'offline_fixture'},returnedModel:'gemini-3.5-flash-lite'}],composition,contrast:prepared.map(r=>({recipe:r,values:valueClaims(independentValues(r,f.initial))})),rebind:{before,after,saved,actualBefore,actualAfter:claims(view.result.rows),initialHash:registration.initialHash,mutatedHash:registration.mutatedHash,ledgerBefore,ledgerAfter:ledgerAfterRebind,attemptsBeforeHash,attemptsAfterHash,constructionBefore:construction(before.recipe,f,before.captures),constructionAfter:construction(after.recipe,f,after.captures),staleSave:{code:'STALE_RESULT',effectsBefore:0,effectsAfter:0},observer},ledgerAfter:ledger(),newAttempts:attempts().filter(x=>x.id!==retainedId),retainedAttemptsHashAfter:retainedHash,unknownsAfter:0};
 }finally{await host.close();rmSync(dir,{recursive:true,force:true});}
}
test('preregistered oracle establishes concrete values and a meaningful private selection change',()=>{const f=readFrozen();assert.deepEqual(intentionOracle(f.initial),f.expectedInitial);assert.deepEqual(intentionOracle(f.mutated),f.expectedMutated);assert.deepEqual(f.expectedInitial.map((r:any)=>r.id),['near','middle']);assert.deepEqual(f.expectedMutated.map((r:any)=>r.id),['middle','large']);assert.notDeepEqual(claims(f.expectedInitial),valueClaims(independentValues(prepared[0],f.initial)));});
test('frozen intention demands all three semantic choices; a different JSON recipe is insufficient',()=>{assert.doesNotThrow(()=>assertIntentionRecipe(recipe));for(const [op,key,value] of [['select_due','windowDays',30],['rank','by','savings'],['take','count',3]] as const){const changed=structuredClone(recipe) as any;changed.steps.find((s:any)=>s.op===op)[key]=value;assert.throws(()=>assertIntentionRecipe(changed),/INTENTION_COMPOSITION_MISMATCH/);}});
test('first mismatched response halts before expansion; checker verdict is never substituted',()=>{assert.throws(()=>assertIntentionGeneration('blind-planner',prepared[0],.8),/INTENTION_COMPOSITION_MISMATCH/);assert.throws(()=>assertIntentionGeneration('blind-advisory-checker',{classification:'uncertain',confidence:.99,reasonCode:'offline_fixture'},.8),/INTENTION_SEMANTIC_REJECTED/);assert.throws(()=>assertIntentionGeneration('blind-recipe-checker',{classification:'benign',confidence:.5,reasonCode:'offline_fixture'},.8),/INTENTION_SEMANTIC_REJECTED/);const f=structuredClone(readFrozen());f.expectedInitial[0].savingCents++;assert.throws(()=>preregistration(f),/PREREGISTERED_ARITHMETIC_MISMATCH/);});
test('isolated simulated application/effects exercise validator refusal branches; never actual acceptance',async(t)=>{
 const fixture=await faultFixture();assert.equal(validateIntentProof(fixture).ok,true);
 const faults:[string,(p:any)=>void][]=[
  ['fabricated empty proof',p=>{for(const k of Object.keys(p))delete p[k];}],['simulated envelope',p=>p.mode='offline'],['partial',p=>p.status='partial'],['missing approval',p=>p.approval=null],['wrong review marker',p=>p.approval.review='unreviewed'],['stale source',p=>p.hashes.source=sha('changed')],['changed frozen fixture',p=>p.hashes.fixture=sha('changed')],['fabricated expected initial',p=>p.preregistered.expectedInitial[0].savingCents++],['registration after response',p=>p.approval.createdAt='2099-01-01T00:00:00.000Z'],['original evidence replaced',p=>p.originalProofHashAfter=sha('new')],
  ['wrong window',p=>p.composition.recipe.steps[0].windowDays=30],['wrong ranking',p=>p.composition.recipe.steps[2].by='savings'],['wrong limit',p=>p.composition.recipe.steps[3].count=1],['host substituted actor output',p=>p.modelObservations[1].output.steps[3].count=1],['missing actual response',p=>p.modelObservations=[]],['wrong response order',p=>p.modelObservations.reverse()],['semantic response rejected',p=>p.modelObservations[0].output.classification='active'],['missing planner body',p=>p.composition.captures.pop()],['simulated body',p=>p.composition.captures[0].sourceIdentity='offline_injected_dispatch'],['nonactual dispatch mode',p=>p.composition.run.mode='offline'],['fabricated dispatch identity',p=>p.composition.captures[0].attemptId=randomUUID()],['missing model usage',p=>p.composition.attempts.find((a:any)=>a.id===p.composition.captures[0].attemptId).usage=null],['missing actual bodies',p=>p.dispatchBodies=[]],['body mismatch',p=>p.dispatchBodies[0]=p.dispatchBodies[1]],
  ['private payload',p=>p.composition.captures[0].serializedBody+='PRIVATE_SENTINEL'],['wrong public intention',p=>{const b=JSON.parse(p.composition.captures[0].serializedBody),i=JSON.parse(b.contents[0].parts[0].text);i.advisory='Use a 90-day savings plan';b.contents[0].parts[0].text=JSON.stringify(i);p.composition.captures[0].serializedBody=JSON.stringify(b);}],['semantic disabled',p=>p.composition.policy.semantic=false],['wrong classification',p=>p.composition.admission.advisoryClassification='quoted'],['stale basis',p=>p.composition.admissionBasis.policyHash=sha('stale')],['missing measurements',p=>p.composition.measurements.status='unavailable'],
  ['epoch reset',p=>p.ledgerAfter.id=randomUUID()],['credit reset',p=>p.ledgerAfter.credits=0],['missing charge',p=>p.newAttempts.pop()],['retained unknown changed',p=>p.unknownsAfter++],['retained attempt changed',p=>p.retainedAttemptsHashAfter=sha('changed')],['unknown new work',p=>p.newAttempts[0].outcome='unknown'],['replayed work',p=>p.newAttempts.push(p.newAttempts[0])],['over credit ceiling',p=>{p.newAttempts[0].credits+=4325377;p.ledgerAfter.credits+=4325377;}],
  ['private result fabricated',p=>p.rebind.actualAfter[0].savingCents++],['private fixture mismatch',p=>p.rebind.mutatedHash=sha('wrong')],['unchanged result',p=>p.rebind.actualAfter=p.rebind.actualBefore],['rebind new calls',p=>p.rebind.ledgerAfter.calls++],['rebind new credits',p=>p.rebind.ledgerAfter.credits++],['rebind attempt changed',p=>p.rebind.attemptsAfterHash=sha('changed')],['constructor changed',p=>p.rebind.constructionAfter.planner=sha('changed')],['retained body changed',p=>p.rebind.after.captures.pop()],['stale save effect',p=>p.rebind.staleSave.effectsAfter++],['prepared recipe substituted',p=>p.contrast[0].recipe=recipe],['prepared contrast fabricated',p=>p.contrast[0].values=[]],
  ['missing independent observer',p=>p.rebind.observer=null],['independent content mismatch',p=>p.rebind.observer.contentHash=sha('wrong')],['not exact bytes',p=>p.rebind.observer.exactBytes=false],['independent action mismatch',p=>p.rebind.observer.actionRunId=randomUUID()],['independent artifact mismatch',p=>p.rebind.observer.artifactId=randomUUID()],['host acknowledgement only',p=>p.rebind.saved.independentEffects.matchesCanonicalBrief=false],['missing tool observation',p=>p.rebind.saved.saveMeasurements=null],['unmodeled private field',p=>p.private='refused']
 ];
 for(const [name,mutate] of faults)await t.test('rejects '+name,()=>{const p=structuredClone(fixture);mutate(p);assert.throws(()=>validateIntentProof(p),name);});
});
test('root prerequisite markers fail before live store, ADC or network reads',()=>{assert.throws(()=>assertRoot({}),/INTENT_ROOT_MARKERS_REQUIRED/);assert.throws(()=>assertRoot({PROOFGATE_LIVE:'1',PROOFGATE_BLIND_ROOT:'1'}),/INTENT_ROOT_MARKERS_REQUIRED/);assert.doesNotThrow(()=>assertRoot({PROOFGATE_LIVE:'1',PROOFGATE_BLIND_ROOT:'1',PROOFGATE_INTENT_ROOT:'1'}));});
