import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,rmSync,existsSync,mkdirSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {tmpdir,homedir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const root=process.cwd(),read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const validator=await import(pathToFileURL(resolve('scripts/check-delivery.mjs')).href);
const {CURRENT_PHASE,CURRENT_SOURCE_FILES,LOCAL_ACCEPTANCE,PENDING_ACCEPTANCE,PAYLOAD,localAcceptanceReportsMatch,validateEvidenceEnvelope,measurementAggregatesMatch,phase04RequirementIds,phase05RequirementIds,sourceSnapshot}=validator;
const hash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const gsdTools=join(process.env.CODEX_HOME||join(homedir(),'.codex'),'gsd-core/bin/gsd-tools.cjs');
// Snapshot sanitized documentary inputs once. Every case gets its own clone;
// package rewrites during a test process cannot alter an in-progress fixture.
const documentaryMetadata=read(join(root,'submission/submission.json'));
const documentaryEvidence=read(join(root,'submission/evidence.json'));
// One-second solid-white H264 artifact refusal fixture; never recorded UI evidence.
const fabricatedArtifactVideo=Buffer.from('AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAA/FtZGF0AAACrwYF//+r3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIyMiBiMzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTEyIGxvb2thaGVhZF90aHJlYWRzPTIgc2xpY2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MyBiX3B5cmFtaWQ9MiBiX2FkYXB0PTEgYl9iaWFzPTAgZGlyZWN0PTEgd2VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0cD0yIGtleWludD0yNTAga2V5aW50X21pbj0xMCBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAAGdliIQAEf/+94gfMstp+TrXchHnrS6tH1DuRnFepL3+IAAAAwAAAwAAZUDfKVB/eXDc4AAABPAAuoQsIaGCFwGoHeKCOoUwgBAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAA4pAAAAE0GaJGxBD/6qVQAAAwAAAwAAC4gAAAAQQZ5CeId/AAADAAADAAAWcQAAABABnmF0Q38AAAMAAAMAAB8wAAAAEAGeY2pDfwAAAwAAAwAAHzEAAAAZQZpoSahBaJlMCHf//qmWAAADAAADAAAs4QAAABJBnoZFESw7/wAAAwAAAwAAFnEAAAAQAZ6ldEN/AAADAAADAAAfMQAAABABnqdqQ38AAAMAAAMAAB8wAAAAGUGaqUmoQWyZTAhv//6nhAAAAwAAAwAAWUAAAAOybW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAA+gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAt10cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAoAAAAHgAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAIAAABAAAAAAJVbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAoAAAAKABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAACAG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAcBzdGJsAAAAwHN0c2QAAAAAAAAAAQAAALBhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAoAB4ABIAAAASAAAAAAAAAABFExhdmM2My4xLjEwMiBsaWJ4MjY0AAAAAAAAAAAAAAAAGP//AAAANmF2Y0MBZAAW/+EAGWdkABas2UCgPbARAAADAAEAAAMAFA8WLZYBAAZo6+PLIsD9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAH0gAAAAAAAAAGHN0dHMAAAAAAAAAAQAAAAoAAAQAAAAAFHN0c3MAAAAAAAAAAQAAAAEAAABgY3R0cwAAAAAAAAAKAAAAAQAACAAAAAABAAAUAAAAAAEAAAgAAAAAAQAAAAAAAAABAAAEAAAAAAEAABQAAAAAAQAACAAAAAABAAAAAAAAAAEAAAQAAAAAAQAACAAAAAAcc3RzYwAAAAAAAAABAAAAAQAAAAoAAAABAAAAPHN0c3oAAAAAAAAAAAAAAAoAAAMeAAAAFwAAABQAAAAUAAAAFAAAAB0AAAAWAAAAFAAAABQAAAAdAAAAFHN0Y28AAAAAAAAAAQAAADAAAABhdWR0YQAAAFltZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYzLjEuMTAy','base64');

function fixture(run:(dir:string,m:any)=>void){const dir=mkdtempSync(join(tmpdir(),'proofgate-delivery-fixture-'));try{const m=structuredClone(documentaryMetadata);m.delivery.acceptance=PENDING_ACCEPTANCE;m.currentAssessment.status='pending_root_acceptance';m.pivotEvidenceMatrix.forEach((r:any)=>r.status='pending_root_acceptance');writeFileSync(join(dir,'submission.json'),JSON.stringify(m));run(dir,m);}finally{rmSync(dir,{recursive:true,force:true});}}
function check(dir:string,stage='metadata',environment:NodeJS.ProcessEnv={}){return spawnSync(process.execPath,[resolve('scripts/check-delivery.mjs'),'--stage',stage,'--directory',dir,'--root',root],{encoding:'utf8',timeout:30000,env:{...process.env,...environment}});}
test('metadata v3 is independently valid with authentic team, separated baseline/pivot and pending current gates',()=>fixture((dir,m)=>{
 const r=check(dir,'metadata',{CODEX_HOME:join(dir,'absent-parser')});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/metadata: passed/);assert.ok(!existsSync(join(dir,'presentation.pdf')));assert.equal(m.schemaVersion,'proofgate-submission-3');assert.equal(m.delivery.acceptance,PENDING_ACCEPTANCE);assert.equal(m.evidenceMatrix.length,21);assert.equal(m.pivotEvidenceMatrix.length,5);
}));
test('metadata rejects forged acceptance, bogus team, unsupported claims and stale matrices',()=>fixture((dir,baseline)=>{
 const mutations=[(m:any)=>m.title+=' Extra',(m:any)=>m.description='word '.repeat(501),(m:any)=>m.team.members[0].name='Invented Member',(m:any)=>m.team.members[0].email='invented@example.com',(m:any)=>m.sources.team='../TEAM.md',(m:any)=>m.licenses.production.pop(),(m:any)=>m.evidenceMatrix[0].status='accepted_current_phase',(m:any)=>m.evidenceMatrix.pop(),(m:any)=>m.evidenceMatrix[0]=m.evidenceMatrix[1],(m:any)=>m.pivotEvidenceMatrix[0].id='FUTURE-01',(m:any)=>m.pivotEvidenceMatrix.pop(),(m:any)=>m.currentAssessment.requirements.pop(),(m:any)=>m.artifacts.push('.env'),(m:any)=>m.description='Guaranteed universal safety and unlimited free local inference.',(m:any)=>m.delivery.acceptance=LOCAL_ACCEPTANCE];
 for(const mutate of mutations){const m=structuredClone(baseline);mutate(m);writeFileSync(join(dir,'submission.json'),JSON.stringify(m));const r=check(dir,'metadata',{CODEX_HOME:join(dir,'absent-parser')});assert.notEqual(r.status,0);assert.match(r.stderr,/delivery:/);}
}));
test('baseline21 and pivot5 requirement scopes remain distinct and reject malformed traceability',()=>{
 const source=readFileSync(join(root,'.planning/REQUIREMENTS.md'),'utf8'),m=structuredClone(documentaryMetadata);
 assert.deepEqual(phase04RequirementIds(source).sort(),m.evidenceMatrix.map((r:any)=>r.id).sort());assert.deepEqual(phase05RequirementIds(source).sort(),m.pivotEvidenceMatrix.map((r:any)=>r.id).sort());
 const extended=source.replace('## Traceability','- [ ] **FUTURE-01**: Unaccepted future fixture.\n\n## Traceability').replace('| Requirement | Phase | Status |','| FUTURE-01 | Phase 6 | Pending |\n| Requirement | Phase | Status |');assert.deepEqual(phase04RequirementIds(extended).sort(),phase04RequirementIds(source).sort());
 const missing=source.replace(/^- \[[ x]\] \*\*CORE-01\*\*:[^\n]*\n/m,'').replace(/^\| CORE-01 \| Phase 1 \|[^\n]*\n/m,'');assert.throws(()=>phase04RequirementIds(missing),/REQUIREMENTS/);assert.throws(()=>phase04RequirementIds(source.replace('| CORE-01 | Phase 1 | Complete |','| CORE-01 | Phase 1 | Complete |\n| CORE-01 | Phase 1 | Complete |')),/REQUIREMENTS/);
});
function assertMissingCanonicalParser(){
 const dir=mkdtempSync(join(tmpdir(),'proofgate-missing-parser-fixture-'));
 try{
  // Forged isolated reports are deliberate refusal fixtures. Their passed/clean
  // prose never grants real phase acceptance in the absence of the parser.
  for(const [phase,reports] of [
   ['.planning/phases/04-judge-ready-evidence-and-delivery/',[['VERIFICATION.md','status: passed'],['REVIEW.md','status: clean'],['04-SECURITY.md','status: verified\nthreats_open: 0'],['04-UI-REVIEW.md','status: verified']]],
   [CURRENT_PHASE,[['05-VERIFICATION.md','status: passed'],['REVIEW.md','status: clean'],['05-SECURITY.md','status: verified\nthreats_open: 0'],['05-UI-REVIEW.md','status: verified']]],
  ] as [string,[string,string][]][]){mkdirSync(join(dir,phase),{recursive:true});for(const [name,header] of reports)writeFileSync(join(dir,phase,name),`---\n${header}\n---\nFabricated isolated refusal fixture; never actual acceptance.\n`);}
  const r=spawnSync(process.execPath,['--input-type=module','-e',`import {pathToFileURL} from 'node:url';const {localAcceptanceReportsMatch}=await import(pathToFileURL(process.argv[2]).href);process.stdout.write(JSON.stringify(localAcceptanceReportsMatch(process.argv[3])));`,'isolated-parser-refusal-fixture',resolve('scripts/check-delivery.mjs'),dir],{cwd:root,encoding:'utf8',timeout:15000,env:{...process.env,CODEX_HOME:join(dir,'explicitly-absent-runtime')}});
  assert.equal(r.error,undefined);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,'false');assert.ok(!existsSync(join(dir,'explicitly-absent-runtime/gsd-core/bin/gsd-tools.cjs')));
 }finally{rmSync(dir,{recursive:true,force:true});}
}
test('final acceptance fails closed with forged passed reports and an explicitly absent canonical parser',()=>{assertMissingCanonicalParser();});
test('canonical acceptance exercises real freshness/coverage when available and fail-closed absence otherwise',()=>{
 // GSD is a root release gate, not an application/offline-builder dependency.
 // The absence branch performs an actual refusal assertion; it is not a skip.
 if(!existsSync(gsdTools)){assertMissingCanonicalParser();return;}
 const dir=mkdtempSync(join(tmpdir(),'proofgate-parser-fixture-')),baseline='.planning/phases/04-judge-ready-evidence-and-delivery/',current=CURRENT_PHASE;
 const put=(name:string,text:string)=>{mkdirSync(dirname(join(dir,name)),{recursive:true});writeFileSync(join(dir,name),text);};
 const report=(phase:string,name:string,header:string)=>put(phase+name,`---\n${header}\n---\nFabricated isolated parser fixture, never actual project acceptance.\n`);
 const query=(...args:string[])=>{const r=spawnSync(process.execPath,[gsdTools,'query',...args,'--cwd',dir],{cwd:dir,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);const parsed=JSON.parse(r.stdout);assert.equal(parsed.error,undefined);return parsed;};
 try{
  mkdirSync(join(dir,baseline),{recursive:true});mkdirSync(join(dir,current),{recursive:true});put('src/baseline.ts','fabricated baseline source\n');put('.planning/REQUIREMENTS.md',readFileSync(join(root,'.planning/REQUIREMENTS.md'),'utf8'));
  for(const name of CURRENT_SOURCE_FILES)if(name!=='.planning/REQUIREMENTS.md')put(name,`Fabricated isolated coverage fixture for ${name}\n`);
  const b=query('verification.fingerprint',baseline,'src/baseline.ts'),c=query('verification.fingerprint',current,...CURRENT_SOURCE_FILES),ids=[...phase04RequirementIds(readFileSync(join(dir,'.planning/REQUIREMENTS.md'),'utf8')),...phase05RequirementIds(readFileSync(join(dir,'.planning/REQUIREMENTS.md'),'utf8'))];
  const baselineHeader=`status: passed\ncovered_files:\n  - src/baseline.ts\ncovered_digest: ${b.covered_digest}`;
  const currentHeader=`status: passed\ncovered_files:\n${c.covered_files.map((f:string)=>'  - '+f).join('\n')}\ncovered_digest: ${c.covered_digest}\nrequirements_verified:\n${ids.map((id:string)=>'  - '+id).join('\n')}`;
  report(baseline,'VERIFICATION.md',baselineHeader);report(baseline,'REVIEW.md','status: clean');report(baseline,'04-SECURITY.md','status: verified\nthreats_open: 0');report(baseline,'04-UI-REVIEW.md','status: verified');
  assert.equal(localAcceptanceReportsMatch(dir),false);report(current,'05-VERIFICATION.md',currentHeader);report(current,'REVIEW.md',`status: clean\ncovered_digest: ${c.covered_digest}`);report(current,'05-SECURITY.md',`status: verified\nthreats_open: 0\ncovered_digest: ${c.covered_digest}`);report(current,'05-UI-REVIEW.md',`status: verified\ncovered_digest: ${c.covered_digest}`);
  assert.equal(query('verification.status',current).status,'passed');assert.equal(localAcceptanceReportsMatch(dir),true);
  put(CURRENT_SOURCE_FILES[0],'Changed source after fabricated acceptance\n');assert.equal(query('verification.status',current).status,'stale');assert.equal(localAcceptanceReportsMatch(dir),false);put(CURRENT_SOURCE_FILES[0],`Fabricated isolated coverage fixture for ${CURRENT_SOURCE_FILES[0]}\n`);
  for(const [name,invalid,valid] of [
   ['REVIEW.md',`status: issues_found\ncovered_digest: ${c.covered_digest}`,`status: clean\ncovered_digest: ${c.covered_digest}`],
   ['REVIEW.md',`status: clean\ncovered_digest: v2:sha256:${'0'.repeat(64)}`,`status: clean\ncovered_digest: ${c.covered_digest}`],
   ['05-SECURITY.md',`status: verified\nthreats_open: 1\ncovered_digest: ${c.covered_digest}`,`status: verified\nthreats_open: 0\ncovered_digest: ${c.covered_digest}`],
   ['05-UI-REVIEW.md',`status: pending\ncovered_digest: ${c.covered_digest}`,`status: verified\ncovered_digest: ${c.covered_digest}`],
  ]){report(current,name!,invalid!);assert.equal(localAcceptanceReportsMatch(dir),false,name);report(current,name!,valid!);}
  report(current,'05-VERIFICATION.md',currentHeader.replace(/^  - BLIND-05$/m,''));assert.equal(localAcceptanceReportsMatch(dir),false);report(current,'05-VERIFICATION.md',currentHeader+'\nbroken: [');assert.equal(localAcceptanceReportsMatch(dir),false);report(current,'05-VERIFICATION.md',currentHeader);
  assert.equal(localAcceptanceReportsMatch(dir),true);rmSync(join(dir,current,'05-UI-REVIEW.md'));assert.equal(localAcceptanceReportsMatch(dir),false);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('ready npm test builds then runs offline only and propagates both failures',()=>{
 const p=read(join(root,'package.json'));assert.equal(p.scripts.test,'npm run build && npm run eval:offline');assert.equal(p.scripts['eval:offline'],'node --test dist/test/offline/*.test.js');assert.equal(p.scripts['eval:hosted'],'node --test --test-concurrency=1 dist/test/hosted/*.test.js');
 const dir=mkdtempSync(join(tmpdir(),'proofgate-command-fixture-'));try{for(const [buildExit,offlineExit] of [[0,0],[23,0],[0,29]]){const marker=join(dir,'offline-ran');if(existsSync(marker))rmSync(marker);writeFileSync(join(dir,'package.json'),JSON.stringify({private:true,scripts:{test:p.scripts.test,build:`node -e "process.exit(${buildExit})"`,'eval:offline':`node -e "require('fs').writeFileSync('offline-ran','yes');process.exit(${offlineExit})"`}}));const r=spawnSync('npm',['test','--silent'],{cwd:dir,encoding:'utf8',timeout:15000,env:{...process.env,npm_config_update_notifier:'false',npm_config_audit:'false'}});assert.equal(r.error,undefined);assert.equal(r.status===0,buildExit===0&&offlineExit===0);assert.equal(existsSync(marker),buildExit===0);}}finally{rmSync(dir,{recursive:true,force:true});}
});
test('bounded measurement sample truncation rejects aggregates below observed counts or duration',()=>{
 const m={samplesTruncated:true,spans:[{kind:'actor',durationMs:10}],aggregates:[{kind:'actor',count:3,totalMs:30}]};assert.equal(measurementAggregatesMatch(m),true);assert.equal(measurementAggregatesMatch({...m,samplesTruncated:false}),false);assert.equal(measurementAggregatesMatch({...m,aggregates:[{kind:'actor',count:0,totalMs:30}]}),false);assert.equal(measurementAggregatesMatch({...m,aggregates:[{kind:'actor',count:3,totalMs:9}]}),false);
});
test('strict dated actual-evidence envelope validates without dispatch, account access or fabricated success',async()=>{
 // Retained sanitized actual documentary evidence is only READ. Clones below are
 // rejection fixtures, never new actual observations or application acceptance.
 const e=structuredClone(documentaryEvidence),m=structuredClone(documentaryMetadata);
 const r=await validateEvidenceEnvelope(e,m,{root,verifySource:false});assert.equal(r.proof.ok,true);assert.equal(r.proof.newAttempts,24);assert.equal(r.proof.newCredits,6502120);assert.equal(e.accounting.totalNewAttempts,36);assert.equal(e.accounting.forecastExceeded,true);assert.equal(e.publicIntention.status,'complete');
 const faults:[string,(e:any)=>void][]=[['unknown envelope field',e=>e.accepted=true],['simulated proof',e=>e.pivotProof.proof.mode='offline'],['proof bytes changed',e=>e.pivotProof.proof.status='partial'],['private capture',e=>{e.pivotProof.proof.observations[0].evidence.captures[0].serializedBody+='PRIVATE_SENTINEL';e.pivotProof.sha256=hash(JSON.stringify(e.pivotProof.proof));}],['missing effect',e=>{e.pivotProof.proof.objectives[0].rebind.observer=null;e.pivotProof.sha256=hash(JSON.stringify(e.pivotProof.proof));}],['forecast hidden',e=>e.accounting.forecastExceeded=false],['walkthroughs ignored',e=>e.accounting.totalNewAttempts=24],['new epoch',e=>e.accounting.checkpoint.epochId='00000000-0000-4000-8000-000000000000'],['unknown erased',e=>e.accounting.checkpoint.unknownsRetained=0],['unknown replay',e=>e.accounting.checkpoint.unknownsReplayed=true],['local ledger reset',e=>e.accounting.checkpoint.creditsReserved=0],['human rehearsal invented',e=>e.walkthroughs[0].humanRehearsal=true],['fresh inference invented',e=>e.walkthroughs[0].composition='freshly composed'],['timing invented',e=>e.walkthroughs[0].elapsedMs=300000],['continuous recording invented',e=>e.backup.continuousRecording=true],['backup save invented',e=>e.backup.establishesNewSave=true],['missing actual intention status',e=>e.publicIntention.status='pending'],['pending intention proof smuggled',e=>e.publicIntention.proof={fake:true}],['unsafe payload',e=>e.browser.limitations=['Authorization: secret', '{"access_token":"secret"}']],['baseline fallback',e=>{e.pivotProof=null;}],['source keys missing',e=>delete e.source.coveredFiles['src/host.ts']],['GET capture claims fresh save',e=>e.captures.captureSource.establishesNewSave=true],['capture has wrong actual run',e=>e.captures.captureSource.runId=e.walkthroughs[0].runId],['provisional capture claims commit',e=>{e.captures.captureSource.scope='provisional_current_worktree';e.captures.sourceRevision=e.captures.captureSource.revision=e.source.revision;}],['capture erases retained history',e=>delete e.captures.retainedPrevious]];
 for(const [name,mutate] of faults){const f=structuredClone(e);mutate(f);await assert.rejects(()=>validateEvidenceEnvelope(f,m,{root,verifySource:false}),name);}
 const stale=structuredClone(e);stale.source.coveredFiles['src/host.ts']='0'.repeat(64);await assert.rejects(()=>validateEvidenceEnvelope(stale,m,{root}),/CURRENT_SOURCE_STALE/);
 const wrongUi=structuredClone(e);wrongUi.source.coveredFiles=sourceSnapshot(root);wrongUi.captures.captureSource.uiHashes['public/app.js']='0'.repeat(64);await assert.rejects(()=>validateEvidenceEnvelope(wrongUi,m,{root}),/CAPTURE_SOURCE_STALE/);
 await assert.rejects(()=>validateEvidenceEnvelope(e,m,{root,verifySource:false,screenshotBytes:Buffer.from('wrong screenshot')}),/CAPTURE_HASH/);await assert.rejects(()=>validateEvidenceEnvelope(e,m,{root,verifySource:false,backupBytes:Buffer.from('wrong video')}),/BACKUP_HASH/);
});

test('completed actual public intention keeps a separate finite allocation, expected changed result and preserved browser failure',async()=>{
 // Retained real root evidence is read only. Altered copies are refusal fixtures.
 const e=structuredClone(documentaryEvidence),m=structuredClone(documentaryMetadata);
 const r=await validateEvidenceEnvelope(e,m,{root,verifySource:false});assert.equal(r.intent.ok,true);assert.equal(r.intent.newAttempts,8);assert.equal(r.intent.newCredits,2150481);assert.equal(e.accounting.totalNewAttempts,36);assert.equal(e.accounting.totalNewCredits,9652824);assert.equal(e.publicIntention.accounting.checkpoint.callsUsed,324);assert.equal(e.publicIntention.accounting.checkpoint.creditsReserved,87971452);assert.equal(e.browser.assertions.passed,3);assert.equal(e.browser.assertions.failedRequests,1);
 const faults:[string,(e:any)=>void][]=[
  ['invented intention status',e=>e.publicIntention.status='accepted'],['missing intention proof',e=>e.publicIntention.proof=null],['offline intention',e=>e.publicIntention.proof.mode='offline'],['prepared host substitution',e=>e.publicIntention.proof.composition.recipe=e.pivotProof.proof.objectives[0].rebind.before.recipe],['model observation substituted',e=>e.publicIntention.proof.modelObservations[1].text='fabricated'],['independent claim altered',e=>e.publicIntention.proof.rebind.actualAfter[0].savingCents++],['altered allocation',e=>e.publicIntention.accounting.allocation.newAttempts=32],['hidden MCP charges',e=>e.publicIntention.accounting.actual.toolAttempts=2],['hidden overall charges',e=>e.publicIntention.accounting.actual.newCredits=0],['new intent epoch',e=>e.publicIntention.accounting.checkpoint.epochId='00000000-0000-4000-8000-000000000000'],['intent unknown erased',e=>e.publicIntention.accounting.checkpoint.unknowns=0],['intent current checkpoint invented',e=>e.publicIntention.accounting.checkpoint.callsUsed=316],['old browser4/4 forged',e=>e.browser.assertions.passed=4],['404 explanation used for application failure',e=>e.browser.assertions.resolution.failedNetwork.entries[0].url='http://127.0.0.1:3100/api/blind/runs'],['continuous new-intent backup invented',e=>e.backup.scope='current_intention_continuous_recording']
 ];
 for(const [name,mutate] of faults){const changed=structuredClone(e);mutate(changed);await assert.rejects(()=>validateEvidenceEnvelope(changed,m,{root,verifySource:false}),name);}
});

test('current fourth walkthrough preserves separate finite tool charges and rejects altered observations/browser failures',async()=>{
 const e=structuredClone(documentaryEvidence),m=structuredClone(documentaryMetadata),r=await validateEvidenceEnvelope(e,m,{root,verifySource:false});assert.equal(e.walkthroughs.length,3);assert.equal(r.current.newAttempts,4);assert.equal(r.current.newCredits,1050011);assert.equal(r.current.newProviderAttempts,0);assert.equal(e.currentWalkthrough.record.after.ledger.calls,328);assert.equal(e.currentWalkthrough.record.after.ledger.credits,89021463);assert.equal(e.backup.scope,'current_intention_walkthrough');assert.equal(e.backup.retainedPrevious.seconds,49);
 const faults:[string,(e:any)=>void][]=[['human fourth rehearsal invented',e=>e.currentWalkthrough.record.humanRehearsal=true],['fresh inference substituted',e=>e.currentWalkthrough.record.composition='fresh_hosted'],['hidden provider attempt',e=>e.currentWalkthrough.record.newProviderAttempts=1],['hidden tool charges',e=>e.currentWalkthrough.record.newAttempts=2],['new epoch',e=>e.currentWalkthrough.record.after.ledger.id='00000000-0000-4000-8000-000000000000'],['erased unknowns',e=>e.currentWalkthrough.record.after.unknowns=0],['new provider charge',e=>e.currentWalkthrough.record.after.provider++],['draft guard absent',e=>e.currentWalkthrough.record.steps[1].status.draft=''],['stale result hidden',e=>e.currentWalkthrough.record.steps[2].status.result='saved'],['changed private result absent',e=>e.currentWalkthrough.record.steps[4].status.result='$130.00'],['independent save absent',e=>e.currentWalkthrough.record.steps[6].status.save='Host acknowledged'],['allocation enlarged',e=>e.currentWalkthrough.allocation.ceilings.newToolAttempts=8],['source capture deleted',e=>e.currentWalkthrough.captureHashes.pop()],['zero of four declared resolved',e=>e.browser.assertions={passed:0,total:4,consoleErrors:7,failedRequests:0,resolution:{status:'resolved',details:'Fabricated isolated refusal fixture',failedNetwork:null}}],['console errors declared resolved',e=>e.browser.assertions={passed:4,total:4,consoleErrors:1,failedRequests:0,resolution:{status:'resolved',details:'Fabricated isolated refusal fixture',failedNetwork:null}}]];
 for(const [name,mutate] of faults){const f=structuredClone(e);mutate(f);f.currentWalkthrough.recordSha256=hash(JSON.stringify(f.currentWalkthrough.record,null,2)+'\n');await assert.rejects(()=>validateEvidenceEnvelope(f,m,{root,verifySource:false}),name);}
 const resolved=structuredClone(e);resolved.browser.assertions={passed:4,total:4,consoleErrors:0,failedRequests:0,resolution:{status:'resolved',details:'Fabricated isolated parser-contract fixture; never an actual browser observation',failedNetwork:null}};assert.equal((await validateEvidenceEnvelope(resolved,m,{root,verifySource:false})).current.newProviderAttempts,0);
});
test('content/release fail closed for missing assets, absent tooling and unknown stage',()=>fixture(dir=>{
 for(const stage of ['content','release','unknown']){const r=check(dir,stage,{PROOFGATE_ARTIFACT_PYTHON:''});assert.notEqual(r.status,0);assert.match(r.stderr,/delivery:/);}
}));
test('PPTX and exact nine-file ZIP validators exercise fabricated isolated artifact fixtures when tooling is configured',()=>fixture(dir=>{
 const python=process.env.PROOFGATE_ARTIFACT_PYTHON;
 if(!python){assert.throws(()=>validator.inspectArtifacts(dir,'content'),/ARTIFACT_TOOLING_REQUIRED/);return;}
 // Fake slide/image/video package used only to validate file structure.
 // It does not depend on a mutable packaged recording or establish UI evidence.
 writeFileSync(join(dir,'backup.mp4'),fabricatedArtifactVideo);
 const create=spawnSync(python,['-c',`from reportlab.pdfgen import canvas\nfrom PIL import Image\nfrom pathlib import Path\nimport zipfile,sys\np=Path(sys.argv[1]);c=canvas.Canvas(str(p/'presentation.pdf'),pagesize=(960,540));c.drawString(40,480,'ProofGate: Public Plans, Private Results');c.drawString(40,440,'synthetic hosted potential unknown causal limits');c.save();Image.new('RGB',(640,480),'white').save(p/'workbench.png')\nwith zipfile.ZipFile(p/'presentation.pptx','w') as z:\n z.writestr('[Content_Types].xml','<Types/>');z.writestr('ppt/presentation.xml','<presentation/>');z.writestr('ppt/slides/slide1.xml','<slide><text>ProofGate: Public Plans, Private Results</text></slide>')`,dir],{encoding:'utf8',timeout:15000});assert.equal(create.status,0,create.stderr);
 writeFileSync(join(dir,'architecture.svg'),'<svg xmlns="http://www.w3.org/2000/svg"><text>isolated fixture</text></svg>');writeFileSync(join(dir,'evidence.json'),'{}');writeFileSync(join(dir,'pitch.md'),'Isolated fixture');writeFileSync(join(dir,'rehearsal.md'),'Isolated fixture');
 const inspected=validator.inspectArtifacts(dir,'content');assert.equal(inspected.pages,1);assert.equal(inspected.width,640);assert.equal(inspected.backup.seconds,1);
 const manifest=PAYLOAD.map((name:string)=>`${hash(readFileSync(join(dir,name)))}  ${name}`).join('\n')+'\n';writeFileSync(join(dir,'SHA256SUMS'),manifest);
 const archive=(extra=false)=>{const r=spawnSync(python,['-c',`from pathlib import Path\nimport zipfile,sys,json\np=Path(sys.argv[1])\nwith zipfile.ZipFile(p/'proofgate.zip','w') as z:\n for n in json.loads(sys.argv[2]): z.write(p/n,n)\n if sys.argv[3]=='extra': z.writestr('../unsafe','unreviewed')`,dir,JSON.stringify([...PAYLOAD,'SHA256SUMS']),extra?'extra':'clean'],{encoding:'utf8',timeout:15000});assert.equal(r.status,0,r.stderr);};
 archive();assert.equal(validator.inspectArtifacts(dir,'release').pages,1);archive(true);assert.throws(()=>validator.inspectArtifacts(dir,'release'),/ARTIFACT_INSPECTION_FAILED/);archive();writeFileSync(join(dir,'pitch.md'),'Bytes changed after ZIP');assert.throws(()=>validator.inspectArtifacts(dir,'release'),/ARTIFACT_INSPECTION_FAILED/);
 const corrupt=spawnSync(python,['-c',`import zipfile,sys\nfrom pathlib import Path\np=Path(sys.argv[1])\nwith zipfile.ZipFile(p/'presentation.pptx','a') as z: z.writestr('ppt/slides/slide2.xml','<slide/>')`,dir],{encoding:'utf8',timeout:15000});assert.equal(corrupt.status,0,corrupt.stderr);assert.throws(()=>validator.inspectArtifacts(dir,'content'),/ARTIFACT_INSPECTION_FAILED/);
}));
