import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js';
import { createHost } from '../../src/host.js';
import { openEffectStore } from '../../fixture/server.js';
import { EvidenceExportSchema, MIGRATION } from '../../src/contracts.js';
import type { HostPorts, ModelAdapter } from '../../src/model.js';
const token='phase04-isolated-test-token';
const headers={authorization:`Bearer ${token}`};
const digest=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
function adapter(ports:HostPorts):ModelAdapter{return {mode:'offline',async generate(kind,input,_schema,deadline,runId){
 const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:0,deadline});ports.markDispatched(id);
 await new Promise(resolve=>setTimeout(resolve,kind==='checker'?8:12));
 let json:any={classification:'benign',confidence:0.99,reasonCode:'offline'};
 if(kind==='actor'){const p=JSON.parse(input);json=p.nextAction==='save_internal_draft'?{kind:'tool',tool:p.nextAction,args:{draft:{sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:[`${runId}:facts`]}}}:p.nextAction==='read_project_context'?{kind:'tool',tool:p.nextAction,args:{projectId:'proofgate-demo'}}:{kind:'tool',tool:p.nextAction,args:{dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'}};}
 ports.settleAttempt(id,{usage:{prompt:1,output:1,thought:0,cache:0},outcome:'known'});return {json,modelVersion:'offline-injected',responseId:'offline-response',usage:{prompt:1,output:1,thought:0,cache:0}};
}};}
function setup(lost=false,modelAdapter:HostOptionsModel=adapter){const dir=mkdtempSync(join(tmpdir(),'proofgate-phase04-'));const fixture=join(dir,'fixture.sqlite');let saves=0;
 const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter,...(lost?{fixtureTransport:(actual:Transport)=>{const wrapper:Transport={async start(){actual.onmessage=m=>{if('result' in m&&(m.result as any)?.structuredContent?.draftId){saves++;void actual.close();return;}wrapper.onmessage?.(m);};actual.onerror=e=>wrapper.onerror?.(e);actual.onclose=()=>wrapper.onclose?.();await actual.start();},send:m=>actual.send(m),close:()=>actual.close()};return wrapper;}}:{})});
 return {host,fixture,get saves(){return saves;},async close(){await host.close();rmSync(dir,{recursive:true,force:true});}};
}
type HostOptionsModel=ModelAdapter|((ports:HostPorts)=>ModelAdapter);
async function start(s:ReturnType<typeof setup>){const r=await s.host.app.inject({method:'POST',url:'/api/runs',headers,payload:{scenario:'clean'}});assert.equal(r.statusCode,202);const id=r.json().runId;await s.host.waitForRun(id);return id;}
test('CR01 hashes arbitrary returned and operator identities without credential keyword assumptions',async()=>{
 const apiKey='AIza'+'A'.repeat(35),oauth='ya29.'+'B'.repeat(32),other='AIza'+'C'.repeat(35);
 const s=setup(false,ports=>{const base=adapter(ports);return {...base,async generate(...args){return {...await base.generate(...args),modelVersion:other,responseId:oauth};}};});
 try{const feed=s.host.store.getFeed();s.host.store.activateFeed(feed.version,{version:feed.version+1,signatures:[{id:apiKey,pattern:'never-matched',reasonCode:other}]});const id=await start(s);
  const assertProjection=async()=>{for(const path of [`/api/runs/${id}/export`,`/api/runs/${id}`]){const reply=await s.host.app.inject({url:path,headers});assert.equal(reply.statusCode,200,reply.body);for(const value of [apiKey,oauth,other])assert.ok(!reply.body.includes(value),`opaque identity leaked at ${path}`);const m=path.endsWith('/export')?reply.json().measurements:reply.json().audit.measurements;for(const row of [...m.spans,...m.models].filter((r:any)=>r.kind==='actor'||r.kind==='checker'||r.role)){assert.equal(row.responseId,null);assert.equal(row.responseIdHash,digest(oauth));assert.equal(row.returnedModel,null);assert.equal(row.returnedModelHash,digest(other));}}
  };
  await assertProjection();const row=s.host.store.db.prepare("SELECT * FROM events WHERE run_id=? AND stage='measurements'").get(id) as any;assert.ok(!row.details.includes(oauth));assert.ok(!row.details.includes(other));
  // Legacy persisted records must go through the same boundary, even with valid identity characters.
  const data=JSON.parse(row.details);for(const span of data.spans.filter((r:any)=>r.kind==='actor'||r.kind==='checker')){span.requestedModel=apiKey;span.returnedModel=other;span.responseId=oauth;delete span.responseIdHash;delete span.returnedModelHash;}
  s.host.store.db.prepare('UPDATE events SET details=? WHERE id=?').run(JSON.stringify(data),row.id);await assertProjection();
  const e=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json();EvidenceExportSchema.parse(e);assert.equal(e.feed.signatures[0].id,null);assert.equal(e.feed.signatures[0].reasonCode,null);assert.equal(e.feed.signatures[0].idHash,digest(apiKey));assert.equal(e.feed.signatures[0].reasonCodeHash,digest(other));
  const known=data.spans.find((r:any)=>r.kind==='actor');known.requestedModel='gemini-3.5-flash';known.returnedModel='gemini-3.5-flash-lite';s.host.store.db.prepare('UPDATE events SET details=? WHERE id=?').run(JSON.stringify(data),row.id);const preserved=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json().measurements.models.find((r:any)=>r.role==='actor');assert.equal(preserved.requestedModel,'gemini-3.5-flash');assert.equal(preserved.returnedModel,'gemini-3.5-flash-lite');assert.equal(preserved.returnedModelHash,digest('gemini-3.5-flash-lite'));assert.equal(preserved.responseIdHash,digest(oauth));
 }finally{await s.close();}
});
test('WR01 records semantic-OFF signature outcome and historical matched rule after feed mutation',async()=>{
 const s=setup();try{let p=s.host.store.getPolicy();s.host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,semantic:false}});let feed=s.host.store.getFeed();const rule={id:'AIza'+'D'.repeat(35),pattern:'quarantine-me',reasonCode:'AIza'+'E'.repeat(35)};s.host.store.activateFeed(feed.version,{version:feed.version+1,signatures:[rule]});p=s.host.store.getPolicy();feed=s.host.store.getFeed();
  const response=await s.host.app.inject({method:'POST',url:'/api/runs',headers,payload:{scenario:'clean',advisory:'quarantine-me synthetic advisory'}});const id=response.json().runId;await s.host.waitForRun(id);assert.equal(s.host.view(id).evidence[0]!.status,'quarantined');
  const expected={status:'quarantined',matchedSignature:{idHash:digest(rule.id),patternHash:digest(rule.pattern),reasonCodeHash:digest(rule.reasonCode)}};
  const original=s.host.store.db.prepare("SELECT details FROM events WHERE run_id=? AND stage='inspection' ORDER BY id LIMIT 1").get(id) as any;assert.deepEqual(JSON.parse(original.details).admission,expected);
  s.host.store.activateFeed(feed.version,{version:feed.version+1,signatures:[{id:'replacement',pattern:'different',reasonCode:'new_rule'}]});
  const e=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json();EvidenceExportSchema.parse(e);const event=e.events.find((x:any)=>x.sourceId===`${id}:advisory`);assert.equal(event.reasonCode,'signature_match');assert.equal(event.admission.classification,null);assert.equal(event.admission.confidence,null);assert.equal(event.admission.status,expected.status);assert.deepEqual(event.admission.matchedSignature,expected.matchedSignature);assert.equal(event.policyVersion,p.version);assert.equal(event.feedVersion,feed.version);assert.equal(event.hashes.policyHash,digest(p));assert.equal(event.hashes.feedHash,digest(feed));assert.notEqual(e.feed.hash,event.hashes.feedHash);
  const status=await s.host.app.inject({url:`/api/runs/${id}`,headers});assert.equal(status.statusCode,200);assert.ok(!status.body.includes(rule.id));assert.ok(!status.body.includes(rule.reasonCode));assert.equal(status.json().decisions[0].reasonCode,'signature_match');
  const legacy=JSON.parse(original.details);delete legacy.admission;s.host.store.db.prepare("UPDATE events SET details=? WHERE run_id=? AND stage='inspection' AND reason=?").run(JSON.stringify(legacy),id,rule.reasonCode);const historical=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json().events.find((x:any)=>x.sourceId===`${id}:advisory`);assert.equal(historical.admission.status,null);assert.equal(historical.admission.matchedSignature,null);
 }finally{await s.close();}
});
test('WR01 revalidation persists admitted or quarantined outcome with the exact new basis',async()=>{
 for(const quarantine of [false,true]){const s=setup();try{const id=await start(s);let p=s.host.store.getPolicy();s.host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,semantic:false}});let feed=s.host.store.getFeed();const rule={id:'historical-notes-rule',pattern:'Synthetic private notes',reasonCode:'notes_rule'};s.host.store.activateFeed(feed.version,{version:feed.version+1,signatures:quarantine?[rule]:[]});p=s.host.store.getPolicy();feed=s.host.store.getFeed();
   if(quarantine)assert.throws(()=>s.host.ports.currentClearance(id,'actor'),/SOURCE_ADMISSION_INVALIDATED/);else s.host.ports.currentClearance(id,'actor');
   const e=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json();EvidenceExportSchema.parse(e);const event=e.events.findLast((x:any)=>x.sourceId===`${id}:notes`);assert.equal(event.admission.status,quarantine?'quarantined':'admitted');assert.deepEqual(event.admission.matchedSignature,quarantine?{idHash:digest(rule.id),patternHash:digest(rule.pattern),reasonCodeHash:digest(rule.reasonCode)}:null);assert.equal(event.policyVersion,p.version);assert.equal(event.feedVersion,feed.version);assert.equal(event.hashes.policyHash,digest(p));assert.equal(event.hashes.feedHash,digest(feed));
  }finally{await s.close();}}
});
test('canonical export authenticates and independently reopens actual stdio effects with measured spans',async()=>{const s=setup();try{const id=await start(s);const response=await s.host.app.inject({url:`/api/runs/${id}/export`,headers});assert.equal(response.statusCode,200);const e=response.json();assert.equal(e.schemaVersion,'proofgate-evidence-1');assert.equal(e.run.runId,id);assert.equal(e.independentEffects.status,'observed');assert.equal(e.independentEffects.count,1);assert.equal(e.independentEffects.matchesCanonicalDraft,true);const reader=openEffectStore(s.fixture);try{assert.equal(e.independentEffects.effects[0].contentHash,digest(JSON.parse(reader.read(id)[0]!.content)));}finally{reader.close();}
 for(const kind of ['deterministic','checker','actor','mcp','overall']){const m=e.measurements.spans.find((x:any)=>x.kind===kind);assert.ok(m,kind);assert.equal(m.unit,'ms');assert.ok(m.durationMs>=0);assert.equal(m.outcome,'resolved');assert.ok(m.boundary.length>0);}
 assert.ok(e.measurements.spans.filter((x:any)=>x.kind==='checker').every((x:any)=>x.durationMs>=5));assert.ok(e.measurements.spans.filter((x:any)=>x.kind==='actor').every((x:any)=>x.durationMs>=8));assert.equal(e.measurements.mode,'offline');assert.equal(e.measurements.hardware.node,process.version);assert.ok(e.measurements.hardware.cpuCores>0);assert.equal(e.measurements.models[0].returnedModel,'offline-injected');assert.equal(e.ledger.scope,'whole_epoch');
 const before=s.host.store.db.prepare('SELECT * FROM ledger').get();const attempts=s.host.store.db.prepare('SELECT * FROM attempts').all();for(const url of [`/api/runs/${id}`,`/api/runs/${id}/export`])assert.equal((await s.host.app.inject({url,headers})).statusCode,200);assert.deepEqual(s.host.store.db.prepare('SELECT * FROM ledger').get(),before);assert.deepEqual(s.host.store.db.prepare('SELECT * FROM attempts').all(),attempts);
 for(const url of [`/api/runs/${id}/export`,`/api/runs/${id}/%65xport`,`/api/%72uns/${id}/export`])assert.notEqual((await s.host.app.inject({url})).statusCode,200);assert.equal((await s.host.app.inject({url:`/api/runs/${id}/export`,headers:{authorization:'Bearer wrong'}})).statusCode,401);assert.equal((await s.host.app.inject({url:'/api/runs/absent/export',headers})).statusCode,404);
}finally{await s.close();}});
test('lost actual save reply is observed independently while host remains blocked unknown charged and unreplayed',async()=>{const s=setup(true);try{const id=await start(s);const before=s.host.view(id);assert.equal(before.state,'blocked');const e=(await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).json();assert.equal(e.independentEffects.count,1);assert.equal(e.independentEffects.hostAcknowledged,false);assert.equal(e.independentEffects.matchesCanonicalDraft,null);assert.equal(e.run.state,'blocked');assert.ok(e.attempts.some((a:any)=>a.kind==='tool'&&a.outcome==='unknown'));assert.deepEqual(s.host.view(id).resources,before.resources);assert.equal(s.saves,1);}finally{await s.close();}});
test('export and audit omit poisoned persisted details identities private text and unknown keys; foreign ownership is denied',async()=>{const s=setup();try{const id=await start(s);const canary='sk-canary-credential-secret-123456789';s.host.store.db.prepare('INSERT INTO events(run_id,stage,reason,details) VALUES (?,?,?,?)').run(id,canary,canary,JSON.stringify({sourceText:canary,thought:canary,thoughtSignature:canary,headers:canary,modelVersion:canary,responseId:canary,unknown:canary}));const p=s.host.store.getPolicy();s.host.store.activatePolicy(p.version,{...p,version:p.version+1,tariffs:{...p.tariffs,asOf:canary}});const feed=s.host.store.getFeed();s.host.store.activateFeed(feed.version,{version:feed.version+1,signatures:[{id:canary,pattern:canary,reasonCode:'canary_secret'}]});
 const rows=s.host.store.db.prepare('SELECT * FROM sources WHERE run_id=?').all(id) as any[];for(const row of rows)s.host.store.db.prepare('UPDATE sources SET text=? WHERE id=?').run(canary,row.id);
 for(const path of [`/api/runs/${id}/export`,`/api/runs/${id}`]){const reply=await s.host.app.inject({url:path,headers});assert.equal(reply.statusCode,200);const exported=path.endsWith('/export')?reply.body:JSON.stringify(reply.json().audit);assert.ok(!exported.includes(canary));assert.doesNotMatch(exported,/thoughtSignature|sourceText|headers/);}
 s.host.store.db.prepare('UPDATE runs SET caller=? WHERE id=?').run('foreign',id);assert.equal((await s.host.app.inject({url:`/api/runs/${id}/export`,headers})).statusCode,404);
}finally{await s.close();}});
test('historical measurements and unavailable recorder stay unavailable; oversized projection fails with sanitized error',async()=>{const s=setup();try{const id=await start(s);s.host.store.db.prepare("DELETE FROM events WHERE run_id=? AND stage='measurements'").run(id);rmSync(s.fixture);const reply=await s.host.app.inject({url:`/api/runs/${id}/export`,headers});assert.equal(reply.statusCode,200);assert.deepEqual(reply.json().measurements.spans,[]);assert.equal(reply.json().measurements.status,'unavailable');assert.equal(reply.json().measurements.hardware,null);assert.equal(reply.json().independentEffects.count,null);assert.equal(reply.json().independentEffects.status,'unavailable');
 s.host.store.db.prepare('INSERT INTO events(run_id,stage,reason,details) VALUES (?,?,?,?)').run(id,'inspection','benign',JSON.stringify({private:'secret-'+ 'x'.repeat(262144)}));const blocked=await s.host.app.inject({url:`/api/runs/${id}/export`,headers});assert.equal(blocked.statusCode,400);assert.deepEqual(blocked.json(),{code:'CONTROL_RESPONSE_BOUND'});
}finally{await s.close();}});
test('failed checker records an actual rejected span without invented returned model identity',async()=>{const dir=mkdtempSync(join(tmpdir(),'proofgate-phase04-failed-'));const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:join(dir,'fixture.sqlite'),modelAdapter:{mode:'offline',async generate(){await new Promise(resolve=>setTimeout(resolve,8));throw new Error('secret model failure');}}});try{const r=await host.app.inject({method:'POST',url:'/api/runs',headers,payload:{scenario:'clean'}});const id=r.json().runId;await host.waitForRun(id);const e=(await host.app.inject({url:`/api/runs/${id}/export`,headers})).json();const span=e.measurements.spans.find((m:any)=>m.kind==='checker');assert.equal(span.outcome,'rejected');assert.ok(span.durationMs>=5);assert.equal(span.returnedModel,null);assert.equal(span.responseId,null);assert.equal(e.measurements.spans.find((m:any)=>m.kind==='overall').outcome,'rejected');assert.ok(!JSON.stringify(e).includes('secret'));}finally{await host.close();rmSync(dir,{recursive:true,force:true});}});
