import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createModelAdapter,parseResponse,type HostPorts,type Kind } from '../../src/model.js';
import { PolicySchema,VerdictSchema,DraftPlanSchema,MIGRATION,type Policy } from '../../src/contracts.js';
import { createHost } from '../../src/host.js';
import { openEffectStore } from '../../fixture/server.js';
import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js';
const initial=PolicySchema.parse(JSON.parse(readFileSync('config/policy.json','utf8')));
const credentials={type:'authorized_user',client_id:'offline-client',client_secret:'offline-secret',refresh_token:'offline-refresh'};
const raw={candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify({classification:'benign',confidence:0.99,reasonCode:'offline_fixture'})}]}}],modelVersion:'offline-sdk-fixture',responseId:'offline-response',usageMetadata:{promptTokenCount:5,candidatesTokenCount:4,thoughtsTokenCount:0,cachedContentTokenCount:0}};
function harness(policy:Policy=structuredClone(initial)){
 const attempts:{kind:Kind;dispatched:boolean;outcome:string;usage:unknown}[]=[];let deny=false;
 const ports:HostPorts={currentClearance(){if(deny)throw new Error('DENIED');return policy;},reserveAttempt(i){attempts.push({kind:i.kind,dispatched:false,outcome:'reserved',usage:null});return String(attempts.length-1);},markDispatched(id){attempts[+id]!.dispatched=true;},settleAttempt(id,r){attempts[+id]!.outcome=r.outcome;attempts[+id]!.usage=r.usage;},emit(){}};
 return {ports,attempts,policy,setDeny(){deny=true;}};
}
const authReply=()=>Response.json({access_token:'synthetic-token',expires_in:3600,token_type:'Bearer'});
test('model removed while OAuth awaits dispatches zero stale generation wire',async()=>{
 const h=harness();let auth=0,gen=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async(input)=>{if(String(input).includes('oauth2')){auth++;h.policy.models.checker='gemini-3.5-flash';h.policy.models.allowlist=['gemini-3.5-flash'];return authReply();}gen++;return Response.json(raw);}});
 await adapter.generate('checker','{}',VerdictSchema,Date.now()+25000,'race').catch(()=>{});assert.equal(gen,0,'removed pinned checker must never reach generation wire');assert.equal(auth,1);assert.equal(h.attempts.filter(a=>a.kind==='checker'&&a.dispatched).length,0);
});
test('chunked response reading obeys shared deadline and cancels unfinished body',async()=>{
 const h=harness();h.policy.limits.attemptMs=30;let cancelled=false;let gen=0;
 const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async(input)=>{if(String(input).includes('oauth2'))return authReply();gen++;return new Response(new ReadableStream<Uint8Array>({start(c){c.enqueue(new TextEncoder().encode('{'));},cancel(){cancelled=true;}}));}});
 const begin=Date.now();const result=await Promise.race([adapter.generate('checker','{}',VerdictSchema,Date.now()+1000,'slow').then(()=> 'success',()=> 'rejected'),new Promise<string>(r=>setTimeout(()=>r('unbounded'),150))]);
 assert.equal(result,'rejected','a stalled chunked body must stop at attempt deadline');assert.ok(Date.now()-begin<150);assert.equal(cancelled,true);assert.equal(gen,1);assert.equal(h.attempts.find(a=>a.kind==='checker')?.outcome,'unknown');
});
test('pre-dispatch clearance failure releases only proven unsent reservation',async()=>{
 const h=harness();const reserve=h.ports.reserveAttempt;h.ports.reserveAttempt=i=>{const id=reserve(i);h.setDeny();return id;};let wires=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async()=>{wires++;return authReply();}});
 await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+1000,'unsent'));assert.equal(wires,0);assert.equal(h.attempts[0]?.dispatched,false);assert.equal(h.attempts[0]?.outcome,'unsent','unsent clearance failure must release reservation');
});
for(const [name,usage] of [['missing',undefined],['negative',{promptTokenCount:-1,candidatesTokenCount:2}],['fractional',{promptTokenCount:2.5,candidatesTokenCount:2}],['overflow',{promptTokenCount:Number.MAX_SAFE_INTEGER+1,candidatesTokenCount:2}]] as const)test(`${name} provider usage remains unknown and charged without replay`,async()=>{
 const h=harness();let gen=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async(input)=>String(input).includes('oauth2')?authReply():(gen++,Response.json({...raw,usageMetadata:usage}))});const result=await adapter.generate('checker','{}',VerdictSchema,Date.now()+1000,'usage');assert.equal(result.usage,null);assert.equal(h.attempts.find(a=>a.kind==='checker')?.outcome,'unknown','unknown provider usage must remain unknown');assert.equal(gen,1);
});
for(const [name,reply] of Object.entries({refused:{...raw,promptFeedback:{blockReason:'SAFETY'}},truncated:{...raw,candidates:[{...raw.candidates[0],finishReason:'MAX_TOKENS'}]},empty:{...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:''}]}}]},extraVerdict:{...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify({classification:'benign',confidence:0.99,reasonCode:'ok',allow:true})}]}}]},unexpectedPart:{...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:'{}',functionCall:{name:'save_internal_draft'}}]}}]}}))test(`${name} provider reply fails closed with one charged generation`,async()=>{const h=harness();let gen=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async(input)=>String(input).includes('oauth2')?authReply():(gen++,Response.json(reply))});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+1000,'reply'));assert.equal(gen,1);assert.equal(h.attempts.find(a=>a.kind==='checker')?.outcome,'unknown');});
test('declared and chunked oversized provider bodies fail within byte bound',async()=>{for(const declared of [true,false]){const h=harness();h.policy.limits.responseBytes=1024;let cancel=false;let gen=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async(input)=>{if(String(input).includes('oauth2'))return authReply();gen++;return new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(1025));},cancel(){cancel=true;}}),{headers:declared?{'content-length':'1025'}:{}});}});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+1000,'oversize'));assert.equal(gen,1);assert.equal(cancel,true,'rejected body must be cancelled');assert.equal(h.attempts.find(a=>a.kind==='checker')?.outcome,'unknown');}});

const token='fault-test-token-123456789';
function hostSetup(verdict:unknown){const dir=mkdtempSync(join(tmpdir(),'proofgate-fault-'));const fixture=join(dir,'fixture.sqlite');let actors=0;const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:ports=>({mode:'offline',async generate(kind,input,_schema,deadline,runId){const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:256,deadline});ports.markDispatched(id);if(kind==='actor')actors++;if(verdict instanceof Error){ports.settleAttempt(id,{usage:null,outcome:'unknown'});throw verdict;}ports.settleAttempt(id,{usage:null,outcome:'known'});return{json:verdict,modelVersion:'offline-injected',responseId:'offline',usage:null};}})});return{host,fixture,actors:()=>actors};}
async function start(host:ReturnType<typeof createHost>){const r=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});assert.equal(r.statusCode,202);return r.json().runId as string;}
for(const [name,verdict] of Object.entries({malformed:{allow:true},empty:null,truncated:'{"classification":',uncertain:{classification:'uncertain',confidence:0.99,reasonCode:'unsure'},lowConfidence:{classification:'benign',confidence:0.1,reasonCode:'low'},unavailable:new Error('unavailable')}))test(`${name} checker never admits evidence or dispatches actor/save`,async()=>{const s=hostSetup(verdict);try{const id=await start(s.host);const v=await s.host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(v.evidence.length,0);assert.equal(s.actors(),0);const e=openEffectStore(s.fixture);try{assert.equal(e.read(id).length,0);}finally{e.close();}const attempts=s.host.store.db.prepare('SELECT * FROM attempts WHERE run_id=?').all(id) as any[];assert.equal(attempts.filter(a=>a.kind==='checker'&&a.dispatched).length,1);assert.equal(attempts.filter(a=>a.kind==='actor').length,0);}finally{await s.host.close();}});

test('one active action per run rejects overlapping dispatch and releases its unsent charge',async()=>{const s=hostSetup(null);try{const id=await start(s.host);await s.host.waitForRun(id);const before=s.host.view(id).resources;const reserve=()=>s.host.ports.reserveAttempt({runId:id,kind:'actor',requestBytes:10,outputTokens:1,deadline:Date.now()+1000});const first=reserve();s.host.ports.markDispatched(first);const second=reserve();assert.throws(()=>s.host.ports.markDispatched(second),/ACTION_IN_FLIGHT/,'overlapping dispatch must be denied');s.host.ports.settleAttempt(second,{usage:null,outcome:'unsent'});s.host.ports.settleAttempt(first,{usage:null,outcome:'unknown'});assert.equal(s.host.view(id).resources.callsUsed,before.callsUsed+1);assert.ok(s.host.view(id).resources.creditsReserved>before.creditsReserved);}finally{await s.host.close();}});
test('shared call and credit admission is atomic and new runs retain epoch and unknown charge',async()=>{const s=hostSetup(new Error('synthetic unknown'));try{const id=await start(s.host);await s.host.waitForRun(id);const before=s.host.view(id).resources;const p=s.host.store.getPolicy();s.host.store.activatePolicy(p.version,{...p,version:p.version+1,limits:{...p.limits,calls:before.callsUsed+1}});const input={runId:id,kind:'actor' as const,requestBytes:10,outputTokens:1,deadline:Date.now()+1000};const a=s.host.ports.reserveAttempt(input);s.host.ports.markDispatched(a);s.host.ports.settleAttempt(a,{usage:null,outcome:'unknown'});const full=s.host.view(id).resources;assert.throws(()=>s.host.ports.reserveAttempt(input),/ALLOWANCE_EXHAUSTED/);assert.deepEqual(s.host.view(id).resources,full);const next=await start(s.host);const v=await s.host.waitForRun(next);assert.equal(v.state,'blocked');assert.equal(v.resources.epochId,before.epochId);assert.equal(v.resources.callsUsed,full.callsUsed);assert.equal(v.resources.creditsReserved,full.creditsReserved);const p2=s.host.store.getPolicy();s.host.store.activatePolicy(p2.version,{...p2,version:p2.version+1,limits:{...p2.limits,calls:64,credits:full.creditsReserved}});assert.throws(()=>s.host.ports.reserveAttempt({...input,deadline:Date.now()+1000}),/ALLOWANCE_EXHAUSTED/);assert.deepEqual(s.host.view(id).resources.creditsReserved,full.creditsReserved);const l=s.host.store.db.prepare('SELECT * FROM ledger').get() as any;const sums=s.host.store.db.prepare("SELECT count(*) calls,sum(credits) credits FROM attempts WHERE outcome!='unsent'").get() as any;assert.equal(l.calls,sums.calls);assert.equal(l.credits,sums.credits);}finally{await s.host.close();}});
test('invalid reservation sizes and output tokens cannot corrupt shared allowance',async()=>{const s=hostSetup(null);try{const id=await start(s.host);await s.host.waitForRun(id);const before=s.host.view(id).resources;for(const bad of [{requestBytes:-1,outputTokens:1},{requestBytes:1.5,outputTokens:1},{requestBytes:1,outputTokens:-100000},{requestBytes:1,outputTokens:2049},{requestBytes:NaN,outputTokens:1}])assert.throws(()=>s.host.ports.reserveAttempt({runId:id,kind:'actor',deadline:Date.now()+1000,...bad}),/REQUEST_BOUND|OUTPUT_BOUND/,'invalid reservation must deny');assert.deepEqual(s.host.view(id).resources,before);}finally{await s.host.close();}});
test('deadline expired before wire has zero reservation and dispatch',async()=>{const h=harness();let wires=0;const adapter=createModelAdapter(h.ports,{credentials,wireFetch:async()=>{wires++;return authReply();}});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()-1,'expired'));assert.equal(wires,0);assert.ok(h.attempts.every(a=>!a.dispatched&&a.outcome==='unsent'));});
test('lost real stdio save reply leaves one independent effect charged and never replayed',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'proofgate-lost-save-'));const fixture=join(dir,'fixture.sqlite');let saves=0;
 const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:ports=>({mode:'offline',async generate(kind,input,_schema,deadline,runId){const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:kind==='actor'?2048:256,deadline});ports.markDispatched(id);let json:any={classification:'benign',confidence:0.99,reasonCode:'offline'};if(kind==='actor'){const p=JSON.parse(input);const notes=p.evidence.find((s:any)=>s.sourceId.endsWith(':notes'));const facts=p.evidence.find((s:any)=>s.sourceId.endsWith(':facts'));if(!notes)json={kind:'tool',tool:'read_project_context',args:{projectId:'proofgate-demo'}};else if(!facts)json={kind:'tool',tool:'read_dependency_evidence',args:{dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'}};else {const draft=DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:[facts.sourceId]});json={kind:'tool',tool:'save_internal_draft',args:{draft}};}}ports.settleAttempt(id,{usage:null,outcome:'known'});return {json,modelVersion:'offline-injected',responseId:'offline',usage:null};}}),fixtureTransport:actual=>{const wrapper:Transport={async start(){actual.onmessage=m=>{if('result' in m&&(m.result as any)?.structuredContent?.draftId){saves++;void actual.close();return;}wrapper.onmessage?.(m);};actual.onerror=e=>wrapper.onerror?.(e);actual.onclose=()=>wrapper.onclose?.();await actual.start();},send:m=>actual.send(m),close:()=>actual.close()};return wrapper;}});
 try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(v.effects.reconciled,false);assert.equal(saves,1);const e=openEffectStore(fixture);try{assert.equal(e.read(id).length,1,'lost reply does not mean absent save');}finally{e.close();}const attempts=host.store.db.prepare('SELECT * FROM attempts WHERE run_id=? ORDER BY rowid').all(id) as any[];assert.ok(attempts.every(a=>a.dispatched===1));assert.equal(attempts.filter(a=>a.kind==='tool'&&a.outcome==='unknown').length,1,'unacknowledged save must remain unknown at host acceptance; timeout cancellation is a separate metered notification');assert.equal(attempts.length,v.resources.callsUsed);assert.equal(attempts.reduce((n,a)=>n+a.credits,0),v.resources.creditsReserved);assert.equal(v.resources.usage,null);assert.equal(v.resources.estimatedCost,null);
 const second=await start(host);const v2=await host.waitForRun(second);assert.equal(v2.resources.epochId,v.resources.epochId);assert.ok(v2.resources.callsUsed>v.resources.callsUsed);assert.equal(saves,2);const e2=openEffectStore(fixture);try{assert.equal(e2.read(id).length,1);assert.equal(e2.read(second).length,1);}finally{e2.close();}
 }finally{await host.close();}
});
