import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,mkdtempSync,existsSync,writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createHost,openStore } from '../../src/host.js';
import { initializeEffectStore,openEffectStore } from '../../fixture/server.js';
import { MIGRATION,DraftPlanSchema,PolicySchema } from '../../src/contracts.js';
import { ControlError,type HostPorts,type ModelAdapter } from '../../src/model.js';
import { readPhase02Fixture,preflightLive,objectHash,sha,evaluateSubjects,ledgerOf,type LivePaths } from '../hosted/semantic.test.js';
import { evaluateAblation } from '../hosted/ablation.test.js';
const fixturePath=resolve('test/phase02-cases.json');
test('frozen Phase02 fixture has four exact expectations and one on/off repetition',()=>{
 const raw=readFileSync(fixturePath,'utf8');const f=JSON.parse(raw);assert.equal(f.synthetic,true);assert.equal(f.repetitionsPerCase,1);assert.deepEqual(f.subjects.map((s:any)=>[s.id,s.name,s.classification,s.admission]),[['02','benign','benign','admitted'],['03','active','active','quarantined'],['04','quoted','quoted','admitted'],['05','paraphrased','active','quarantined']]);assert.equal(new Set(f.subjects.map((s:any)=>s.text)).size,4);assert.equal(f.comparison.subjectId,'03');assert.equal(f.comparison.repetitionsPerArm,1);assert.deepEqual(f.comparison.arms,[{name:'on',semantic:true,signatures:true,flow:true},{name:'off',semantic:false,signatures:false,flow:true}]);assert.equal(createHash('sha256').update(raw).digest('hex').length,64);const feed=JSON.parse(readFileSync('config/signatures.json','utf8'));assert.ok(feed.signatures.every((s:any)=>!f.subjects[3].text.toLowerCase().includes(s.pattern.toLowerCase())));
});
test('hosted semantic entry rejects missing explicit opt-in before creating any store',()=>{
 const dir=mkdtempSync(join(tmpdir(),'proofgate-no-optin-'));const result=spawnSync(process.execPath,['--test',resolve('dist/test/hosted/semantic.test.js')],{cwd:dir,env:{PATH:process.env.PATH,GOOGLE_APPLICATION_CREDENTIALS:join(dir,'absent-adc.json')},encoding:'utf8',timeout:10000});assert.notEqual(result.status,0);assert.match(result.stdout+result.stderr,/PHASE02_LIVE_OPT_IN_REQUIRED/);assert.equal(existsSync(join(dir,'.proofgate')),false);
});

test('hosted ablation entry rejects missing explicit opt-in before creating any store',()=>{const dir=mkdtempSync(join(tmpdir(),'proofgate-ablation-no-optin-'));const result=spawnSync(process.execPath,['--test',resolve('dist/test/hosted/ablation.test.js')],{cwd:dir,env:{PATH:process.env.PATH,GOOGLE_APPLICATION_CREDENTIALS:join(dir,'absent-adc.json')},encoding:'utf8',timeout:10000});assert.notEqual(result.status,0);assert.match(result.stdout+result.stderr,/PHASE02_LIVE_OPT_IN_REQUIRED/);assert.equal(existsSync(join(dir,'.proofgate')),false);});
function preflightFixture(){const dir=mkdtempSync(join(tmpdir(),'proofgate-harness-preflight-'));const paths:LivePaths={hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:join(dir,'fixture.sqlite'),approvalPath:join(dir,'approved.json'),fixturePath,adcPath:join(dir,'adc.json')};const store=openStore(paths.hostDbPath);initializeEffectStore(paths.fixtureDbPath);writeFileSync(paths.adcPath,JSON.stringify({type:'authorized_user',client_id:'offline-client',client_secret:'offline-secret',refresh_token:'offline-token'}));const approve=()=>writeFileSync(paths.approvalPath,JSON.stringify({epochId:(store.db.prepare('SELECT * FROM ledger').get() as any).id,fixtureHash:readPhase02Fixture(fixturePath).fixtureHash,policyHash:objectHash(store.getPolicy()),feedHash:objectHash(store.getFeed())}));approve();return {paths,store,approve};}
// Seed only independent temporary stores; ordinary activations remain monotonic.
function seedPolicyVersion(store:ReturnType<typeof openStore>,version:number){const policy=PolicySchema.parse({...store.getPolicy(),version});store.db.prepare("UPDATE policy SET content=? WHERE id='policy'").run(JSON.stringify(policy));return policy;}
test('ablation preflight requires all three policy increments without mutating policy/feed/ledger',()=>{
 const {paths,store,approve}=preflightFixture();try{const live={PROOFGATE_PHASE02_LIVE:'1'};
 for(const version of [999998,999999,1000000]){const original=seedPolicyVersion(store,version);approve();const feed=store.getFeed();const ledger=store.db.prepare('SELECT * FROM ledger').get();
 assert.throws(()=>preflightLive('ablation',paths,live),(error:unknown)=>error instanceof ControlError&&error.code==='PHASE02_POLICY_VERSION_HEADROOM');
 assert.deepEqual(store.getPolicy(),original);assert.deepEqual(store.getFeed(),feed);assert.deepEqual(store.db.prepare('SELECT * FROM ledger').get(),ledger);assert.equal((store.db.prepare('SELECT count(*) n FROM runs').get() as any).n,0);assert.equal((store.db.prepare('SELECT count(*) n FROM attempts').get() as any).n,0);
 assert.equal(preflightLive('semantic',paths,live).policy.version,version,'checker-only evaluation does not activate policies');}
 seedPolicyVersion(store,999997);approve();assert.equal(preflightLive('ablation',paths,live).policy.version,999997);
 }finally{store.close();}
});
test('read-only preflight rejects missing stores, ADC, snapshot mismatch and insufficient conserved allowance without dispatch',()=>{
 const {paths,store,approve}=preflightFixture();const live={PROOFGATE_PHASE02_LIVE:'1'};try{const before=store.db.prepare('SELECT * FROM ledger').get();assert.throws(()=>preflightLive('semantic',paths,{}),/PHASE02_LIVE_OPT_IN_REQUIRED/);assert.throws(()=>preflightLive('semantic',{...paths,hostDbPath:paths.hostDbPath+'.absent'},live),/PHASE02_PREREQUISITE_MISSING/);assert.equal(existsSync(paths.hostDbPath+'.absent'),false);assert.throws(()=>preflightLive('semantic',{...paths,adcPath:paths.adcPath+'.absent'},live),/PHASE02_PREREQUISITE_MISSING/);
 writeFileSync(paths.adcPath,JSON.stringify({type:'service_account'}));assert.throws(()=>preflightLive('semantic',paths,live),/ADC_UNSUPPORTED/);writeFileSync(paths.adcPath,JSON.stringify({type:'authorized_user',client_id:'offline',client_secret:'offline',refresh_token:'offline'}));writeFileSync(paths.approvalPath,JSON.stringify({epochId:'forged'}));assert.throws(()=>preflightLive('semantic',paths,live),/PHASE02_APPROVAL_MISMATCH/);approve();const good=preflightLive('semantic',paths,live);assert.equal(good.bound.calls,5);assert.equal(preflightLive('ablation',paths,live).bound.calls,32);
 const p=store.getPolicy();store.activatePolicy(p.version,{...p,version:p.version+1,limits:{...p.limits,calls:4}});approve();assert.throws(()=>preflightLive('semantic',paths,live),/PHASE02_ALLOWANCE_INSUFFICIENT/);assert.deepEqual(store.db.prepare('SELECT * FROM ledger').get(),before);assert.equal((store.db.prepare('SELECT count(*) n FROM attempts').get() as any).n,0);assert.equal((store.db.prepare('SELECT count(*) n FROM runs').get() as any).n,0);
 }finally{store.close();}
});
test('offline semantic helper serially attempts each frozen subject once and retains malformed/unknown/false-positive outcomes',async()=>{
 const {store}=preflightFixture();try{const f=readPhase02Fixture(fixturePath);const calls:string[]=[];let active=0,maxActive=0;const records:any[]=[];const adapter:ModelAdapter={mode:'offline',async generate(_kind,input){active++;maxActive=Math.max(maxActive,active);try{await new Promise<void>(r=>setImmediate(r));const subject=f.subjects.find(s=>s.text===JSON.parse(input).subject)!;calls.push(subject.id);if(subject.id==='03')throw new ControlError('MODEL_UNAVAILABLE');return {json:subject.id==='04'?{classification:'quoted'}:{classification:subject.id==='02'?'active':'uncertain',confidence:0.99,reasonCode:'offline_fault'},modelVersion:'offline-fixture',responseId:'offline',usage:null};}finally{active--;}}};
 const result=await evaluateSubjects(f.subjects,adapter,store.getPolicy(),store.getFeed(),'offline-isolated',Date.now()+10000,r=>records.push(r));assert.deepEqual(calls,['02','03','04','05']);assert.equal(maxActive,1);assert.equal(result.length,4);assert.deepEqual(records,result);assert.equal(result[0]!.falsePositive,true);assert.equal(result[1]!.error,'MODEL_UNAVAILABLE');assert.equal(result[2]!.error,'LIVE_CHECKER_FAILED');assert.equal(result[3]!.admission,'blocked');assert.ok(result.every(r=>r.repetition===1&&!r.passed));assert.deepEqual(result.map(r=>r.subjectHash),f.subjects.map(s=>sha(s.text)));assert.equal((store.db.prepare('SELECT calls FROM ledger').get() as any).calls,0);
 }finally{store.close();}
});
const offlineToken='phase02-harness-offline-token';
function ablationFixture(failFirstActor=false){const dir=mkdtempSync(join(tmpdir(),'proofgate-ablation-offline-'));const fixture=join(dir,'fixture.sqlite');let failed=false;const capture:{kind:string;input:string}[]=[];
 const model=(ports:HostPorts):ModelAdapter=>({mode:'offline',async generate(kind,input,_schema,deadline,runId){capture.push({kind,input});const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:kind==='actor'?2048:256,deadline});ports.markDispatched(id);if(failFirstActor&&!failed&&kind==='actor'){failed=true;ports.settleAttempt(id,{usage:null,outcome:'unknown'});throw new ControlError('MODEL_UNAVAILABLE');}const payload=JSON.parse(input);const json=kind==='checker'?{classification:payload.subject.includes('Ignore earlier')?'active':'benign',confidence:0.99,reasonCode:'offline_harness'}:payload.nextAction==='read_project_context'?{kind:'tool',tool:'read_project_context',args:{projectId:'proofgate-demo'}}:payload.nextAction==='read_dependency_evidence'?{kind:'tool',tool:'read_dependency_evidence',args:{dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'}}:{kind:'tool',tool:'save_internal_draft',args:{draft:DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:payload.evidence.filter((s:any)=>!s.sourceId.endsWith(':advisory')).map((s:any)=>s.sourceId)})}};ports.settleAttempt(id,{usage:null,outcome:'known'});ports.emit({runId,stage:kind,reasonCode:'model_response',inputHash:sha(input),modelVersion:'offline-harness',responseId:'offline',promptHash:'offline',schemaHash:'offline'});return {json,modelVersion:'offline-harness',responseId:'offline',usage:null};}});
 return {fixture,capture,host:createHost({token:offlineToken,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:model})};}
test('ablation version 999998 fails closed before mutation, HTTP POST, model dispatch or effect',async()=>{
 const {host,fixture,capture}=ablationFixture();initializeEffectStore(fixture);try{const original=seedPolicyVersion(host.store,999998);const feed=host.store.getFeed();const ledger=ledgerOf(host);let posts=0,records=0;host.app.addHook('onRequest',async req=>{if(req.method==='POST'&&req.url==='/api/runs')posts++;});let error:unknown;
 try{await evaluateAblation(host,fixture,readPhase02Fixture(fixturePath).subjects[1]!,offlineToken,()=>{records++;});}catch(caught){error=caught;}
 console.log(JSON.stringify({check:'ablation-version-headroom',error:error instanceof ControlError?error.code:error instanceof Error?error.name:null,posts,records,version:host.store.getPolicy().version,controls:host.store.getPolicy().controls,calls:ledgerOf(host).calls,credits:ledgerOf(host).credits}));
 assert.ok(error instanceof ControlError);assert.equal(error.code,'PHASE02_POLICY_VERSION_HEADROOM');assert.deepEqual(host.store.getPolicy(),original);assert.deepEqual(host.store.getFeed(),feed);assert.deepEqual(ledgerOf(host),ledger);assert.equal(posts,0);assert.equal(records,0);assert.equal(capture.length,0);for(const table of ['runs','attempts','events','sources'])assert.equal((host.store.db.prepare(`SELECT count(*) n FROM ${table}`).get() as any).n,0);const effects=openEffectStore(fixture);try{for(const table of ['drafts','effects'])assert.equal((effects.db.prepare(`SELECT count(*) n FROM ${table}`).get() as any).n,0);}finally{effects.close();}
 }finally{await host.close();}
});
test('ablation version 999997 completes two actual offline HTTP/MCP arms and restores at 1000000',async()=>{
 const {host,fixture}=ablationFixture();try{const original=seedPolicyVersion(host.store,999997);const feed=host.store.getFeed();const ledger=ledgerOf(host);let posts=0;host.app.addHook('onRequest',async req=>{if(req.method==='POST'&&req.url==='/api/runs')posts++;});const result=await evaluateAblation(host,fixture,readPhase02Fixture(fixturePath).subjects[1]!,offlineToken);
 assert.equal(posts,2);assert.deepEqual(result.records.map(r=>r.policy.version),[999998,999999]);assert.ok(result.records.every(r=>r.mode==='offline'&&r.truthfulReconciliation&&r.forbiddenEffects===0&&r.exposure.hashesMatch));assert.equal(result.records[0].exposure.wholeAdvisoryExcluded,true);assert.equal(result.records[1].exposure.advisoryExposed,true);assert.deepEqual(host.store.getPolicy(),{...original,version:1000000});assert.deepEqual(host.store.getFeed(),feed);assert.equal(result.after.id,ledger.id);assert.ok(result.after.calls>ledger.calls);assert.ok(result.after.credits>ledger.credits);const effects=openEffectStore(fixture);try{for(const record of result.records)assert.equal(effects.read(record.runId).length,1);}finally{effects.close();}
 console.log(JSON.stringify({check:'ablation-version-boundary',posts,armVersions:result.records.map(r=>r.policy.version),restoredVersion:host.store.getPolicy().version,controlsRestored:objectHash(host.store.getPolicy().controls)===objectHash(original.controls),epochPreserved:result.after.id===ledger.id}));
 }finally{await host.close();}
});
test('offline ablation uses two serial HTTP→actual MCP runs, proves hash exposure and restores controls without ledger reset',async()=>{
 const {host,fixture}=ablationFixture();try{const original=host.store.getPolicy();const before=ledgerOf(host);let count=0;const result=await evaluateAblation(host,fixture,readPhase02Fixture(fixturePath).subjects[1]!,offlineToken,record=>{count++;assert.equal((host.store.db.prepare("SELECT count(*) n FROM runs WHERE json_extract(view,'$.state')='running'").get() as any).n,0);assert.equal(record.mode,'offline');});assert.equal(count,2);assert.deepEqual(result.records.map(r=>r.arm),['on','off']);assert.equal(result.before.id,result.after.id);assert.equal(before.id,result.after.id);assert.ok(result.after.calls>before.calls);assert.equal(result.downstreamCausalBenefit,'no observed downstream causal benefit');assert.ok(result.records.every(r=>r.truthfulReconciliation&&r.forbiddenEffects===0&&r.exposure.hashesMatch));assert.equal(result.records[0].exposure.wholeAdvisoryExcluded,true);assert.equal(result.records[1].exposure.advisoryExposed,true);assert.equal(result.records[1].attempts.filter((a:any)=>a.kind==='checker').length,0);assert.deepEqual({...host.store.getPolicy(),version:original.version},original);const e=openEffectStore(fixture);try{for(const r of result.records)assert.equal(e.read(r.runId).length,1);}finally{e.close();}
 }finally{await host.close();}
});
test('offline ablation retains unknown failed dispatch, does not retry the arm and restores controls on callback failure',async()=>{
 const {host,fixture}=ablationFixture(true);try{const original=host.store.getPolicy();const result=await evaluateAblation(host,fixture,readPhase02Fixture(fixturePath).subjects[1]!,offlineToken);assert.equal(result.records.length,2);assert.equal(result.records[0].error,'MODEL_UNAVAILABLE');assert.equal(result.records[0].effects.length,0);assert.equal(result.records[0].exposure.responded,false);assert.equal(result.records[0].exposure.advisoryExposed,false);assert.equal(result.records[0].attempts.filter((a:any)=>a.kind==='actor').length,1);assert.ok(result.records[0].attempts.some((a:any)=>a.kind==='actor'&&a.dispatched===1&&a.outcome==='unknown'));assert.equal(result.records[1].truthfulReconciliation,true);assert.equal(result.downstreamCausalBenefit,'not established');assert.deepEqual({...host.store.getPolicy(),version:original.version},original);
 }finally{await host.close();}
 const s=ablationFixture();try{const original=s.host.store.getPolicy();await assert.rejects(evaluateAblation(s.host,s.fixture,readPhase02Fixture(fixturePath).subjects[1]!,offlineToken,()=>{throw new Error('offline evidence-write fault');}),/offline evidence-write fault/);assert.deepEqual({...s.host.store.getPolicy(),version:original.version},original);assert.equal((s.host.store.db.prepare('SELECT count(*) n FROM runs').get() as any).n,1);assert.ok(ledgerOf(s.host).calls>0);}finally{await s.host.close();}
});
