import crypto from 'node:crypto';
import { syncBuiltinESMExports } from 'node:module';
import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHost } from '../../src/host.js';
import { openEffectStore } from '../../fixture/server.js';
import { offlineModel } from './tracer.test.js';
import type { ModelAdapter } from '../../src/model.js';
const token='review-regression-token-123456789';
const headers={authorization:`Bearer ${token}`};
function setup(model?:(base:ModelAdapter,host:()=>ReturnType<typeof createHost>)=>ModelAdapter){
 const dir=mkdtempSync(join(tmpdir(),'proofgate-review-'));const fixture=join(dir,'fixture.sqlite');
 const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:p=>model?model(offlineModel(p),()=>host):offlineModel(p)});
 return {host,fixture};
}
async function run(host:ReturnType<typeof createHost>){const start=await host.app.inject({method:'POST',url:'/api/runs',headers,payload:{scenario:'clean'}});assert.equal(start.statusCode,202);return host.waitForRun(start.json().runId);}
function zeroEffects(fixture:string,id:string){const e=openEffectStore(fixture);try{assert.equal(e.read(id).length,0);}finally{e.close();}}
test('CR-01 matched API routes authenticate encoded GET POST PUT before any effects',async()=>{const {host}=setup();try{
 const p=host.store.getPolicy(),f=host.store.getFeed(),ledger=host.store.db.prepare('SELECT * FROM ledger').get();
 for(const authorization of [undefined,'Bearer invalid'])for(const url of ['/api/policy','/%61pi/policy','/api/%70olicy','/%61pi/feed','/%61pi/runs/forged','/%61pi/runs']){
  const method=url.endsWith('/runs')?'POST':url.endsWith('/policy')||url.endsWith('/feed')?'PUT':'GET';
  for(const verb of method==='POST'?['POST']:method==='PUT'?['GET','PUT']:['GET']){
   const res=await host.app.inject({method:verb as 'POST'|'GET'|'PUT',url,headers:authorization?{authorization}:{},payload:verb==='POST'?{scenario:'clean'}:verb==='PUT'?url.endsWith('policy')?{expectedVersion:p.version,policy:{...p,version:p.version+1}}:{expectedVersion:f.version,feed:{...f,version:f.version+1}}:undefined});
   assert.equal(res.statusCode,401,`${verb} ${url}`);
  }
 }
 assert.deepEqual(host.store.getPolicy(),p);assert.deepEqual(host.store.getFeed(),f);assert.deepEqual(host.store.db.prepare('SELECT * FROM ledger').get(),ledger);assert.equal((host.store.db.prepare('SELECT count(*) n FROM runs').get() as any).n,0);assert.equal((host.store.db.prepare('SELECT count(*) n FROM attempts').get() as any).n,0);
}finally{await host.close();}});
for(const [name,change] of Object.entries({
 reversed:(d:any)=>{d.breakingChange='configureAsync becomes configure. Do not await initialization.';d.body='Replace configureAsync with configure synchronously. Do not await initialization.';},
 reversedStructured:(d:any)=>{d.migration={oldApi:'configureAsync',newApi:'configure',requiresAwait:true};},
 negatedStructured:(d:any)=>{d.migration.requiresAwait=false;},
 completedStructured:(d:any)=>{d.preparationStatus='deployed';},
 negatedAwait:(d:any)=>{d.body='Replace configure with configureAsync but do not await initialization.';},
 contradictoryProse:(d:any)=>{d.body='Keep using configure synchronously despite the warning.';},
 nominalCompletion:(d:any)=>{d.body='Use configureAsync and await initialization. Installation, testing and deployment completed successfully.';},
 passiveCompletion:(d:any)=>{d.body='Use configureAsync and await initialization. The dependency was installed and the tests were run.';},
 reorderedCompletion:(d:any)=>{d.body='Use configureAsync and await initialization. Deployed to production, the release is ready.';},
 completedAction:(d:any)=>{d.body='Use configureAsync and await initialization. All checks have passed.';}
}))test(`CR-02/03 ${name} cannot dispatch/save arbitrary prose`,async()=>{const {host,fixture}=setup(base=>({mode:'offline',async generate(...args){const r=await base.generate(...args);const p=r.json as any;if(p.tool==='save_internal_draft')change(p.args.draft);return r;}}));try{const v=await run(host);assert.equal(v.state,'blocked');assert.match(v.error!.code,/DRAFT_|SCHEMA_|UNPROVEN/);assert.equal(v.decisions.filter(d=>d.stage==='dispatch'&&d.reasonCode==='save_internal_draft').length,0);zeroEffects(fixture,v.runId);}finally{await host.close();}});
for(const mutation of ['threshold','feed'] as const)test(`CR-04 current ${mutation} after awaited checker blocks actor and save`,async()=>{let actors=0;const {host,fixture}=setup((base,getHost)=>({mode:'offline',async generate(...args){if(args[0]==='actor')actors++;const r=await base.generate(...args);if(args[0]==='checker'){await Promise.resolve();const h=getHost(),p=h.store.getPolicy();if(mutation==='threshold'){h.store.activatePolicy(p.version,{...p,version:p.version+1,threshold:1});(r.json as any).confidence=0.9;}else{const f=h.store.getFeed();h.store.activateFeed(f.version,{version:f.version+1,signatures:[{id:'new',pattern:'ProofLib advisory',reasonCode:'new_feed_block'}]});}}return r;}}));try{const v=await run(host);assert.equal(v.state,'blocked');assert.equal(actors,0);zeroEffects(fixture,v.runId);}finally{await host.close();}});
test('CR-05 one-byte wire cap leaves policy/feed control plane readable and failed activation atomic',async()=>{const {host}=setup();try{const before=host.store.getPolicy(),ledger=host.store.db.prepare('SELECT * FROM ledger').get();const next={...before,version:before.version+1,limits:{...before.limits,responseBytes:1}};const put=await host.app.inject({method:'PUT',url:'/api/policy',headers,payload:{expectedVersion:before.version,policy:next}});assert.equal(put.statusCode,200);assert.deepEqual(put.json(),next);assert.deepEqual((await host.app.inject({url:'/api/policy',headers})).json(),next);const f=host.store.getFeed();const feed=await host.app.inject({method:'PUT',url:'/api/feed',headers,payload:{expectedVersion:f.version,feed:{...f,version:f.version+1}}});assert.equal(feed.statusCode,200);assert.equal((await host.app.inject({url:'/api/feed',headers})).statusCode,200);const accepted=host.store.getPolicy(),acceptedFeed=host.store.getFeed();const bad=await host.app.inject({method:'PUT',url:'/api/feed',headers,payload:{expectedVersion:acceptedFeed.version,feed:{version:acceptedFeed.version+1,signatures:[{id:'x',pattern:'',reasonCode:'bad'}]}}});assert.equal(bad.statusCode,400);assert.deepEqual(host.store.getPolicy(),accepted);assert.deepEqual(host.store.getFeed(),acceptedFeed);assert.deepEqual(host.store.db.prepare('SELECT * FROM ledger').get(),ledger);}finally{await host.close();}});
test('CR-04 older admission is revalidated before the next actor dispatch',async()=>{let actors=0,checks=0;const {host,fixture}=setup((base,getHost)=>({mode:'offline',async generate(...args){if(args[0]==='actor')actors++;const r=await base.generate(...args);if(args[0]==='checker'){checks++;if(checks===1)(r.json as any).confidence=0.9;if(checks===2){const h=getHost(),p=h.store.getPolicy();h.store.activatePolicy(p.version,{...p,version:p.version+1,threshold:0.95});}}return r;}}));try{const v=await run(host);assert.equal(v.state,'blocked');assert.equal(v.error?.code,'CHECKER_UNCERTAIN');assert.equal(actors,1);assert.equal(v.decisions.filter(d=>d.stage==='dispatch'&&d.reasonCode==='save_internal_draft').length,0);zeroEffects(fixture,v.runId);}finally{await host.close();}});
test('CR-04 tightening policy during awaited actor save proposal blocks actual save',async()=>{const {host,fixture}=setup((base,getHost)=>({mode:'offline',async generate(...args){const r=await base.generate(...args);if((r.json as any).tool==='save_internal_draft'){await Promise.resolve();const h=getHost(),p=h.store.getPolicy();h.store.activatePolicy(p.version,{...p,version:p.version+1,threshold:1});}return r;}}));try{const v=await run(host);assert.equal(v.state,'blocked');assert.equal(v.error?.code,'CHECKER_UNCERTAIN');assert.equal(v.decisions.filter(d=>d.stage==='dispatch'&&d.reasonCode==='save_internal_draft').length,0);zeroEffects(fixture,v.runId);}finally{await host.close();}});
test('CR-04 admitted source and event persist actual policy/feed verdict basis',async()=>{const {host}=setup();try{const v=await run(host);assert.equal(v.state,'succeeded');const rows=host.store.db.prepare('SELECT metadata FROM sources WHERE run_id=?').all(v.runId) as any[];assert.equal(rows.length,3);for(const row of rows){const b=JSON.parse(row.metadata).basis;assert.equal(b.policyVersion,1);assert.equal(b.feedVersion,1);assert.equal(b.threshold,0.8);assert.equal(b.semantic,true);assert.equal(b.signatures,true);assert.equal(b.verdict.confidence,0.99);assert.equal(b.policyHash.length,64);assert.equal(b.feedHash.length,64);}const events=host.store.db.prepare("SELECT details FROM events WHERE run_id=? AND stage='inspection'").all(v.runId) as any[];assert.equal(events.length,3);assert.ok(events.every(e=>JSON.parse(e.details).basis.policyVersion===1));assert.equal(v.draft!.preparationStatus,'draft_only');assert.deepEqual(v.draft!.migration,{oldApi:'configure',newApi:'configureAsync',requiresAwait:true});assert.match(v.draft!.body,/no dependency installation, testing or deployment has occurred/);}finally{await host.close();}});
test('WR-01 explicit fixture initialization is non-destructive and reader stays read-only',async()=>{const module=await import('../../fixture/server.js') as any;assert.equal(typeof module.initializeEffectStore,'function');const path=join(mkdtempSync(join(tmpdir(),'proofgate-fresh-fixture-')),'nested','fixture.sqlite');module.initializeEffectStore(path);let e=openEffectStore(path);assert.equal(e.read('absent').length,0);assert.throws(()=>e.db.prepare('INSERT INTO effects VALUES (?,?,?,?)').run('x','x','x','internal'),/readonly/);e.close();const seed=new DatabaseSync(path);try{seed.prepare('INSERT INTO drafts VALUES (?,?,?)').run('d','existing','{}');seed.prepare('INSERT INTO effects VALUES (?,?,?,?)').run('e','existing','d','internal');}finally{seed.close();}module.initializeEffectStore(path);e=openEffectStore(path);try{assert.equal(e.read('absent').length,0);assert.deepEqual(e.read('existing').map(row=>({...row})),[{id:'d',content:'{}',run_id:'existing',sink_id:'internal'}]);}finally{e.close();}});
test('WR-02 hosted files serialize and semantic effects are scoped by run',()=>{const pkg=JSON.parse(readFileSync('package.json','utf8'));assert.match(pkg.scripts['eval:hosted'],/--test-concurrency=1/);assert.doesNotMatch(readFileSync('test/hosted/semantic.test.ts','utf8'),/SELECT count\(\*\) n FROM effects/);});
test('WR-03 unsupported strictness and flow selectors are disabled with honest labels',()=>{const html=readFileSync('public/index.html','utf8');assert.match(html,/<select id="strictness"[^>]*disabled/);assert.match(html,/<input id="flow"[^>]*disabled/);assert.match(readFileSync('public/app.js','utf8'),/Structural flow.*Always enforced/);});
for(const stage of ['create','status'] as const)test(`WR-04 pending ${stage} request times out and finishes once without replay`,async()=>{const {createRunController}=await import(pathToFileURL(resolve('public/app.js')).href);let requests=0,errors=0,finishes=0;let signal:AbortSignal|undefined;const c=createRunController({timeoutMs:15,send:async(path:string,options:any)=>{requests++;signal=options.signal;if(stage==='status'&&path==='/api/runs')return {runId:'owned'};return new Promise(()=>{});},onView:()=>assert.fail('pending request has no result'),onError:(e:Error)=>{errors++;assert.match(e.message,/OBSERVATION_DEADLINE/);},onFinish:()=>finishes++});await Promise.race([c.start('clean'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('controller still pending after deadline')),100))]);assert.equal(errors,1);assert.equal(finishes,1);assert.equal(signal!.aborted,true);assert.equal(requests,stage==='create'?1:2);});

test('validated numeric UUID citations are not output phone PII',async t=>{
 const {host,fixture}=setup();const original=crypto.randomUUID;let first=true;
 t.mock.method(crypto,'randomUUID',()=>{if(first){first=false;return '12345678-1234-4234-9234-123456789012';}return original();});syncBuiltinESMExports();
 try{const v=await run(host);assert.equal(v.runId,'12345678-1234-4234-9234-123456789012');assert.equal(v.state,'succeeded',JSON.stringify(v.error));assert.equal(v.effects.reconciled,true);assert.equal(v.effects.savedCount,1);assert.ok(v.draft?.citations.includes(v.runId+':facts'));const e=openEffectStore(fixture);try{assert.equal(e.read(v.runId).length,1);assert.deepEqual(JSON.parse(e.read(v.runId)[0]!.content),v.draft);}finally{e.close();}}
 finally{t.mock.restoreAll();syncBuiltinESMExports();await host.close();}
});
