import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,existsSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { createHost } from '../../src/host.js';
import { openEffectStore } from '../../fixture/server.js';
import type { HostPorts, ModelAdapter } from '../../src/model.js';
import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js';
import { DraftPlanSchema, MIGRATION,renderDraft } from '../../src/contracts.js';

const phase02=JSON.parse(readFileSync('test/phase02-cases.json','utf8'));
const phase02Active=phase02.subjects.find((s:any)=>s.name==='active').text as string;
async function customStart(host:ReturnType<typeof createHost>,advisory:string){const r=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean',advisory}});assert.equal(r.statusCode,202,r.body);return r.json().runId as string;}

export const token='boundary-test-token-123456789';
export function scriptedModel(ports:HostPorts, mutate:(kind:string,input:any,json:any)=>any=(_k,_i,j)=>j, capture:string[]=[]):ModelAdapter {
 return {mode:'offline',async generate(kind,input,_schema,deadline,runId){
  const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:kind==='actor'?2048:256,deadline});ports.markDispatched(id);
  const payload=JSON.parse(input);let json:any;
  if(kind==='checker')json={classification:'benign',confidence:0.99,reasonCode:'offline_injected'};
  else {capture.push(input);const evidence=payload.evidence as {sourceId:string;text:string}[];const notes=evidence.find(e=>e.sourceId.endsWith(':notes'));const facts=evidence.find(e=>e.sourceId.endsWith(':facts'));
   json=!notes?{kind:'tool',tool:'read_project_context',args:{projectId:'proofgate-demo'}}:!facts?{kind:'tool',tool:'read_dependency_evidence',args:{dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'}}:{kind:'tool',tool:'save_internal_draft',args:{draft:DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:[notes.sourceId,facts.sourceId]})}};
  }
  try{json=mutate(kind,payload,json);ports.settleAttempt(id,{usage:null,outcome:'known'});return {json,modelVersion:'offline-injected',responseId:'offline',usage:null};}catch(e){ports.settleAttempt(id,{usage:null,outcome:'unknown'});throw e;}
 }};
}
export function setup(mutate?:Parameters<typeof scriptedModel>[1],capture:string[]=[],fixtureTransport?:(t:Transport)=>Transport){const dir=mkdtempSync(join(tmpdir(),'proofgate-boundary-'));const fixture=join(dir,'fixture.sqlite');const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:p=>scriptedModel(p,mutate,capture),fixtureTransport});return {host,fixture};}
export async function start(host:ReturnType<typeof createHost>){const res=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});assert.equal(res.statusCode,202);return res.json().runId as string;}
export function effects(fixture:string,runId:string){if(!existsSync(fixture))return [];const store=openEffectStore(fixture);try{return store.read(runId);}finally{store.close();}}
function toolDispatches(host:ReturnType<typeof createHost>,id:string,name:string){return host.store.db.prepare("SELECT count(*) n FROM events WHERE run_id=? AND stage='dispatch' AND reason=?").get(id,name) as {n:number};}

test('forged write is rejected by HTTP, host proposal and actual MCP; independent effects stay zero',async()=>{
 const {host,fixture}=setup((kind,_input,json)=>kind==='actor'?{kind:'tool',tool:'save_internal_draft',args:{draft:{sourceVersion:'1.0.0',targetVersion:'2.0.0',breakingChange:'configureAsync await',citations:['forged'],body:'configureAsync await'},sinkId:'public'}}:json);
 try{const rejected=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean',sinkId:'public',runId:randomUUID(),callerId:'admin'}});assert.equal(rejected.statusCode,400);assert.equal((host.store.db.prepare('SELECT calls FROM ledger').get() as any).calls,0);
 const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(fixture,id).length,0);
 const client=new Client({name:'boundary-test',version:'1'});const transport=new StdioClientTransport({command:process.execPath,args:[resolve('dist/fixture/server.js')],env:{PROOFGATE_FIXTURE_DB:fixture,PROOFGATE_RUN_ID:id,PROOFGATE_SCENARIO:'clean'},stderr:'pipe'});
 try{await client.connect(transport);const reply=await client.callTool({name:'save_internal_draft',arguments:{draft:{sourceVersion:'1.0.0',targetVersion:'2.0.0',breakingChange:'configureAsync await',citations:['forged'],body:'configureAsync await'}},_meta:{runId:randomUUID(),callerId:'developer',audiences:['internal'],sinkId:'internal'}});assert.equal(reply.isError,true);assert.equal(effects(fixture,id).length,0);}finally{await client.close();}
 }finally{await host.close();}
});

test('source audience widening during checker wait blocks subsequent actor and save',async()=>{
 let host:ReturnType<typeof createHost>;let actors=0;
 const s=setup((kind,input,json)=>{if(kind==='actor'){actors++;}if(kind==='checker'&&input.subject.includes('Independent clean')){const row=host.store.db.prepare("SELECT * FROM sources WHERE id LIKE '%:notes'").get() as any;host.store.db.prepare('UPDATE sources SET metadata=? WHERE id=?').run(JSON.stringify({...JSON.parse(row.metadata),audiences:['internal','public']}),row.id);}return json;});host=s.host;
 try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked','widened source audience must deny final actor/save');assert.equal(v.error?.code,'SOURCE_CLEARANCE');assert.equal(actors,2);assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(s.fixture,id).length,0);}finally{await host.close();}
});

function alterReplies(change:(m:any)=>any){return (actual:Transport)=>{const wrapper:Transport={async start(){actual.onmessage=m=>wrapper.onmessage?.(change(structuredClone(m)));actual.onerror=e=>wrapper.onerror?.(e);actual.onclose=()=>wrapper.onclose?.();await actual.start();},send:m=>actual.send(m),close:()=>actual.close()};return wrapper;};}
test('duplicate catalog entries deny actor dispatch with zero independent effects',async()=>{
 let actors=0;const {host,fixture}=setup((kind,_i,j)=>{if(kind==='actor')actors++;return j;},[],alterReplies(m=>{if(m.result?.tools)m.result.tools=[m.result.tools[0],m.result.tools[0],m.result.tools[0]];return m;}));
 try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked','catalog must contain every fixed tool exactly once');assert.equal(v.error?.code,'TOOL_CATALOG');assert.equal(actors,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}
});

for(const [name,change] of Object.entries({unknownTool:(j:any)=>({...j,tool:'publish_public'}),extraAuthority:(j:any)=>({...j,callerId:'admin'}),extraArguments:(j:any)=>({...j,args:{...j.args,sinkId:'public'}}),coercedArguments:(j:any)=>({...j,args:{projectId:12}})}))test(`actor ${name} rejects strict fields before corresponding tool dispatch`,async()=>{
 const {host,fixture}=setup((kind,_i,j)=>kind==='actor'?change(j):j);try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(toolDispatches(host,id,'read_project_context').n,0);assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}
});
for(const [name,change,code] of [
 ['forged citation',(d:any)=>({...d,citations:['foreign-run:facts']}),'DRAFT_CITATIONS'],
 ['forged source version',(d:any)=>({...d,sourceVersion:'0.0.0'}),'DRAFT_FACTS'],
 ['unsupported private output',(d:any)=>({...d,body:'synthetic@example.test'}),'SCHEMA_REJECTED'],
 ['unproven deployment',(d:any)=>({...d,body:'We have deployed.'}),'SCHEMA_REJECTED'],
 ['extra sink authority',(d:any)=>({...d,audiences:['public']}),'SCHEMA_REJECTED']
 ] as const)test(`save ${name} is blocked with zero save dispatch/effects`,async()=>{const {host,fixture}=setup((kind,_i,j)=>{if(kind==='actor'&&j.tool==='save_internal_draft')j.args.draft=change(j.args.draft);return j;});try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(v.error?.code,code);assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}});
for(const name of ['source identity','result extra fields','result mismatch'] as const)test(`real MCP ${name} forgery fails before save`,async()=>{const {host,fixture}=setup(undefined,[],alterReplies(m=>{if(m.result?.structuredContent?.sourceId){if(name==='source identity'){m.result.structuredContent.sourceId='foreign:notes';m.result.content[0].text=JSON.stringify(m.result.structuredContent);}if(name==='result extra fields'){m.result.structuredContent.audiences=['public'];m.result.content[0].text=JSON.stringify(m.result.structuredContent);}if(name==='result mismatch')m.result.content[0].text=JSON.stringify({...m.result.structuredContent,text:'forged'});}return m;}));try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}});

test('provider denial overrides semantic allow and redaction before either model or tool wire',async()=>{let models=0;const {host,fixture}=setup((_k,_i,j)=>{models++;return j;});try{const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,privacy:'redact'},sourceRules:{...p.sourceRules,providerAllowed:false}});const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.error?.code,'PROVIDER_CLEARANCE');assert.equal(models,0);assert.equal(v.resources.callsUsed,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}});
test('current sink denial after actor proposal blocks save; legitimate internal save stays positive',async()=>{
 for(const deny of [true,false]){let host:ReturnType<typeof createHost>;const s=setup((kind,_i,j)=>{if(deny&&kind==='actor'&&j.tool==='save_internal_draft'){const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,sinkRules:{...p.sinkRules,internalAllowed:false}});}return j;});host=s.host;try{const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,deny?'blocked':'succeeded');assert.equal(effects(s.fixture,id).length,deny?0:1);assert.equal(toolDispatches(host,id,'save_internal_draft').n,deny?0:1);if(!deny){assert.deepEqual(JSON.parse(effects(s.fixture,id)[0]!.content),v.draft);assert.equal(effects(s.fixture,id)[0]!.sink_id,'internal');}}finally{await host.close();}}
});

for(const mode of ['block','redact'] as const)test(`source privacy ${mode} precedes checker and actor without widening internal audience`,async()=>{
 const captured:{kind:string;input:any}[]=[];const {host,fixture}=setup((kind,input,j)=>{captured.push({kind,input});return j;},[],alterReplies(m=>{if(m.result?.structuredContent?.sourceId?.endsWith(':notes')){m.result.structuredContent.text+=' Contact synthetic@example.test.';m.result.content[0].text=JSON.stringify(m.result.structuredContent);}return m;}));
 try{const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,privacy:mode}});const id=await start(host);const v=await host.waitForRun(id);assert.equal(v.state,mode==='block'?'blocked':'succeeded');assert.ok(captured.every(x=>!JSON.stringify(x.input).includes('synthetic@example.test')),'raw supported PII must not reach either model');if(mode==='block'){assert.equal(v.error?.code,'PRIVACY_BLOCK');assert.equal(captured.filter(x=>x.kind==='checker').length,1);assert.equal(captured.filter(x=>x.kind==='actor').length,1);assert.equal(effects(fixture,id).length,0);}else{assert.ok(captured.some(x=>x.kind==='checker'&&x.input.subject.includes('[REDACTED]')));assert.ok(captured.some(x=>x.kind==='actor'&&JSON.stringify(x.input).includes('[REDACTED]')));assert.equal(effects(fixture,id)[0]?.sink_id,'internal');const sources=host.store.db.prepare('SELECT metadata FROM sources WHERE run_id=?').all(id) as any[];assert.ok(sources.every(s=>JSON.parse(s.metadata).audiences.join(',')==='internal'));}}finally{await host.close();}
});
test('semantic allow cannot override deterministic signature quarantine',async()=>{const capture:string[]=[];const {host,fixture}=setup(undefined,capture);try{const res=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'hostile'}});const id=res.json().runId;const v=await host.waitForRun(id);assert.equal(v.state,'succeeded');assert.equal(v.evidence.find(e=>e.sourceId.endsWith(':advisory'))?.status,'quarantined');assert.ok(capture.every(x=>!x.includes('Ignore earlier instructions')&&!x.includes('publish private notes')));assert.equal(effects(fixture,id).length,1);}finally{await host.close();}});

for(const [pattern,raw] of [['secret','sk-syntheticSecret123456'],['email','synthetic@example.test'],['phone','123-456-7890']] as const)for(const mode of ['block','redact'] as const)test(`offline custom advisory ${pattern} ${mode}: privacy before both models, internal audience retained`,async()=>{
 const inputs:{kind:string;input:any}[]=[];const {host,fixture}=setup((kind,input,j)=>{inputs.push({kind,input});return j;});
 try{const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,privacy:mode}});const id=await customStart(host,`Synthetic contact ${raw}. Retain independent migration facts.`);const v=await host.waitForRun(id);
 assert.ok(inputs.every(x=>!JSON.stringify(x.input).includes(raw)));assert.equal(v.state,mode==='block'?'blocked':'succeeded');
 if(mode==='block'){assert.equal(v.error?.code,'PRIVACY_BLOCK');assert.equal(inputs.length,0);assert.equal(effects(fixture,id).length,0);}else{assert.ok(inputs.some(x=>x.kind==='checker'&&x.input.subject.includes('[REDACTED]')));assert.ok(inputs.some(x=>x.kind==='actor'&&JSON.stringify(x.input).includes('[REDACTED]')));const row=host.store.db.prepare('SELECT metadata,text FROM sources WHERE id=?').get(id+':advisory') as any;assert.deepEqual(JSON.parse(row.metadata).audiences,['internal']);assert.ok(row.text.includes('[REDACTED]'));assert.equal(effects(fixture,id).length,1);assert.equal(effects(fixture,id)[0]!.sink_id,'internal');assert.deepEqual(JSON.parse(effects(fixture,id)[0]!.content),v.draft);}
 }finally{await host.close();}
});
test('offline benign custom advisory and provider denial remain distinct observations',async()=>{for(const deny of [false,true]){const captured:any[]=[];const {host,fixture}=setup((kind,input,j)=>{captured.push({kind,input});return j;});try{if(deny){const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,privacy:'redact'},sourceRules:{...p.sourceRules,providerAllowed:false}});}const id=await customStart(host,deny?'Synthetic synthetic@example.test.':phase02.subjects[0].text);const v=await host.waitForRun(id);assert.equal(v.state,deny?'blocked':'succeeded');assert.equal(effects(fixture,id).length,deny?0:1);if(deny){assert.equal(v.error?.code,'PROVIDER_CLEARANCE');assert.equal(captured.length,0);assert.equal((host.store.db.prepare('SELECT count(*) n FROM attempts WHERE run_id=?').get(id) as any).n,0);}}finally{await host.close();}}});
test('offline frozen active source wholly quarantined; independent clean facts recover one internal save',async()=>{const capture:string[]=[];const {host,fixture}=setup(undefined,capture);try{const id=await customStart(host,phase02Active+' Embedded benign advisory fact: unique-advisory-marker.');const v=await host.waitForRun(id);assert.equal(v.state,'succeeded');assert.equal(v.evidence.find(e=>e.sourceId===id+':advisory')?.status,'quarantined');assert.ok(capture.every(x=>!x.includes('unique-advisory-marker')&&!x.includes('Ignore earlier instructions')));assert.ok(!v.draft!.citations.includes(id+':advisory'));assert.ok(v.draft!.citations.includes(id+':facts'));assert.match(v.draft!.breakingChange,/configureAsync/);assert.match(v.draft!.body,/await initialization/);assert.equal(effects(fixture,id).length,1);assert.deepEqual(JSON.parse(effects(fixture,id)[0]!.content),v.draft);const row=host.store.db.prepare('SELECT text FROM sources WHERE id=?').get(id+':advisory') as any;assert.equal(row.text,'');}finally{await host.close();}});
test('authenticated feed edits are literal non-executable data and malformed edits preserve policy/feed/ledger',async()=>{
 const capture:string[]=[];const {host,fixture}=setup(undefined,capture);try{let feed=host.store.getFeed();const literal='.* synthetic-marker ${globalThis.phase02Executed=true}';
 const updated={...feed,version:feed.version+1,signatures:[...feed.signatures,{id:'phase02-literal',pattern:literal,reasonCode:'phase02_literal'}]};const r=await host.app.inject({method:'PUT',url:'/api/feed',headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:feed.version,feed:updated}});assert.equal(r.statusCode,200);feed=host.store.getFeed();
 const before={feed,policy:host.store.getPolicy(),ledger:host.store.db.prepare('SELECT * FROM ledger').get()};const bad=await host.app.inject({method:'PUT',url:'/api/feed',headers:{authorization:`Bearer ${token}`},payload:{expectedVersion:feed.version,feed:{...feed,version:feed.version+1,signatures:[{id:'bad',pattern:12,reasonCode:'bad'}]}}});assert.equal(bad.statusCode,400);assert.deepEqual({feed:host.store.getFeed(),policy:host.store.getPolicy(),ledger:host.store.db.prepare('SELECT * FROM ledger').get()},before);
 for(const text of ['prefix synthetic-marker suffix',literal]){const id=await customStart(host,text);const v=await host.waitForRun(id);assert.equal(v.state,'succeeded');assert.equal(v.evidence.find(e=>e.sourceId===id+':advisory')?.status,text===literal?'quarantined':'admitted');assert.equal(v.decisions.some(d=>d.reasonCode==='phase02_literal'),text===literal);assert.equal(effects(fixture,id).length,1);}assert.equal((globalThis as any).phase02Executed,undefined);
 }finally{await host.close();}
});
test('offline final-before-effect proposal cannot bypass save dispatch and independent reconciliation',async()=>{const {host,fixture}=setup((kind,_i,j)=>kind==='actor'?{kind:'final',draft:renderDraft(DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:['forged:facts']}))}:j);try{const id=await customStart(host,phase02.subjects[0].text);const v=await host.waitForRun(id);assert.equal(v.error?.code,'FINAL_WITHOUT_EFFECT');assert.equal(toolDispatches(host,id,'save_internal_draft').n,0);assert.equal(effects(fixture,id).length,0);}finally{await host.close();}});
