import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHost,openStore } from '../../src/host.js';
import { openEffectStore } from '../../fixture/server.js';
import { MIGRATION, DraftPlanSchema } from '../../src/contracts.js';
import { type HostPorts,type ModelAdapter, type GenerationResult } from '../../src/model.js';
const token='offline-test-token-123456789';
export const draftPlan=(citations:string[])=>DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['review_call_sites','plan_await_initialization','review_internal_draft'],citations});
export function offlineModel(ports:HostPorts,capture:string[]=[]):ModelAdapter{return {mode:'offline',async generate(kind,input,_schema,deadline,runId){const id=ports.reserveAttempt({runId,kind,requestBytes:Buffer.byteLength(input),outputTokens:kind==='actor'?2048:256,deadline});ports.markDispatched(id);let json:unknown;if(kind==='checker'){const text=JSON.parse(input).subject as string;json={classification:text.includes('Ignore earlier')?'active':'benign',confidence:0.99,reasonCode:'offline_fixture'};}else{capture.push(input);const payload=JSON.parse(input);const evidence=payload.evidence as {sourceId:string;text:string}[];const notes=evidence.find(e=>e.sourceId.endsWith(':notes'));const facts=evidence.find(e=>e.sourceId.endsWith(':facts'));if(!notes)json={kind:'tool',tool:'read_project_context',args:{projectId:'proofgate-demo'}};else if(!facts)json={kind:'tool',tool:'read_dependency_evidence',args:{dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'}};else if(!facts.text.includes('configureAsync'))json={kind:'incomplete',reason:'Missing essential breaking change facts'};else {json={kind:'tool',tool:'save_internal_draft',args:{draft:draftPlan([notes.sourceId,facts.sourceId])}};}}
const result:GenerationResult={json,modelVersion:'offline-injected',responseId:'offline',usage:null};ports.settleAttempt(id,{usage:null,outcome:'known'});return result;}};}
function setup(capture:string[]=[]){const dir=mkdtempSync(join(tmpdir(),'proofgate-offline-'));const fixture=join(dir,'fixture.sqlite');return {fixture,host:createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:p=>offlineModel(p,capture)})};}
test('authenticated tracer implementation exists', async () => {
  let factory: unknown;
  try { const path = '../../src/host.js'; factory = (await import(path)).createHost; } catch { factory = undefined; }
  assert.equal(typeof factory, 'function', 'authenticated real MCP tracer must export createHost');
});
test('unauthorized and forged starts dispatch zero calls; all API routes authenticate',async()=>{const{host}=setup();try{for(const url of ['/api/runs','/api/policy','/api/feed','/api/runs/forged']){const res=await host.app.inject({method:url==='/api/runs'?'POST':'GET',url,payload:url==='/api/runs'?{scenario:'clean'}:undefined});assert.equal(res.statusCode,401);}const forged=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean',callerId:'admin'}});assert.equal(forged.statusCode,400);assert.equal((host.store.db.prepare('SELECT calls FROM ledger').get() as any).calls,0);}finally{await host.close();}});
for(const scenario of ['clean','hostile','missing'] as const)test(`actual stdio ${scenario} tracer reconciles independent fixture contents`,async()=>{const capture:string[]=[];const{host,fixture}=setup(capture);try{const start=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario}});assert.equal(start.statusCode,202);const {runId}=start.json();const v=await host.waitForRun(runId);assert.equal(v.state,scenario==='missing'?'incomplete':'succeeded',JSON.stringify({error:v.error,decisions:v.decisions}));const effects=openEffectStore(fixture);try{const rows=effects.read(runId);assert.equal(rows.length,scenario==='missing'?0:1);if(rows[0]){assert.deepEqual(JSON.parse(rows[0].content),v.draft);assert.equal(rows[0].sink_id,'internal');assert.match(v.draft!.breakingChange,/configureAsync/);assert.ok(v.draft!.citations.every(id=>v.evidence.some(e=>e.sourceId===id&&e.status==='admitted')));}}finally{effects.close();}if(scenario==='hostile'){assert.equal(v.evidence.find(e=>e.sourceId.endsWith(':advisory'))?.status,'quarantined');assert.ok(capture.every(input=>!input.includes('Ignore earlier instructions')&&!input.includes('publish private notes')));}assert.ok(v.resources.callsUsed>0);assert.equal(v.resources.usage,null);const status=await host.app.inject({url:`/api/runs/${runId}`,headers:{authorization:`Bearer ${token}`}});assert.equal(status.statusCode,200);assert.equal(status.json().state,v.state);}finally{await host.close();}});
test('SQLite ledger retains unknown dispatched work and new runs never replenish shared allowance',async()=>{const{host}=setup();try{const start=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});await host.waitForRun(start.json().runId);const before=(host.store.db.prepare('SELECT credits,calls FROM ledger').get() as any);const second=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'missing'}});await host.waitForRun(second.json().runId);const after=(host.store.db.prepare('SELECT credits,calls FROM ledger').get() as any);assert.ok(after.calls>before.calls);assert.ok(after.credits>before.credits);}finally{await host.close();}});
test('strict policy and feed activation preserve accepted snapshot on invalid/stale candidates',()=>{const store=openStore(':memory:');try{const p=store.getPolicy();assert.throws(()=>store.activatePolicy(0,{...p,version:2}));assert.throws(()=>store.activatePolicy(1,{...p,version:2,forged:true}));assert.deepEqual(store.getPolicy(),p);const next=store.activatePolicy(1,{...p,version:2,threshold:0.95});assert.equal(next.threshold,0.95);const feed=store.getFeed();assert.throws(()=>store.activateFeed(0,{...feed,version:2}));assert.deepEqual(store.getFeed(),feed);}finally{store.close();}});
test('uncertain checker fails closed before actor dispatch and independent effects remain zero',async()=>{const dir=mkdtempSync(join(tmpdir(),'proofgate-uncertain-'));let actors=0;const fixture=join(dir,'fixture.sqlite');const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:{mode:'offline',async generate(kind){if(kind==='actor')actors++;return{json:{classification:'uncertain',confidence:0.99,reasonCode:'uncertain'},modelVersion:'offline',responseId:'offline',usage:null};}}});try{const start=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});const id=start.json().runId;const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(v.error?.code,'CHECKER_UNCERTAIN');assert.equal(actors,0);const effect=openEffectStore(fixture);try{assert.equal(effect.read(id).length,0);}finally{effect.close();}}finally{await host.close();}});
test('unknown dispatched attempt remains charged in durable SQLite; only proven unsent releases',async()=>{const{host}=setup();try{const start=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});const id=start.json().runId;await host.waitForRun(id);const before=host.view(id).resources;const attempt=host.ports.reserveAttempt({runId:id,kind:'actor',requestBytes:100,outputTokens:10,deadline:Date.now()+10000});host.ports.markDispatched(attempt);host.ports.settleAttempt(attempt,{usage:null,outcome:'unknown'});const after=host.view(id).resources;assert.equal(after.callsUsed,before.callsUsed+1);assert.equal(after.creditsReserved,before.creditsReserved+100+262144+160);assert.equal((host.store.db.prepare('SELECT outcome FROM attempts WHERE id=?').get(attempt) as any).outcome,'unknown');const unsent=host.ports.reserveAttempt({runId:id,kind:'actor',requestBytes:10,outputTokens:1,deadline:Date.now()+10000});host.ports.settleAttempt(unsent,{usage:null,outcome:'unsent'});assert.equal(host.view(id).resources.creditsReserved,after.creditsReserved);assert.equal(host.view(id).resources.callsUsed,after.callsUsed);}finally{await host.close();}});
test('redaction mode cannot authorize arbitrary private actor output in the constrained draft',async()=>{const dir=mkdtempSync(join(tmpdir(),'proofgate-redact-'));const fixture=join(dir,'fixture.sqlite');const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:fixture,modelAdapter:p=>{const base=offlineModel(p);return{mode:'offline',async generate(...args){const r=await base.generate(...args);const proposal=r.json as any;if(proposal.kind==='tool'&&proposal.tool==='save_internal_draft')proposal.args.draft.body='Contact synthetic@example.test.';return r;}};}});try{const p=host.store.getPolicy();host.store.activatePolicy(p.version,{...p,version:p.version+1,controls:{...p.controls,privacy:'redact'}});const start=await host.app.inject({method:'POST',url:'/api/runs',headers:{authorization:`Bearer ${token}`},payload:{scenario:'clean'}});const id=start.json().runId;const v=await host.waitForRun(id);assert.equal(v.state,'blocked');assert.equal(v.error?.code,'SCHEMA_REJECTED');const effects=openEffectStore(fixture);try{assert.equal(effects.read(id).length,0);assert.equal(v.decisions.filter(d=>d.stage==='dispatch'&&d.reasonCode==='save_internal_draft').length,0);}finally{effects.close();}}finally{await host.close();}});
