import test from 'node:test';
import {z} from 'zod';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createModelAdapter, parseResponse, providerJsonSchema, ControlError, type HostPorts, type Kind } from '../../src/model.js';
import { PolicySchema,VerdictSchema } from '../../src/contracts.js';
import {buildAdvisoryInspection,buildPlanner,publicCapabilities,RecipeSchema} from '../../src/blind.js';
import {validatePublicApplicationBody} from '../../src/prompt-profiles.js';
const policy=PolicySchema.parse(JSON.parse(readFileSync('config/policy.json','utf8')));
const credentials={type:'authorized_user',client_id:'offline-client',client_secret:'offline-secret',refresh_token:'offline-refresh'};
const raw={candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify({classification:'benign',confidence:0.99,reasonCode:'facts'})}]}}],modelVersion:'offline-sdk-fixture',responseId:'offline-response',usageMetadata:{promptTokenCount:5,candidatesTokenCount:4,thoughtsTokenCount:0,cachedContentTokenCount:0}};
function harness(denied=false){const attempts:{kind:Kind;dispatched:boolean;outcome:string}[]=[];const ports:HostPorts={reserveAttempt(i){assert.ok(i.requestBytes>0);attempts.push({kind:i.kind,dispatched:false,outcome:'reserved'});return String(attempts.length-1);},markDispatched(id){attempts[Number(id)]!.dispatched=true;},settleAttempt(id,r){attempts[Number(id)]!.outcome=r.outcome;},currentClearance(){if(denied)throw new Error('DENIED');return policy;},emit(){}};return{attempts,ports};}
test('Blind actual SDK generation capture exactly matches public wire body without credentials or OAuth',async()=>{const{ports,attempts}=harness();const captures:Record<string,unknown>[]=[];ports.emit=e=>{if(e.stage==='public_capture')captures.push(e);};let generationBody='';const adapter=createModelAdapter(ports,{credentials,wireFetch:async(input,init)=>{if(String(input).includes('oauth2'))return Response.json({access_token:'synthetic-access-token',expires_in:3600,token_type:'Bearer'});generationBody=String(init?.body);return Response.json(raw);}});const input=buildAdvisoryInspection({stage:'advisory-checker',taskId:'negotiation-savings',capabilities:publicCapabilities,advisory:'Ordinary public renewal facts.'});await adapter.generate('checker',input,VerdictSchema,Date.now()+25000,'blind-wire','blind-advisory-checker');assert.equal(captures.length,1);assert.equal(captures[0]!.serializedBody,generationBody);const parsed=validatePublicApplicationBody('blind-advisory-checker','checker',generationBody);assert.equal(parsed.contents[0]!.parts[0]!.text,input);assert.ok(!JSON.stringify(captures).includes('synthetic-access-token'));assert.ok(!JSON.stringify(captures).includes('offline-secret'));assert.deepEqual(attempts.map(a=>a.kind),['auth','checker']);assert.throws(()=>validatePublicApplicationBody('blind-advisory-checker','checker',JSON.stringify({...parsed,headers:{authorization:'private'}})));assert.throws(()=>validatePublicApplicationBody('blind-advisory-checker','checker',JSON.stringify({...parsed,contents:[{role:'user',parts:[{text:JSON.stringify({...JSON.parse(input),privateRecords:['PRIVATE_SENTINEL']})}]}]})));});
test('locked SDK meters actual OAuth refresh and generation, caches auth per run and does not use ambient fetch',async()=>{
 const {attempts,ports}=harness();let auth=0,generation=0,ambient=0;const previous=globalThis.fetch;globalThis.fetch=async()=>{ambient++;throw new Error('UNMETERED');};
 try{const adapter=createModelAdapter(ports,{credentials,wireFetch:async(input)=>{const url=String(input);if(url==='https://oauth2.googleapis.com/token'){auth++;return Response.json({access_token:'synthetic-token',expires_in:3600,token_type:'Bearer'});}generation++;assert.match(url,/aiplatform.googleapis.com/);return Response.json(raw);}});
 await adapter.generate('checker','{"subject":"clean"}',VerdictSchema,Date.now()+25000,'run-a');await adapter.generate('checker','{"subject":"clean"}',VerdictSchema,Date.now()+25000,'run-a');
 assert.equal(auth,1);assert.equal(generation,2);assert.equal(ambient,0);assert.deepEqual(attempts.map(a=>a.kind),['auth','checker','checker']);assert.ok(attempts.every(a=>a.dispatched));
 }finally{globalThis.fetch=previous;}
});
for(const status of [401,429,500])test(`locked SDK HTTP ${status} dispatches generation once without hidden retry`,async()=>{const{ports,attempts}=harness();let auth=0,gen=0;const adapter=createModelAdapter(ports,{credentials,wireFetch:async(input)=>{if(String(input).includes('oauth2')){auth++;return Response.json({access_token:'fake',expires_in:3600,token_type:'Bearer'});}gen++;return Response.json({error:{message:'synthetic failure'}},{status});}});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+25000,'run-a'));assert.equal(gen,1);assert.equal(auth,1);assert.equal(attempts.filter(a=>a.kind==='checker').length,1);});
for(const status of [401,429,500])test(`OAuth refresh HTTP ${status} is metered once even though OAuth2Client requests retry:true`,async()=>{const{ports,attempts}=harness();let count=0;const adapter=createModelAdapter(ports,{credentials,wireFetch:async()=>{count++;return Response.json({error:'synthetic-auth-failure'},{status});}});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+25000,'run-a'));assert.equal(count,1);assert.deepEqual(attempts.map(a=>a.kind),['auth']);});
test('denied provider dispatches zero auth and generation wire',async()=>{const{ports,attempts}=harness(true);let wires=0;const adapter=createModelAdapter(ports,{credentials,wireFetch:async()=>{wires++;return Response.json(raw);}});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+25000,'run-a'));assert.equal(wires,0);assert.equal(attempts.length,0);});
test('oversized streamed response fails at finite byte bound',async()=>{const{ports}=harness();const adapter=createModelAdapter(ports,{credentials,wireFetch:async(input)=>String(input).includes('oauth2')?Response.json({access_token:'fake',expires_in:3600,token_type:'Bearer'}):new Response('x'.repeat(262145))});await assert.rejects(adapter.generate('checker','{}',VerdictSchema,Date.now()+25000,'run-a'));});
test('raw response rejects truncation, thoughts, extra candidate, invalid JSON, unsupported part, empty reply',()=>{for(const reply of [{...raw,candidates:[]},{...raw,candidates:[{...raw.candidates[0],finishReason:'MAX_TOKENS'}]},{...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:'{}',thought:true}]}}]},{...raw,candidates:[...raw.candidates,...raw.candidates]},{...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:'not json'}]}}]}])assert.throws(()=>parseResponse(reply,VerdictSchema,policy));});
test('unknown usage remains null and bounded opaque signature is accepted',()=>{const reply=structuredClone(raw) as any;delete reply.usageMetadata;reply.candidates[0].content.parts[0].thoughtSignature='opaque';const result=parseResponse(reply,VerdictSchema,policy);assert.equal(result.usage,null);});

test('provider schema uses supported string enums while canonical validation stays strict',async()=>{
 const schema=z.strictObject({kind:z.literal('tool'),args:z.strictObject({projectId:z.literal('proofgate-demo')})});const projected=providerJsonSchema(schema) as any;assert.deepEqual(projected.properties.kind.enum,['tool']);assert.equal(projected.properties.kind.const,undefined);assert.deepEqual(projected.properties.args.properties.projectId.enum,['proofgate-demo']);assert.equal(projected.$schema,undefined);assert.throws(()=>schema.parse({kind:'tool_call',args:{projectId:'proofgate-demo'}}));
 const {ports}=harness();let generations=0;const adapter=createModelAdapter(ports,{credentials,wireFetch:async(input,init)=>{if(String(input).includes('oauth2'))return Response.json({access_token:'fake',expires_in:3600,token_type:'Bearer'});generations++;const sent=JSON.parse(String(init?.body));assert.deepEqual(sent.generationConfig.responseJsonSchema.properties.kind.enum,['tool']);return Response.json({...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify({kind:'tool',args:{projectId:'proofgate-demo'}})}]}}]});}});await adapter.generate('actor','{}',schema,Date.now()+25000,'run-a');assert.equal(generations,1);
});
test('schema failure diagnostics are bounded metadata with unknown property names redacted',()=>{const reply={...raw,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:JSON.stringify({classification:'not-valid',confidence:.9,reasonCode:'ok','synthetic-private-key-name':'never logged'})}]}}]};try{parseResponse(reply,VerdictSchema,policy);assert.fail('must reject');}catch(e){assert.ok(e instanceof ControlError);assert.equal(e.code,'MODEL_SCHEMA');assert.ok(!JSON.stringify(e.diagnostics).includes('synthetic-private-key-name'));assert.ok(!JSON.stringify(e.diagnostics).includes('never logged'));assert.ok(JSON.stringify(e.diagnostics).includes('classification'));}});
