import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHost } from '../../src/host.js';
import {renderDraft, DraftPlanSchema, MIGRATION, type RunView} from '../../src/contracts.js';
const browser=await import(pathToFileURL(resolve('public/app.js')).href);
const {projectRun,resourceLabels,submitPolicy,submitFeed,createRunController,renderRun,renderEmpty}=browser;
function view(overrides:Partial<RunView>={}):RunView {return {runId:'owned',state:'succeeded',mode:'live',synthetic:true,policyVersion:2,feedVersion:1,evidence:[],decisions:[],draft:renderDraft(DraftPlanSchema.parse({sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:MIGRATION,preparationStatus:'draft_only',steps:['plan_await_initialization'],citations:['owned:facts']})),effects:{savedCount:1,reconciled:true},resources:{epochId:'same-epoch',creditsReserved:50,creditsLimit:100,callsUsed:2,callsLimit:4,usage:null,estimatedCost:null},error:null,...overrides};}
test('unreconciled succeeded response never announces success',()=>{for(const effects of [{savedCount:0,reconciled:false},{savedCount:1,reconciled:false},{savedCount:2,reconciled:true}]){const p=projectRun(view({effects}));assert.equal(p.verified,false);assert.equal(p.state,'incomplete');assert.doesNotMatch(p.title,/verified save/i);}assert.equal(projectRun(view({draft:null})).verified,false);});
test('fresh audit mismatch or unavailable independent recorder prevents renewed verified-save claim',()=>{for(const observation of [{status:'unavailable',count:null,hostAcknowledged:true,matchesCanonicalDraft:null,effects:[]},{status:'observed',count:1,hostAcknowledged:true,matchesCanonicalDraft:false,effects:[]},{status:'observed',count:1,hostAcknowledged:false,matchesCanonicalDraft:true,effects:[]}])assert.equal(projectRun(view({audit:{independentEffects:observation} as any})).verified,false);});
test('blocked incomplete empty running and replay remain distinct from verified live or offline work',()=>{for(const state of ['blocked','incomplete','empty','running'] as const){const p=projectRun(view({state}));assert.equal(p.state,state);assert.equal(p.verified,false);}const replay=projectRun(view({mode:'replay'}));assert.equal(replay.verified,false);assert.match(replay.mode,/Replay/);assert.match(replay.effect,/NO LIVE SAVE CLAIM/);assert.equal(projectRun(view()).verified,true);assert.match(projectRun(view({mode:'offline'})).mode,/Offline injected/);});
test('unknown tokens and unpriced tariff remain unknown while known zero is zero',()=>{const unknown=resourceLabels(view().resources);assert.match(unknown.tokens,/Unknown/);assert.match(unknown.cost,/unknown \/ unpriced/);assert.deepEqual(unknown.categories.map((row:string[])=>row[1]),['Unknown','Unknown','Unknown','Unknown']);const known=resourceLabels({...view().resources,usage:{prompt:0,output:0,thought:0,cache:0},estimatedCost:0});assert.match(known.tokens,/0 prompt/);assert.match(known.cost,/0 \(policy tariff/);assert.match(known.credits,/admission credits/);});
test('policy and feed submissions use PUT and the captured expectedVersion without mutating snapshots',async()=>{const requests:any[]=[];const send=async(path:string,options:any)=>{requests.push({path,...options});return options.body;};const policy={version:8,controls:{semantic:true}},feed={version:3,signatures:[]};await submitPolicy(7,policy,send);await submitFeed(2,feed,send);assert.deepEqual(requests,[{path:'/api/policy',method:'PUT',body:{expectedVersion:7,policy}},{path:'/api/feed',method:'PUT',body:{expectedVersion:2,feed}}]);assert.equal(policy.version,8);assert.equal(feed.version,3);});
test('poller rejects mismatched run IDs before rendering',async()=>{let renders=0;let error='';const c=createRunController({send:async(path:string)=>path==='/api/runs'?{runId:'owned'}:view({runId:'foreign'}),onView:()=>renders++,onError:(e:Error)=>error=e.message});await c.start('clean');assert.equal(renders,0);assert.equal(error,'RUN_ID_MISMATCH');});
test('selection cancels stale responses and at most one status request is outstanding',async()=>{const rendered:string[]=[];let resolveOld:(v:any)=>void=()=>{};let pending=0,maxPending=0;const send=async(path:string,options:any)=>{if(path==='/api/runs')return {runId:options.body.scenario};if(path.endsWith('clean')){pending++;maxPending=Math.max(maxPending,pending);return await new Promise(resolve=>{resolveOld=v=>{pending--;resolve(v);};options.signal.addEventListener('abort',()=>{pending--;resolve(view({runId:'clean'}));},{once:true});});}pending++;maxPending=Math.max(maxPending,pending);pending--;return view({runId:'hostile'});};const c=createRunController({send,onView:(v:RunView)=>rendered.push(v.runId)});const first=c.start('clean');await new Promise(resolve=>setImmediate(resolve));const second=c.start('hostile');await Promise.all([first,second]);assert.deepEqual(rendered,['hostile']);assert.equal(maxPending,1);void resolveOld;});
test('polling runs sequentially and observation errors do not automatically retry',async()=>{let requests=0;let rendered=0;let finish=0;const c=createRunController({send:async(path:string)=>{requests++;return path==='/api/runs'?{runId:'owned'}:view({state:requests===2?'running':'succeeded'});},wait:async()=>{},onView:()=>rendered++,onFinish:()=>finish++});await c.start('clean');assert.equal(requests,3);assert.equal(rendered,2);assert.equal(finish,1);let errors=0;const failing=createRunController({send:async()=>{errors++;throw new Error('UNAUTHORIZED');},onView:()=>assert.fail('no render')});await failing.start('clean');assert.equal(errors,1);});
class TextNode {textContent='';className='';value='all';max=0;children:TextNode[]=[];constructor(public tag='div'){}append(...children:TextNode[]){this.children.push(...children);}replaceChildren(...children:TextNode[]){this.children=children;}set innerHTML(_value:string){assert.fail('untrusted data must never use innerHTML');}}
test('new selection clears prior verified identity evidence trail and result',()=>{const nodes:Record<string,TextNode>={};const doc={getElementById:(id:string)=>nodes[id]??=(new TextNode()),createElement:(tag:string)=>new TextNode(tag)};renderRun(view(),doc);assert.match(nodes['effect-badge']!.textContent,/1 VERIFIED/);renderEmpty(doc);assert.equal(nodes['effect-badge']!.textContent,'NO VERIFIED SAVE');assert.equal(nodes['gate-status']!.textContent,'Your policy is the boundary');assert.equal(nodes['resources']!.children.length,0);assert.equal(nodes['decisions']!.children.length,0);assert.equal(nodes['policy-identity']!.textContent,'No selected run');});
test('actual renderer keeps hostile markup as text and exposes breaking warning and citations',()=>{const nodes:Record<string,TextNode>={};const doc={getElementById:(id:string)=>nodes[id]??=(new TextNode()),createElement:(tag:string)=>new TextNode(tag)};const hostile='<img src=x onerror=globalThis.pwned=true>';renderRun(view({evidence:[{sourceId:'owned:advisory',status:'quarantined',summary:hostile}],draft:{...view().draft!,body:hostile}}),doc);const texts=(node:TextNode):string=>node.textContent+' '+node.children.map(texts).join(' ');assert.ok(texts(nodes.evidence!).includes(hostile));assert.ok(texts(nodes.draft!).includes(hostile));assert.match(texts(nodes.draft!),/BREAKING CHANGE/);assert.match(texts(nodes.draft!),/owned:facts/);assert.match(nodes['effect-badge']!.textContent,/VERIFIED SAVE/);renderRun(view({state:'blocked'}),doc);assert.doesNotMatch(texts(nodes.draft!),/INTERNAL RELEASE DRAFT/);});
test('actual host serves module stylesheet restrictive CSP and preserves accepted policy and epoch on invalid edit',async()=>{const dir=mkdtempSync(join(tmpdir(),'proofgate-workbench-'));const token='workbench-offline-test-token';const host=createHost({token,hostDbPath:join(dir,'host.sqlite'),fixtureDbPath:join(dir,'fixture.sqlite')});try{const html=await host.app.inject('/');assert.equal(html.statusCode,200);assert.match(html.body,/type="module"/);assert.match(html.body,/href="\/styles.css"/);assert.doesNotMatch(html.body,/<style>|onclick=|<script[^>]*>[^<]+/);assert.match(html.headers['content-security-policy'] as string,/style-src 'self'/);assert.doesNotMatch(html.headers['content-security-policy'] as string,/unsafe-inline|unsafe-eval/);for(const [url,type] of [['/app.js','javascript'],['/styles.css','text/css']]){const asset=await host.app.inject(url!);assert.equal(asset.statusCode,200);assert.match(asset.headers['content-type'] as string,new RegExp(type!));assert.ok(asset.body.length>1000);}const headers={authorization:'Bearer '+token};const before=(await host.app.inject({url:'/api/policy',headers})).json();const ledger=host.store.db.prepare('SELECT * FROM ledger').get();const invalid={...before,version:before.version+1,models:{...before.models,allowlist:[]}};const rejected=await host.app.inject({method:'PUT',url:'/api/policy',headers,payload:{expectedVersion:before.version,policy:invalid}});assert.equal(rejected.statusCode,400);assert.deepEqual((await host.app.inject({url:'/api/policy',headers})).json(),before);assert.deepEqual(host.store.db.prepare('SELECT * FROM ledger').get(),ledger);const stale=await host.app.inject({method:'PUT',url:'/api/feed',headers,payload:{expectedVersion:0,feed:{version:1,signatures:[]}}});assert.equal(stale.statusCode,409);}finally{await host.close();}});
test('browser uses no persistence executable evidence or provider credentials',()=>{const source=readFileSync('public/app.js','utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|\.innerHTML|eval\(|new Function|document\.cookie/);});
class InteractiveNode extends TextNode {disabled=false;hidden=false;checked=false;onclick:any;onchange:any;oninput:any;onsubmit:any;href='';download='';clicked=false;removed=false;attributes:Record<string,string>={};click(){this.clicked=true;return this.onclick?.();}remove(){this.removed=true;}setAttribute(k:string,v:string){this.attributes[k]=v;}focus(){}scrollIntoView(){}}
function interactiveDocument(){const nodes:Record<string,InteractiveNode>={};for(const m of readFileSync('public/index.html','utf8').matchAll(/id="([^"]+)"/g))nodes[m[1]!]=new InteractiveNode();nodes.scenario!.value='clean';nodes.advisory!.value='';const created:InteractiveNode[]=[];const doc={body:new InteractiveNode('body'),getElementById:(id:string)=>nodes[id]??=new InteractiveNode(),createElement:(tag:string)=>{const n=new InteractiveNode(tag);created.push(n);return n;}};return {doc,nodes,created};}
const policyFixture=()=>JSON.parse(readFileSync('config/policy.json','utf8'));
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('executed setup permits versioned policy and feed mutation during observation without duplicate runs; stop invalidates late success',async t=>{
 const {doc,nodes}=interactiveDocument();let policy=policyFixture(),feed={version:1,signatures:[]};const calls:any[]=[];let late:(v:any)=>void=()=>{};
 const send=async(path:string,o:any={})=>{calls.push({path,...o});if(path==='/api/policy'){if(o.method==='PUT'){assert.equal(o.body.expectedVersion,policy.version);policy=o.body.policy;}return policy;}if(path==='/api/feed'){if(o.method==='PUT'){assert.equal(o.body.expectedVersion,feed.version);feed=o.body.feed;policy={...policy,version:policy.version+1,feedVersion:feed.version};}return feed;}if(path==='/api/runs')return {runId:'owned'};return new Promise(resolve=>{late=resolve;});};
 assert.equal(typeof browser.setup,'function');browser.setup(doc,{send,listen:()=>{}});t.after(()=>nodes.stop!.onclick());nodes.token!.value='local-test-token';await nodes.connect!.onclick();const running=nodes.start!.onclick();await settle();assert.equal(nodes.start!.disabled,true);assert.equal(nodes['policy-fields']!.disabled,false);nodes.threshold!.value='.9';await nodes['policy-form']!.onsubmit({preventDefault(){}});assert.equal(policy.version,2);assert.equal(nodes.start!.disabled,true);assert.equal(nodes['save-feed']!.disabled,false);await nodes['save-feed']!.onclick();assert.equal(feed.version,2);assert.equal(policy.feedVersion,2);assert.equal(nodes.start!.disabled,true);await nodes.start!.onclick();assert.equal(calls.filter(c=>c.path==='/api/runs').length,1);
 nodes.stop!.onclick();late(view());await running;assert.match(nodes.state!.textContent,/Observation stopped/);assert.match(nodes['gate-status']!.textContent,/Observation stopped/);assert.match(nodes['effect-badge']!.textContent,/NO NEW VERIFIED/);assert.doesNotMatch(nodes.state!.textContent,/Useful work|cancelled/i);assert.equal(nodes['inspect-id']!.value,'owned');assert.match(nodes.mode!.textContent,/retained/i);
});
test('executed form prevents oversized UTF8 advisory before POST and reports capacity as zero admitted work',async()=>{
 const {doc,nodes}=interactiveDocument();const requests:any[]=[];const send=async(path:string,o:any={})=>{requests.push({path,...o});if(path==='/api/policy')return policyFixture();if(path==='/api/feed')return {version:1,signatures:[]};throw new Error('RUN_CAPACITY');};assert.equal(typeof browser.setup,'function');browser.setup(doc,{send,listen:()=>{}});nodes.token!.value='local-test-token';await nodes.connect!.onclick();
 for(const text of ['a'.repeat(4097),'é'.repeat(2048)+'a','😀'.repeat(1024)+'a']){nodes.advisory!.value=text;nodes.advisory!.oninput();await nodes.start!.onclick();assert.match(nodes['advisory-feedback']!.textContent,/4097/);assert.equal(requests.filter(c=>c.method==='POST').length,0);}
 for(const text of ['a'.repeat(4096),'é'.repeat(2048),'😀'.repeat(1024)]){nodes.advisory!.value=text;nodes.advisory!.oninput();assert.equal(nodes.start!.disabled,false);await nodes.start!.onclick();assert.match(nodes.state!.textContent,/capacity/i);assert.match(nodes['gate-reason']!.textContent,/No run or work was admitted/);assert.doesNotMatch(nodes['gate-reason']!.textContent,/may.*charged/i);assert.equal(nodes['effect-badge']!.textContent,'NO WORK ADMITTED');}
 assert.equal(requests.filter(c=>c.method==='POST').length,3);
});
test('executed retained inspection and download bind identities and use only GET with revoked bounded Blob URL',async()=>{
 const {doc,nodes,created}=interactiveDocument();const id='b4d82c90-b2bc-44a9-9e8e-0d21a1cce164';const calls:any[]=[];let revoked='';let blob:Blob|null=null;const urlApi={createObjectURL:(b:Blob)=>{blob=b;return 'blob:isolated';},revokeObjectURL:(u:string)=>{revoked=u;}};const send=async(path:string,o:any={})=>{calls.push({path,...o});if(path==='/api/policy')return policyFixture();if(path==='/api/feed')return {version:1,signatures:[]};return path.endsWith('/export')?{schemaVersion:'proofgate-evidence-1',run:{runId:id}}:view({runId:id});};assert.equal(typeof browser.setup,'function');browser.setup(doc,{send,listen:()=>{},urlApi});nodes.token!.value='local-test-token';await nodes.connect!.onclick();nodes['inspect-id']!.value=id;await nodes.inspect!.onclick();assert.match(nodes.state!.textContent,/Retained observation/);assert.match(nodes['effect-badge']!.textContent,/RETAINED/);await nodes.export!.onclick();assert.equal(revoked,'blob:isolated');assert.ok(blob);const link=created.find(n=>n.tag==='a')!;assert.equal(link.download,`proofgate-${id}.json`);assert.equal(link.clicked,true);assert.equal(link.removed,true);assert.ok(calls.every(c=>!c.method||c.method==='GET'));assert.match(nodes['export-feedback']!.textContent,new RegExp(id));
});
test('download keeps its Blob and anchor alive until the browser has consumed the click, then releases both',async()=>{
 const {doc,created}=interactiveDocument();const id='b4d82c90-b2bc-44a9-9e8e-0d21a1cce164';let release!:()=>void;let revoked=false;
 const pending=browser.downloadEvidence(id,{doc,send:async()=>({schemaVersion:'proofgate-evidence-1',run:{runId:id}}),urlApi:{createObjectURL:()=> 'blob:lifetime',revokeObjectURL:()=>{revoked=true;}},releaseDelay:()=>new Promise<void>(resolve=>{release=resolve;})});
 await settle();const link=created.find(n=>n.tag==='a')!;assert.equal(link.clicked,true);assert.equal(link.removed,false);assert.equal(revoked,false);
 release();await pending;assert.equal(link.removed,true);assert.equal(revoked,true);
});
