import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync,mkdirSync,writeFileSync,renameSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createConnection} from 'node:net';
import {createHost} from '../../src/host.js';
import {createModelAdapter,ControlError} from '../../src/model.js';
import {openBlindEffectStore} from '../../fixture/blind-store.js';
const {INTENT_PATHS,ApprovalSchema,assertRoot,readOnlySnapshot,readFrozen,frozenHashes,preregistration,objectHash,sha,construction,assertIntentionRecipe,assertIntentionGeneration,validateIntentProof}=await import(pathToFileURL(resolve('scripts/check-blind-intent-proof.mjs')).href);
const claims=(rows:any[])=>rows.map(r=>({identityHash:sha(r.id),targetCents:r.targetCents,savingCents:r.savingCents,atRisk:r.atRisk}));
async function stoppedListener(){await new Promise<void>((ok,fail)=>{const socket=createConnection({host:'127.0.0.1',port:3100});socket.setTimeout(1000);socket.once('connect',()=>{socket.destroy();fail(new Error('STOP_OWNED_LISTENER_3100_FIRST'));});socket.once('error',(e:any)=>{socket.destroy();e.code==='ECONNREFUSED'?ok():fail(new Error('LISTENER_UNVERIFIED'));});socket.once('timeout',()=>{socket.destroy();fail(new Error('LISTENER_UNVERIFIED'));});});}
test('root-only fresh public intention; frozen expectation precedes any actual response',async()=>{
 assertRoot();await stoppedListener();assert.ok(existsSync(INTENT_PATHS.approval),'INTENT_APPROVAL_REQUIRED');const approval=ApprovalSchema.parse(JSON.parse(readFileSync(INTENT_PATHS.approval,'utf8'))),current=readOnlySnapshot();assert.deepEqual({...current,createdAt:approval.createdAt},approval,'INTENT_APPROVAL_STALE');
 const f=readFrozen(),token=readFileSync(INTENT_PATHS.token,'utf8').trim();assert.ok(token.length>=16,'TOKEN_REQUIRED');
 const result:any={schemaVersion:'proofgate-blind-intent-proof-1',generatedAt:new Date().toISOString(),mode:'actual_hosted',status:'partial',error:null,approval,hashes:frozenHashes(),preregistered:preregistration(f),originalProofHashAfter:approval.originalProofHash,dispatchBodies:[],modelObservations:[],composition:null,contrast:[],rebind:null,ledgerAfter:approval.ledger,newAttempts:[],retainedAttemptsHashAfter:approval.retainedAttemptsHash,unknownsAfter:approval.unknowns};
 let host:ReturnType<typeof createHost>|undefined,stopped=false;
 const ledger=()=>({...host!.store.db.prepare('SELECT * FROM ledger').get()}) as {id:string;calls:number;credits:number};
 const attempts=()=>host!.store.db.prepare('SELECT * FROM attempts ORDER BY id').all() as any[];
 const preserve=()=>{if(host){const rows=attempts();result.ledgerAfter=ledger();result.newAttempts=rows.filter(x=>!approval.retainedAttemptIds.includes(x.id));result.retainedAttemptsHashAfter=objectHash(rows.filter(x=>approval.retainedAttemptIds.includes(x.id)));result.unknownsAfter=rows.filter(x=>x.dispatched&&x.outcome==='unknown').length;}result.originalProofHashAfter=sha(readFileSync(INTENT_PATHS.original));result.generatedAt=new Date().toISOString();mkdirSync(dirname(INTENT_PATHS.result),{recursive:true});const temporary=INTENT_PATHS.result+'.partial';writeFileSync(temporary,JSON.stringify(result,null,2)+'\n',{mode:0o600});renameSync(temporary,INTENT_PATHS.result);};
 const guard=(prospective=0,credit=0)=>{if(stopped)throw new ControlError('INTENT_STOPPED');const l=ledger();if(l.id!==approval.ledger.id||l.calls-approval.ledger.calls+prospective>12||l.credits-approval.ledger.credits+credit>4325376)throw new ControlError('INTENT_ALLOCATION');if(objectHash(attempts().filter(x=>approval.retainedAttemptIds.includes(x.id)))!==approval.retainedAttemptsHash)throw new ControlError('RETAINED_WORK_CHANGED');};
 // No forced recipe, no injected wire, and no custom credentials in this runner.
 // Guards wrap the same host-owned ports used by OAuth/model and registered MCP.
 try{
  preserve();host=createHost({token,hostDbPath:INTENT_PATHS.host,fixtureDbPath:INTENT_PATHS.fixture,modelAdapter:ports=>{
   const reserve=ports.reserveAttempt,dispatch=ports.markDispatched,settle=ports.settleAttempt,emit=ports.emit;
   ports.reserveAttempt=input=>{const p=ports.currentClearance(input.runId,input.kind);guard(1,input.requestBytes+p.limits.responseBytes+16*input.outputTokens);try{const id=reserve(input);preserve();return id;}catch(e){stopped=true;preserve();throw e;}};
   ports.markDispatched=id=>{guard();dispatch(id);preserve();};
   ports.settleAttempt=(id,outcome)=>{settle(id,outcome);if(outcome.outcome!=='known')stopped=true;preserve();};
   ports.emit=e=>{emit(e);if(e.stage==='public_capture'&&typeof e.serializedBody==='string'){result.dispatchBodies.push(e.serializedBody);preserve();}};
   const adapter=createModelAdapter(ports);
   return {mode:adapter.mode,async generate(...args){const generated=await adapter.generate(...args),profileId=args[5];result.modelObservations.push({profileId,output:generated.json,returnedModel:generated.modelVersion});preserve();try{assertIntentionGeneration(profileId,generated.json,approval.policy.threshold);}catch{stopped=true;preserve();throw new ControlError(profileId==='blind-planner'?'INTENTION_COMPOSITION_MISMATCH':'INTENTION_SEMANTIC_REJECTED');}return generated;}};
  }});assert.deepEqual(ledger(),approval.ledger);guard();
  const headers={authorization:'Bearer '+token},request=async(url:string,method:'GET'|'POST'|'PUT'='GET',payload?:any)=>host!.app.inject({url,method,headers,...(payload===undefined?{}:{payload})});
  const get=async(url:string)=>{const r=await request(url);assert.equal(r.statusCode,200,r.body);return r.json();};
  const putPrivate=async(data:any)=>{let w=await get('/api/blind/workspace');let r=await request('/api/blind/private','PUT',{expectedVersion:w.version,records:data.records});assert.equal(r.statusCode,200,r.body);preserve();w=await get('/api/blind/workspace');r=await request('/api/blind/rules','PUT',{expectedVersion:w.version,rules:data.rules});assert.equal(r.statusCode,200,r.body);preserve();w=await get('/api/blind/workspace');assert.deepEqual({records:w.records,rules:w.rules},data);return w;};
  const effectCount=()=>{const reader=openBlindEffectStore(INTENT_PATHS.fixture);try{return Number((reader.db.prepare('SELECT count(*) n FROM blind_effects').get() as any).n);}finally{reader.close();}};
  await putPrivate(f.initial);assert.deepEqual(ledger(),approval.ledger,'LOCAL_FIXTURE_CHARGED');preserve();
  const start=await request('/api/blind/runs','POST',{taskId:f.taskId,advisory:f.advisory});assert.equal(start.statusCode,202,start.body);const id=start.json().runId;preserve();await host.waitForRun(id);result.composition=await get('/api/blind/runs/'+id+'/export');preserve();let view=await get('/api/blind/runs/'+id);
  assert.equal(stopped,false,'FAILED_OR_UNKNOWN_STOP');assert.equal(view.state,'succeeded',view.error?.code);assertIntentionRecipe(view.recipe);assert.deepEqual(claims(view.result.rows),approval.preregistered.expectedInitial,'INDEPENDENT_INITIAL_EXPECTATION');
  result.contrast=approval.preparedRecipes.map((recipe:any)=>({recipe,values:claims(independentlyPrepared(recipe,f.initial))}));assert.notDeepEqual(result.contrast[0].values,claims(view.result.rows),'PREPARED_RESULT_NOT_MEANINGFULLY_DIFFERENT');preserve();
  const before=await get('/api/blind/runs/'+id+'/export'),ledgerBefore=ledger(),attemptsBeforeHash=objectHash(attempts()),actualBefore=claims(view.result.rows),revision=view.resultRevision,constructionBefore=construction(view.recipe,f,before.captures);
  await putPrivate(f.mutated);const effectsBefore=effectCount(),stale=await request('/api/blind/runs/'+id+'/save','POST',{resultRevision:revision});assert.equal(stale.json().code,'STALE_RESULT');assert.equal(effectCount(),effectsBefore);preserve();
  const rebound=await request('/api/blind/runs/'+id+'/rebind','POST',{});assert.equal(rebound.statusCode,200,rebound.body);view=rebound.json();const after=await get('/api/blind/runs/'+id+'/export');assert.deepEqual(ledger(),ledgerBefore);assert.equal(objectHash(attempts()),attemptsBeforeHash);assert.deepEqual(after.captures,before.captures);assert.deepEqual(claims(view.result.rows),approval.preregistered.expectedMutated,'INDEPENDENT_MUTATED_EXPECTATION');assert.notDeepEqual(claims(view.result.rows),actualBefore);
  result.rebind={before,after,saved:null,actualBefore,actualAfter:claims(view.result.rows),initialHash:approval.preregistered.initialHash,mutatedHash:approval.preregistered.mutatedHash,ledgerBefore,ledgerAfter:ledger(),attemptsBeforeHash,attemptsAfterHash:objectHash(attempts()),constructionBefore,constructionAfter:construction(view.recipe,f,after.captures),staleSave:{code:'STALE_RESULT',effectsBefore,effectsAfter:effectCount()},observer:null};preserve();process.stdout.write('Intent composed correctly; private rebind verified with zero new attempts\n');
  guard();const save=await request('/api/blind/runs/'+id+'/save','POST',{resultRevision:view.resultRevision});result.rebind.saved=await get('/api/blind/runs/'+id+'/export');preserve();assert.equal(stopped,false,'SAVE_UNKNOWN_NOT_REPLAYED');assert.equal(save.statusCode,200,save.body);assert.equal(save.json().save?.state,'confirmed');
  const reader=openBlindEffectStore(INTENT_PATHS.fixture);try{const rows=reader.readRevision(id,view.resultRevision);assert.equal(rows.length,1);const row=rows[0]!;assert.equal(row.content,JSON.stringify(view.result),'INDEPENDENT_EXACT_BYTES');assert.equal(row.caller_id,'developer');assert.equal(row.sink_id,'internal');assert.equal(row.workspace_version,view.workspaceVersion);result.rebind.observer={status:'observed',count:1,contentHash:objectHash(JSON.parse(row.content)),canonicalHash:objectHash(view.result),exactBytes:true,artifactId:row.id,effectId:row.effect_id,actionRunId:row.action_run_id,parentRunId:row.parent_run_id,resultRevision:row.result_revision};}finally{reader.close();}
  result.status='complete';preserve();const checked=validateIntentProof(result);process.stdout.write(JSON.stringify(checked)+'\n');
 }catch(e){stopped=true;result.status='partial';result.error=e instanceof ControlError?e.code:'INTENT_ASSERTION_FAILED';preserve();throw new Error(result.error+'; partial evidence and charges retained; no automatic retry');}finally{if(host){preserve();await host.close();}}
});
// The comparison interprets retained prepared methods independently, rather than
// feeding either fixture values or a substitute method to the actual actor.
function independentlyPrepared(recipe:any,data:any){const window=recipe.steps.find((s:any)=>s.op==='select_due').windowDays;let rows=data.records.filter((r:any)=>r.dueDays<=window).map((r:any)=>({...r,targetCents:Math.floor(r.currentCents*(10000+data.rules.maxIncreaseBp)/10000),savingCents:Math.max(0,r.quoteCents-Math.floor(r.currentCents*(10000+data.rules.maxIncreaseBp)/10000)),atRisk:recipe.steps.some((s:any)=>s.op==='evaluate_service')&&r.servicePct<data.rules.minimumServicePct}));if(recipe.taskId==='negotiation-savings')rows=rows.filter((r:any)=>r.savingCents>=data.rules.minimumSavingCents);const rank=recipe.steps.find((s:any)=>s.op==='rank').by;rows.sort((a:any,b:any)=>(rank==='soonest'?a.dueDays-b.dueDays:rank==='service-risk'?Number(b.atRisk)-Number(a.atRisk)||a.servicePct-b.servicePct:0)||b.savingCents-a.savingCents||(a.id<b.id?-1:a.id>b.id?1:0));return rows.slice(0,recipe.steps.find((s:any)=>s.op==='take')?.count??10).slice(0,10);}
