import {z} from 'zod';
import {createHash} from 'node:crypto';
import {RecipeSchema,TaskIdSchema,validateRecipe} from './blind.js';
import {EvidenceExportSchema,EvidenceModelIdentitySchema} from './contracts.js';
import {validatePublicApplicationBody,type ProfileId} from './prompt-profiles.js';
const int=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),hashSchema=z.string().regex(/^[a-f0-9]{64}$/),uuid=z.string().uuid();
const model=(value:unknown)=>{const r=EvidenceModelIdentitySchema.safeParse(value);return r.success?r.data:null;};
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const BlindSpanSchema=z.strictObject({kind:z.enum(['deterministic','advisory-checker','recipe-checker','planner','local','mcp','overall']),unit:z.literal('ms'),startedMs:z.number().finite().nonnegative(),endedMs:z.number().finite().nonnegative(),durationMs:z.number().finite().nonnegative().max(1000000),startedAt:z.string().datetime(),capturedAt:z.string().datetime(),outcome:z.enum(['resolved','rejected']),boundary:z.enum(['synchronous_control_entry_to_exit','generate_entry_to_resolution_or_rejection','local_executor_entry_to_exit','mcp_call_entry_to_resolution_or_rejection','composition_entry_to_cleanup','rebind_entry_to_exit','save_action_entry_to_cleanup']),requestedModel:EvidenceModelIdentitySchema.nullable(),returnedModel:EvidenceModelIdentitySchema.nullable()}).refine(s=>s.endedMs>=s.startedMs&&Math.abs(s.endedMs-s.startedMs-s.durationMs)<.01);
export type BlindSpan=z.infer<typeof BlindSpanSchema>;
const HardwareSchema=EvidenceExportSchema.shape.measurements.shape.hardware;
const MeasurementSchema=z.strictObject({status:z.enum(['measured','unavailable']),hardware:HardwareSchema,spans:z.array(BlindSpanSchema).max(128),samplesTruncated:z.boolean(),aggregates:z.array(z.strictObject({kind:BlindSpanSchema.shape.kind,count:int.max(4096),totalMs:z.number().finite().nonnegative()})).max(7),workload:z.strictObject({events:int.max(128),attempts:int.max(512),localExecutions:int.max(4096),repetitions:int.max(4096)})});
const AttemptSchema=EvidenceExportSchema.shape.attempts.element;
const BasisSchema=z.strictObject({policyHash:hashSchema,feedHash:hashSchema,policyVersion:int,feedVersion:int,semantic:z.boolean(),threshold:z.number().min(0).max(1),signatures:z.boolean()});
const reasons=['unrecognized','signature_match','benign','active','quoted','uncertain','semantic_disabled','model_response','brief_rendered','rebound_without_models','independent_brief_save','unknown_save','save_blocked','external_export_refused','CHECKER_FAILED_CLOSED','CHECKER_UNCERTAIN','PRIVACY_BLOCK','ALLOWANCE_EXHAUSTED','RUN_CALL_LIMIT','DEADLINE','PROVIDER_CLEARANCE','SINK_DENIED','MODEL_ALLOWLIST','SCHEMA_REJECTED','WORKFLOW_FAILED','RECIPE_DENIED','RECIPE_REQUIRED','EFFECT_MISMATCH','NEW_COMPOSITION_REQUIRED','SOURCE_ADMISSION_INVALIDATED','ADMISSION_INPUT_CHANGED','ACTION_IN_FLIGHT','CONTROL_RESPONSE_BOUND'] as const;
const stages=['inspection','actor','checker','local','reconciliation','blocked','save','manual','unrecognized'] as const;
export const BlindEvidenceSchema=z.strictObject({
 schemaVersion:z.literal('proofgate-blind-evidence-1'),generatedAt:z.string().datetime(),
 run:z.strictObject({runId:uuid,taskId:TaskIdSchema,mode:z.enum(['live','offline','replay']),synthetic:z.literal(true),state:z.enum(['running','succeeded','blocked','incomplete','empty']),resultCurrent:z.boolean(),resultVersion:int.nullable(),workspaceVersion:int.nullable()}),
 policy:z.strictObject({scope:z.literal('current_accepted'),hash:hashSchema,version:int,feedVersion:int,semantic:z.boolean(),threshold:z.number(),signatures:z.boolean(),privacy:z.enum(['block','redact']),providerAllowed:z.boolean(),internalSinkAllowed:z.boolean(),actor:EvidenceModelIdentitySchema.nullable(),checker:EvidenceModelIdentitySchema.nullable(),modelAllowlist:z.array(EvidenceModelIdentitySchema).max(16),limits:z.strictObject({calls:int,credits:int,runCalls:int,runMs:int,attemptMs:int,requestBytes:int,responseBytes:int,actorTokens:int,checkerTokens:int})}),
 feed:z.strictObject({scope:z.literal('current_accepted'),version:int,hash:hashSchema,signatures:z.array(z.strictObject({idHash:hashSchema,patternHash:hashSchema,reasonCodeHash:hashSchema})).max(128)}),
 admissionBasis:BasisSchema.nullable(),admission:z.strictObject({advisory:z.enum(['pending','admitted','quarantined']),advisoryClassification:z.enum(['benign','active','quoted','uncertain']).nullable(),recipeClassification:z.enum(['benign','active','quoted','uncertain']).nullable()}),
 recipe:RecipeSchema.nullable(),captures:z.array(z.strictObject({attemptId:uuid,profileId:z.enum(['blind-planner','blind-advisory-checker','blind-recipe-checker']),mode:z.enum(['live','offline']),evidence:z.literal('actual_application_dispatch'),sourceIdentity:z.enum(['hosted_sdk_dispatch','offline_injected_dispatch']),dispatchStatus:z.literal('dispatched'),outcome:AttemptSchema.shape.outcome,serializedBody:z.string().max(65536)})).max(32),
 events:z.array(z.strictObject({sequence:int,stage:z.enum(stages),reasonCode:z.enum(reasons),policyVersion:int.nullable()})).max(128),eventsTruncated:z.boolean(),attempts:z.array(AttemptSchema).max(512),
 ledger:EvidenceExportSchema.shape.ledger,
 save:z.strictObject({actionRunId:uuid,parentRunId:uuid,resultRevision:uuid,state:z.enum(['pending','confirmed','unknown','blocked']),acknowledged:z.boolean(),artifactId:uuid.nullable(),attempts:z.array(AttemptSchema).max(512)}).nullable(),
 independentEffects:z.strictObject({status:z.enum(['observed','unavailable']),count:int.max(16).nullable(),hostAcknowledged:z.boolean(),matchesCanonicalBrief:z.boolean().nullable(),effects:z.array(z.strictObject({artifactId:uuid,effectId:uuid,actionRunId:uuid,parentRunId:uuid,resultRevision:uuid,sink:z.literal('internal'),contentHash:hashSchema})).max(16)}),
 measurements:MeasurementSchema,saveMeasurements:MeasurementSchema.nullable(),
 manualExternalRefusal:z.strictObject({evidence:z.literal('manual_deterministic_refusal'),reasonCode:z.literal('EXTERNAL_SINK_DENIED'),sinkEffects:z.literal(0)}).nullable()
});
export type BlindEvidence=z.infer<typeof BlindEvidenceSchema>;
function projectMeasurements(raw:any,events:number,attempts:number,localExecutions:number){
 const unavailable={status:'unavailable',hardware:null,spans:[],samplesTruncated:false,aggregates:[],workload:{events,attempts,localExecutions,repetitions:0}};
 if(!raw)return unavailable;
 if(!Array.isArray(raw.spans)||raw.spans.length>128||!Array.isArray(raw.aggregates)||raw.aggregates.length>7)throw new Error('EVIDENCE_INVALID');
 const spans=raw.spans.map((s:any)=>BlindSpanSchema.parse({kind:s.kind,unit:s.unit,startedMs:s.startedMs,endedMs:s.endedMs,durationMs:s.durationMs,startedAt:s.startedAt,capturedAt:s.capturedAt,outcome:s.outcome,boundary:s.boundary,requestedModel:model(s.requestedModel),returnedModel:model(s.returnedModel)}));
 const h=raw.hardware;if(h&&Object.values(h).some(v=>typeof v==='string'&&/(?:[<>]|sk-|secret|credential|token|canary|sentinel)/i.test(v)))throw new Error('EVIDENCE_INVALID');
 const hardware=h?{node:h.node,platform:h.platform,architecture:h.architecture,osRelease:h.osRelease,cpuModel:h.cpuModel,cpuCores:h.cpuCores,totalMemoryBytes:h.totalMemoryBytes}:null;
 const aggregates=raw.aggregates.map((a:any)=>({kind:a.kind,count:a.count,totalMs:a.totalMs}));
 for(const a of aggregates){const samples=spans.filter((s:BlindSpan)=>s.kind===a.kind);if(a.count<samples.length||a.totalMs+.01<samples.reduce((n:number,s:BlindSpan)=>n+s.durationMs,0))throw new Error('EVIDENCE_INVALID');}
 return MeasurementSchema.parse({status:spans.length?'measured':'unavailable',hardware,spans,samplesTruncated:raw.samplesTruncated===true,aggregates,workload:{events,attempts,localExecutions,repetitions:aggregates.find((a:any)=>a.kind==='overall')?.count??0}});
}
// No private record, rule, result, arbitrary verdict/event text or transport secret is copied.
export function projectBlindEvidence({view:v,policy:p,feed,events:rawEvents,measurement,saveMeasurement}:any):BlindEvidence{
 const attempts=(rows:any[])=>rows.map(a=>AttemptSchema.parse({id:a.id,kind:a.kind,credits:a.credits,dispatched:!!a.dispatched,outcome:a.outcome,usage:typeof a.usage==='string'?JSON.parse(a.usage):a.usage??null}));
 const composition=attempts(v.attempts),action=v.saveAction?attempts(v.saveAction.attempts):[];
 const captures=v.captures.map((c:any)=>{const a=composition.find(x=>x.id===c.attemptId);if(!a?.dispatched||!['actor','checker'].includes(a.kind)||c.mode!==v.mode||c.outcome!==a.outcome||c.dispatchStatus!=='dispatched'||c.evidence!=='actual_application_dispatch')throw new Error('EVIDENCE_INVALID');validatePublicApplicationBody(c.profileId as ProfileId,a.kind as 'actor'|'checker',c.serializedBody);return{attemptId:c.attemptId,profileId:c.profileId,mode:c.mode,evidence:'actual_application_dispatch',sourceIdentity:c.mode==='live'?'hosted_sdk_dispatch':'offline_injected_dispatch',dispatchStatus:'dispatched',outcome:c.outcome,serializedBody:c.serializedBody};});
 const events=rawEvents.slice(0,128).map((e:any,i:number)=>({sequence:i+1,stage:stages.includes(e.stage)?e.stage:'unrecognized',reasonCode:reasons.includes(e.reason)?e.reason:'unrecognized',policyVersion:Number.isSafeInteger(e.policyVersion)&&e.policyVersion>=0?e.policyVersion:null}));
 const r=v.resources,e=v.independentEffects;
 if(v.recipe)validateRecipe(v.recipe,v.taskId);
 const result=BlindEvidenceSchema.parse({schemaVersion:'proofgate-blind-evidence-1',generatedAt:new Date().toISOString(),run:{runId:v.runId,taskId:v.taskId,mode:v.mode,synthetic:true,state:v.state,resultCurrent:v.resultCurrent,resultVersion:v.resultVersion,workspaceVersion:v.workspaceVersion},policy:{scope:'current_accepted',hash:hash(p),version:p.version,feedVersion:p.feedVersion,semantic:p.controls.semantic,threshold:p.threshold,signatures:p.controls.signatures,privacy:p.controls.privacy,providerAllowed:p.sourceRules.providerAllowed,internalSinkAllowed:p.sinkRules.internalAllowed,actor:model(p.models.actor),checker:model(p.models.checker),modelAllowlist:p.models.allowlist.map(model),limits:Object.fromEntries(['calls','credits','runCalls','runMs','attemptMs','requestBytes','responseBytes','actorTokens','checkerTokens'].map(k=>[k,p.limits[k]]))},feed:{scope:'current_accepted',version:feed.version,hash:hash(feed),signatures:feed.signatures.map((s:any)=>({idHash:hash(s.id),patternHash:hash(s.pattern),reasonCodeHash:hash(s.reasonCode)}))},admissionBasis:v.basis&&BasisSchema.safeParse(v.basis).success?{policyHash:v.basis.policyHash,feedHash:v.basis.feedHash,policyVersion:v.basis.policyVersion,feedVersion:v.basis.feedVersion,semantic:v.basis.semantic,threshold:v.basis.threshold,signatures:v.basis.signatures}:null,admission:{advisory:v.advisoryStatus,advisoryClassification:v.advisoryVerdict?.classification??null,recipeClassification:v.recipeVerdict?.classification??null},recipe:v.recipe,captures,events,eventsTruncated:rawEvents.length>128,attempts:composition,ledger:{scope:'whole_epoch',epochId:r.epochId,creditsReserved:r.creditsReserved,creditsLimit:r.creditsLimit,callsUsed:r.callsUsed,callsLimit:r.callsLimit,runUsage:r.usage,estimatedTariffCost:r.estimatedCost},save:v.save?{actionRunId:v.save.actionRunId,parentRunId:v.runId,resultRevision:v.save.resultRevision,state:v.save.state,acknowledged:v.save.acknowledged,artifactId:v.save.artifactId,attempts:action}:null,independentEffects:{status:e.status,count:e.count,hostAcknowledged:e.hostAcknowledged,matchesCanonicalBrief:e.matchesCanonicalBrief,effects:e.effects.map((x:any)=>({artifactId:x.artifactId,effectId:x.effectId,actionRunId:x.actionRunId,parentRunId:x.parentRunId,resultRevision:x.resultRevision,sink:x.sink,contentHash:x.contentHash}))},measurements:projectMeasurements(measurement,events.length,composition.length,v.localExecutions),saveMeasurements:v.save?projectMeasurements(saveMeasurement,0,action.length,0):null,manualExternalRefusal:rawEvents.some((x:any)=>x.stage==='manual'&&x.reason==='external_export_refused')?{evidence:'manual_deterministic_refusal',reasonCode:'EXTERNAL_SINK_DENIED',sinkEffects:0}:null});
 if(Buffer.byteLength(JSON.stringify(result))>262144)throw new Error('CONTROL_RESPONSE_BOUND');return result;
}
