import { z } from 'zod';
export const MigrationSchema=z.strictObject({oldApi:z.literal('configure'),newApi:z.literal('configureAsync'),requiresAwait:z.literal(true)});
export const MIGRATION=MigrationSchema.parse({oldApi:'configure',newApi:'configureAsync',requiresAwait:true});
export const PREPARATION_STEPS={review_call_sites:'Review call sites that currently use configure.',plan_await_initialization:'Plan the replacement with configureAsync and await initialization.',review_internal_draft:'Review this cited internal migration draft before executing any changes.'} as const;
export const DraftPlanSchema=z.strictObject({sourceVersion:z.string().min(1).max(64),targetVersion:z.string().min(1).max(64),migration:MigrationSchema,preparationStatus:z.literal('draft_only'),steps:z.array(z.enum(['review_call_sites','plan_await_initialization','review_internal_draft'])).min(1).max(3),citations:z.array(z.string().min(1).max(128)).min(1).max(16)});
export const DraftSchema=DraftPlanSchema.extend({breakingChange:z.string().min(1).max(2000),body:z.string().min(1).max(8000)});
export function renderDraft(plan:z.infer<typeof DraftPlanSchema>){return DraftSchema.parse({...plan,breakingChange:`${plan.migration.oldApi} becomes ${plan.migration.newApi}; callers must await initialization.`,body:`Internal migration preparation: replace ${plan.migration.oldApi} with ${plan.migration.newApi} and await initialization.\n${plan.steps.map(step=>PREPARATION_STEPS[step]).join('\n')}\nPreparation only: no dependency installation, testing or deployment has occurred.`});}
export type Draft = z.infer<typeof DraftSchema>;
export const SourceSchema=z.strictObject({sourceId:z.string().min(1).max(128),text:z.string().min(1).max(16000)});
export const SaveSchema=z.strictObject({draftId:z.string().min(1).max(128)});
export const ToolRegistry={
 read_project_context:{args:z.strictObject({projectId:z.literal('proofgate-demo')}),result:SourceSchema},
 read_dependency_evidence:{args:z.strictObject({dependency:z.literal('ProofLib'),sourceVersion:z.literal('1.0.0'),targetVersion:z.literal('2.0.0')}),result:SourceSchema},
 save_internal_draft:{args:z.strictObject({draft:DraftSchema}),result:SaveSchema}
} as const;
export type ToolName=keyof typeof ToolRegistry;
export const ProposalSchema=z.union([
 z.strictObject({kind:z.literal('tool'),tool:z.literal('read_project_context'),args:ToolRegistry.read_project_context.args}),
 z.strictObject({kind:z.literal('tool'),tool:z.literal('read_dependency_evidence'),args:ToolRegistry.read_dependency_evidence.args}),
 z.strictObject({kind:z.literal('tool'),tool:z.literal('save_internal_draft'),args:z.strictObject({draft:DraftPlanSchema})}),
 z.strictObject({kind:z.literal('final'),draft:DraftSchema}),
 z.strictObject({kind:z.literal('incomplete'),reason:z.string().min(1).max(2000)})]);
export type Proposal=z.infer<typeof ProposalSchema>;
export const VerdictSchema=z.strictObject({classification:z.enum(['benign','active','quoted','uncertain']),confidence:z.number().min(0).max(1),reasonCode:z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/)});
export type Verdict=z.infer<typeof VerdictSchema>;
const boundedInt=(min:number,max:number)=>z.number().int().min(min).max(max);
export const POLICY_VERSION_MAX=1000000;
export const PolicySchema=z.strictObject({version:boundedInt(1,POLICY_VERSION_MAX),profile:z.enum(['standard','restricted']),controls:z.strictObject({semantic:z.boolean(),privacy:z.enum(['block','redact']),flow:z.boolean(),signatures:z.boolean()}),strictness:z.enum(['standard','strict']),threshold:z.number().min(0.5).max(1),models:z.strictObject({actor:z.string().max(128),checker:z.string().max(128),allowlist:z.array(z.enum(['gemini-3.5-flash','gemini-3.5-flash-lite'])).min(1).max(2)}),sourceRules:z.strictObject({syntheticOnly:z.literal(true),providerAllowed:z.boolean(),audiences:z.array(z.enum(['internal'])).min(1).max(1)}),sinkRules:z.strictObject({internalAllowed:z.boolean(),publicAllowed:z.literal(false)}),feedVersion:boundedInt(1,1000000),limits:z.strictObject({credits:boundedInt(1,134217728),calls:boundedInt(1,512),runCalls:boundedInt(1,16),actorTurns:boundedInt(1,8),runMs:boundedInt(1,120000),attemptMs:boundedInt(1,25000),requestBytes:boundedInt(1,65536),responseBytes:boundedInt(1,262144),jsonBytes:boundedInt(1,16384),parts:boundedInt(1,16),actorTokens:boundedInt(1,2048),checkerTokens:boundedInt(1,256)}),tariffs:z.strictObject({asOf:z.string().min(1).max(64),prompt:z.number().nonnegative().nullable(),output:z.number().nonnegative().nullable(),thought:z.number().nonnegative().nullable(),cache:z.number().nonnegative().nullable()})});
export type Policy=z.infer<typeof PolicySchema>;
export const FeedSchema=z.strictObject({version:boundedInt(1,1000000),signatures:z.array(z.strictObject({id:z.string().min(1).max(64),pattern:z.string().min(1).max(256),reasonCode:z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/)})).max(64)});
export type Feed=z.infer<typeof FeedSchema>;
export type Usage={prompt:number;output:number;thought:number;cache:number};
export type RunView={audit?:AuditProjection;runId:string;state:'empty'|'running'|'blocked'|'incomplete'|'succeeded';mode:'live'|'offline'|'replay';synthetic:true;policyVersion:number;feedVersion:number;evidence:{sourceId:string;status:'admitted'|'quarantined'|'blocked';summary:string}[];decisions:{sequence:number;stage:string;reasonCode:string;sourceId:string|null;policyVersion:number}[];draft:Draft|null;effects:{savedCount:number;reconciled:boolean};resources:{epochId:string;creditsReserved:number;creditsLimit:number;callsUsed:number;callsLimit:number;usage:Usage|null;estimatedCost:number|null};error:{code:string;message:string}|null};
const HashSchema=z.string().regex(/^[a-f0-9]{64}$/);
const RefSchema=z.string().regex(/^[a-f0-9-]{36}(?::(?:notes|facts|advisory))?$/);
const IdentitySchema=z.string().regex(/^[A-Za-z0-9._:-]{1,128}$/);
// Exact supported/observed provider identities and one fixed offline evidence label.
// Arbitrary provider/operator text is represented by hashes, never character filtering.
export const EvidenceModelIdentitySchema=z.enum(['gemini-3.5-flash','gemini-3.5-flash-lite','offline-injected']);
const ModelEvidenceFields={requestedModel:EvidenceModelIdentitySchema.nullable(),returnedModel:EvidenceModelIdentitySchema.nullable(),returnedModelHash:HashSchema.nullable().default(null),responseId:z.null(),responseIdHash:HashSchema.nullable().default(null)};
export const AdmissionOutcomeSchema=z.strictObject({status:z.enum(['admitted','quarantined','blocked']),matchedSignature:z.strictObject({idHash:HashSchema,patternHash:HashSchema,reasonCodeHash:HashSchema}).nullable()});
export const SpanSchema=z.strictObject({kind:z.enum(['deterministic','checker','actor','mcp','overall']),unit:z.literal('ms'),durationMs:z.number().finite().nonnegative().max(1000000),startedAt:z.string().datetime(),capturedAt:z.string().datetime(),outcome:z.enum(['resolved','rejected']),boundary:z.enum(['synchronous_control_entry_to_exit','generate_entry_to_resolution_or_rejection','mcp_call_entry_to_resolution_or_rejection','processRun_entry_to_cleanup']),...ModelEvidenceFields});
export type MeasuredSpan=z.infer<typeof SpanSchema>;
const UsageSchema=z.strictObject({prompt:boundedInt(0,Number.MAX_SAFE_INTEGER),output:boundedInt(0,Number.MAX_SAFE_INTEGER),thought:boundedInt(0,Number.MAX_SAFE_INTEGER),cache:boundedInt(0,Number.MAX_SAFE_INTEGER)});
export const EvidenceExportSchema=z.strictObject({schemaVersion:z.literal('proofgate-evidence-1'),generatedAt:z.string().datetime(),run:z.strictObject({runId:z.string().uuid(),mode:z.enum(['live','offline','replay']),synthetic:z.literal(true),state:z.enum(['empty','running','blocked','incomplete','succeeded']),policyVersion:boundedInt(1,POLICY_VERSION_MAX),feedVersion:boundedInt(1,POLICY_VERSION_MAX)}),
 policy:z.strictObject({scope:z.literal('current_accepted'),hash:HashSchema,snapshot:PolicySchema}),feed:z.strictObject({scope:z.literal('current_accepted'),version:boundedInt(1,POLICY_VERSION_MAX),hash:HashSchema,signatures:z.array(z.strictObject({id:z.null(),reasonCode:z.null(),idHash:HashSchema,patternHash:HashSchema,reasonCodeHash:HashSchema})).max(64)}),
 events:z.array(z.strictObject({sequence:boundedInt(1,128),stage:IdentitySchema,reasonCode:IdentitySchema,sourceId:RefSchema.nullable(),policyVersion:boundedInt(1,POLICY_VERSION_MAX),feedVersion:boundedInt(1,POLICY_VERSION_MAX).nullable(),hashes:z.strictObject({sourceHash:HashSchema.nullable(),clearedHash:HashSchema.nullable(),inputHash:HashSchema.nullable(),schemaHash:HashSchema.nullable(),promptHash:HashSchema.nullable(),proposalHash:HashSchema.nullable(),policyHash:HashSchema.nullable(),feedHash:HashSchema.nullable()}),admission:z.strictObject({semantic:z.boolean(),threshold:z.number().min(.5).max(1),signatures:z.boolean(),classification:z.enum(['benign','active','quoted','uncertain']).nullable(),confidence:z.number().min(0).max(1).nullable(),status:AdmissionOutcomeSchema.shape.status.nullable().default(null),matchedSignature:AdmissionOutcomeSchema.shape.matchedSignature.default(null)}).nullable()})).max(128),
 attempts:z.array(z.strictObject({id:z.string().uuid(),kind:z.enum(['actor','checker','auth','tool']),credits:boundedInt(0,Number.MAX_SAFE_INTEGER),dispatched:z.boolean(),outcome:z.enum(['reserved','known','unknown','unsent']),usage:UsageSchema.nullable()})).max(512),
 ledger:z.strictObject({scope:z.literal('whole_epoch'),epochId:z.string().uuid(),creditsReserved:boundedInt(0,Number.MAX_SAFE_INTEGER),creditsLimit:boundedInt(1,134217728),callsUsed:boundedInt(0,Number.MAX_SAFE_INTEGER),callsLimit:boundedInt(1,512),runUsage:UsageSchema.nullable(),estimatedTariffCost:z.number().finite().nonnegative().nullable()}),
 independentEffects:z.strictObject({status:z.enum(['observed','unavailable']),count:boundedInt(0,16).nullable(),hostAcknowledged:z.boolean(),matchesCanonicalDraft:z.boolean().nullable(),effects:z.array(z.strictObject({effectId:z.string().uuid(),sink:z.literal('internal'),contentHash:HashSchema})).max(16)}),
 draft:z.strictObject({sourceVersion:z.literal('1.0.0'),targetVersion:z.literal('2.0.0'),migration:MigrationSchema,preparationStatus:z.literal('draft_only'),citations:z.array(RefSchema).max(16),contentHash:HashSchema}).nullable(),
 measurements:z.strictObject({status:z.enum(['measured','unavailable']),mode:z.enum(['live','offline','replay']),scenario:z.enum(['clean','hostile','missing']).nullable(),hardware:z.strictObject({node:z.string().max(32),platform:z.string().max(32),architecture:z.string().max(32),osRelease:z.string().max(128),cpuModel:z.string().max(128),cpuCores:boundedInt(1,65536),totalMemoryBytes:boundedInt(1,Number.MAX_SAFE_INTEGER)}).nullable(),spans:z.array(SpanSchema).max(128),samplesTruncated:z.boolean(),aggregates:z.array(z.strictObject({kind:SpanSchema.shape.kind,count:boundedInt(1,4096),totalMs:z.number().finite().nonnegative()})).max(5),workload:z.strictObject({events:boundedInt(0,128),attempts:boundedInt(0,512),sources:boundedInt(0,16)}),models:z.array(z.strictObject({role:z.enum(['actor','checker']),...ModelEvidenceFields})).max(32)})});
export type EvidenceExport=z.infer<typeof EvidenceExportSchema>;
export type AuditProjection=Pick<EvidenceExport,'independentEffects'|'measurements'>;
export const START_SCHEMA=z.strictObject({scenario:z.enum(['clean','hostile','missing']),advisory:z.string().min(1).max(4096).refine(text=>Buffer.byteLength(text,'utf8')<=4096).optional()});
export type Scenario=z.infer<typeof START_SCHEMA>['scenario'];
export const TRUSTED_META=z.strictObject({runId:z.string().uuid(),callerId:z.literal('developer'),audiences:z.array(z.literal('internal')).length(1),sinkId:z.literal('internal')});
export const jsonSchema=(schema:z.ZodType)=>z.toJSONSchema(schema,{target:'draft-07'});
