import Fastify from 'fastify';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { cpus, totalmem, release } from 'node:os';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js';
import { EvidenceExportSchema, EvidenceModelIdentitySchema, AdmissionOutcomeSchema, SpanSchema, type MeasuredSpan, type EvidenceExport, DraftSchema, DraftPlanSchema, renderDraft, ProposalSchema, VerdictSchema, PolicySchema, FeedSchema, ToolRegistry, START_SCHEMA, jsonSchema, type Draft, type Policy, type Feed, type Verdict, type RunView, type Scenario, type Usage, type ToolName } from './contracts.js';
import { createModelAdapter, ControlError, type HostPorts, type ModelAdapter, type Kind } from './model.js';
import { openEffectStore, initializeEffectStore, ADVISORIES, FACTS, ESSENTIAL_FACTS, FIXTURE_BUSY_MS } from '../fixture/server.js';
import {BlindStartSchema,RecipeSchema,validateRecipe,executeRecipe,initialPrivate,DEFAULT_ADVISORY,buildPlanner,buildAdvisoryInspection,buildRecipeInspection,publicCapabilities,PrivateUpdateSchema,RulesUpdateSchema,SaveRequestSchema,BlindSaveArgsSchema,BlindSaveResultSchema,BlindSaveMetaSchema,type Recipe} from './blind.js';
import {validatePublicApplicationBody,type ProfileId} from './prompt-profiles.js';
import {initializeBlindStore,openBlindEffectStore,BLIND_BUSY_MS} from '../fixture/blind-store.js';
import {projectBlindEvidence,BlindSpanSchema,type BlindSpan} from './blind-evidence.js';
const ROOT=fileURLToPath(new URL('../..',import.meta.url));
const configRoot=resolve(ROOT,'config');
const loadPolicy=()=>PolicySchema.parse(JSON.parse(readFileSync(resolve(configRoot,'policy.json'),'utf8')));
const loadFeed=()=>FeedSchema.parse(JSON.parse(readFileSync(resolve(configRoot,'signatures.json'),'utf8')));
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const CONTROL_RESPONSE_BYTES=262144;
export const MAX_ACTIVE_RUNS=4;
export const RUN_QUEUE_CAPACITY=0;
const controlSnapshot=<T>(data:T):T=>{if(Buffer.byteLength(JSON.stringify(data))>CONTROL_RESPONSE_BYTES)throw new ControlError('CONTROL_RESPONSE_BOUND');return data;};
export function openStore(path:string){
 if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});const db=new DatabaseSync(path);
 db.exec(`PRAGMA journal_mode=WAL;
 CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,caller TEXT NOT NULL,view TEXT NOT NULL,deadline INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,metadata TEXT NOT NULL,text TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT NOT NULL,stage TEXT NOT NULL,reason TEXT NOT NULL,details TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS policy(id TEXT PRIMARY KEY,content TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,credits INTEGER NOT NULL,calls INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,kind TEXT NOT NULL,credits INTEGER NOT NULL,dispatched INTEGER NOT NULL DEFAULT 0,outcome TEXT NOT NULL DEFAULT 'reserved',usage TEXT);`);
 db.exec(`CREATE TABLE IF NOT EXISTS workflow_variants(run_id TEXT PRIMARY KEY,variant TEXT NOT NULL,parent_id TEXT,result_revision TEXT);
 CREATE TABLE IF NOT EXISTS blind_workspace(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL,content TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS blind_runs(run_id TEXT PRIMARY KEY,content TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS blind_result_sequence(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS blind_captures(attempt_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,profile_id TEXT NOT NULL,body TEXT NOT NULL);`);
 db.prepare('INSERT OR IGNORE INTO blind_workspace VALUES(1,1,?)').run(JSON.stringify(initialPrivate()));
 db.prepare('INSERT OR IGNORE INTO blind_result_sequence VALUES(1,0)').run();
 db.prepare('INSERT OR IGNORE INTO policy VALUES (?,?)').run('policy',JSON.stringify(loadPolicy()));db.prepare('INSERT OR IGNORE INTO policy VALUES (?,?)').run('feed',JSON.stringify(loadFeed()));
 if(!db.prepare('SELECT id FROM ledger').get())db.prepare('INSERT INTO ledger VALUES (?,0,0)').run(randomUUID());
 const getPolicy=()=>PolicySchema.parse(JSON.parse((db.prepare('SELECT content FROM policy WHERE id=?').get('policy') as any).content));
 const getFeed=()=>FeedSchema.parse(JSON.parse((db.prepare('SELECT content FROM policy WHERE id=?').get('feed') as any).content));
 function activatePolicy(expectedVersion:number,candidate:unknown){const next=controlSnapshot(PolicySchema.parse(candidate));const current=getPolicy();if(current.version!==expectedVersion||next.version!==expectedVersion+1||next.feedVersion!==getFeed().version)throw new ControlError('STALE_POLICY');if(!next.models.allowlist.includes(next.models.actor as any)||!next.models.allowlist.includes(next.models.checker as any))throw new ControlError('MODEL_ALLOWLIST');db.prepare('UPDATE policy SET content=? WHERE id=?').run(JSON.stringify(next),'policy');return next;}
 function activateFeed(expectedVersion:number,candidate:unknown){const next=controlSnapshot(FeedSchema.parse(candidate));if(getFeed().version!==expectedVersion||next.version!==expectedVersion+1)throw new ControlError('STALE_FEED');db.exec('BEGIN IMMEDIATE');try{const p=getPolicy();p.feedVersion=next.version;p.version++;controlSnapshot(PolicySchema.parse(p));db.prepare('UPDATE policy SET content=? WHERE id=?').run(JSON.stringify(next),'feed');db.prepare('UPDATE policy SET content=? WHERE id=?').run(JSON.stringify(p),'policy');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return next;}
 return {db,getPolicy,getFeed,activatePolicy,activateFeed,close(){db.close();}};
}
export type Store=ReturnType<typeof openStore>;
export const activatePolicy=(store:Store,expectedVersion:number,policy:unknown)=>store.activatePolicy(expectedVersion,policy);
export const activateFeed=(store:Store,expectedVersion:number,feed:unknown)=>store.activateFeed(expectedVersion,feed);
export function restrictedProfile(policy:Policy):Policy{return PolicySchema.parse({...policy,profile:'restricted',strictness:'strict',threshold:0.95,limits:{...policy.limits,credits:16777216,calls:32,actorTurns:6,runMs:90000,actorTokens:1536}});}
export type HostOptions={token:string;hostDbPath:string;fixtureDbPath:string;modelAdapter?:ModelAdapter|((ports:HostPorts)=>ModelAdapter);fixtureTransport?:(meteredActualTransport:Transport)=>Transport};
export function createHost(options:HostOptions){
 if(!options.token||options.token.length<16)throw new ControlError('TOKEN_REQUIRED');
 const store=openStore(options.hostDbPath);const {db}=store;const app=Fastify({logger:false,bodyLimit:65536,ajv:{customOptions:{removeAdditional:false,coerceTypes:false}}});
 const jobs=new Map<string,Promise<void>>();
 const activeActions=new Map<string,string>();
 const blindMeasurements=new Map<string,{eventId:number;data:{hardware:EvidenceExport['measurements']['hardware'];spans:BlindSpan[];samplesTruncated:boolean;aggregates:{kind:BlindSpan['kind'];count:number;totalMs:number}[]}}>();
 function beginBlindMeasurements(id:string){if(blindMeasurements.has(id))return;const row=db.prepare("SELECT id,details FROM events WHERE run_id=? AND stage='blind_measurements' ORDER BY id DESC LIMIT 1").get(id) as any;
  if(row){blindMeasurements.set(id,{eventId:row.id,data:JSON.parse(row.details)});return;}
  const cpu=cpus(),data={hardware:{node:process.version,platform:process.platform,architecture:process.arch,osRelease:release().slice(0,128),cpuModel:(cpu[0]?.model??'Unavailable').slice(0,128),cpuCores:cpu.length||1,totalMemoryBytes:totalmem()},spans:[] as BlindSpan[],samplesTruncated:false,aggregates:[] as {kind:BlindSpan['kind'];count:number;totalMs:number}[]};const inserted=db.prepare('INSERT INTO events(run_id,stage,reason,details) VALUES(?,?,?,?)').run(id,'blind_measurements','measured',JSON.stringify(data));blindMeasurements.set(id,{eventId:Number(inserted.lastInsertRowid),data});
 }
 function recordBlindSpan(id:string,kind:BlindSpan['kind'],start:number,startedAt:string,outcome:BlindSpan['outcome'],boundary:BlindSpan['boundary'],requestedModel:string|null=null,returnedModel:string|null=null){const m=blindMeasurements.get(id);if(!m)return;const end=performance.now(),span=BlindSpanSchema.parse({kind,unit:'ms',startedMs:start,endedMs:end,durationMs:end-start,startedAt,capturedAt:new Date().toISOString(),outcome,boundary,requestedModel:modelIdentity(requestedModel),returnedModel:modelIdentity(returnedModel)});let a=m.data.aggregates.find(a=>a.kind===kind);if(!a){a={kind,count:0,totalMs:0};m.data.aggregates.push(a);}a.count++;a.totalMs+=span.durationMs;if(m.data.spans.length<128)m.data.spans.push(span);else{m.data.samplesTruncated=true;if(kind==='overall')m.data.spans[127]=span;}db.prepare('UPDATE events SET details=? WHERE id=?').run(JSON.stringify(m.data),m.eventId);}
 async function measureBlindAsync<T>(id:string,kind:BlindSpan['kind'],work:()=>Promise<T>,boundary:BlindSpan['boundary'],requestedModel:string|null=null):Promise<T>{const start=performance.now(),startedAt=new Date().toISOString();let outcome:BlindSpan['outcome']='resolved',result:any;try{result=await work();return result;}catch(e){outcome='rejected';throw e;}finally{recordBlindSpan(id,kind,start,startedAt,outcome,boundary,requestedModel,result?.modelVersion??null);}}
 const measurements=new Map<string,{eventId:number;scenario:Scenario;hardware:EvidenceExport['measurements']['hardware'];spans:MeasuredSpan[];aggregates:Partial<Record<MeasuredSpan['kind'],{count:number;totalMs:number}>>;samplesTruncated:boolean}>();
 const modelIdentity=(v:unknown)=>{const result=EvidenceModelIdentitySchema.safeParse(v);return result.success?result.data:null;};
 const identityHash=(v:unknown):string|null=>typeof v==='string'?hash(v):null;
 function recordSpan(runId:string,span:z.input<typeof SpanSchema>){const m=measurements.get(runId);if(!m)return;const parsed=SpanSchema.parse(span);const aggregate=m.aggregates[span.kind]??={count:0,totalMs:0};aggregate.count++;aggregate.totalMs+=span.durationMs;if(m.spans.length<128)m.spans.push(parsed);else{m.samplesTruncated=true;if(span.kind==='overall')m.spans[127]=parsed;}db.prepare('UPDATE events SET details=? WHERE id=?').run(JSON.stringify({scenario:m.scenario,hardware:m.hardware,spans:m.spans,aggregates:m.aggregates,samplesTruncated:m.samplesTruncated}),m.eventId);}
 let controlDepth=0;
 function measureControl<T>(runId:string,work:()=>T):T{if(controlDepth)return work();controlDepth++;const start=performance.now(),startedAt=new Date().toISOString();let outcome:MeasuredSpan['outcome']='resolved';try{return work();}catch(e){outcome='rejected';throw e;}finally{controlDepth--;recordSpan(runId,{kind:'deterministic',unit:'ms',durationMs:performance.now()-start,startedAt,capturedAt:new Date().toISOString(),outcome,boundary:'synchronous_control_entry_to_exit',requestedModel:null,returnedModel:null,responseId:null});recordBlindSpan(runId,'deterministic',start,startedAt,outcome,'synchronous_control_entry_to_exit');}}
 async function measureAsync<T>(runId:string,kind:'actor'|'checker'|'mcp',work:()=>Promise<T>,requestedModel:string|null=null):Promise<T>{const start=performance.now(),startedAt=new Date().toISOString();let result:any,outcome:MeasuredSpan['outcome']='resolved';try{result=await work();return result;}catch(e){outcome='rejected';throw e;}finally{recordSpan(runId,{kind,unit:'ms',durationMs:performance.now()-start,startedAt,capturedAt:new Date().toISOString(),outcome,boundary:kind==='mcp'?'mcp_call_entry_to_resolution_or_rejection':'generate_entry_to_resolution_or_rejection',requestedModel:modelIdentity(requestedModel),returnedModel:kind==='mcp'?null:modelIdentity(result?.modelVersion),returnedModelHash:kind==='mcp'?null:identityHash(result?.modelVersion),responseId:null,responseIdHash:kind==='mcp'?null:identityHash(result?.responseId)});}}
 let fixtureInitialized=false;
 const getRun=(id:string)=>{const row=db.prepare('SELECT * FROM runs WHERE id=?').get(id) as any;if(!row||row.caller!=='developer')throw new ControlError('RUN_NOT_FOUND');return row;};
 const resources=(runId:string)=>{const p=store.getPolicy();const l=db.prepare('SELECT * FROM ledger').get() as any;const rows=db.prepare("SELECT usage,kind,outcome FROM attempts WHERE run_id=? AND kind IN ('actor','checker') AND dispatched=1").all(runId) as any[];let usage:Usage|null=rows.length?{prompt:0,output:0,thought:0,cache:0}:null;for(const row of rows){if(!row.usage){usage=null;break;}const u=JSON.parse(row.usage);if(usage)for(const k of ['prompt','output','thought','cache'] as const)usage[k]+=u[k];}const rates=p.tariffs;const estimatedCost=usage&&[rates.prompt,rates.output,rates.thought,rates.cache].every(v=>v!==null)?(Math.max(0,usage.prompt-usage.cache)*rates.prompt!+usage.output*rates.output!+usage.thought*rates.thought!+usage.cache*rates.cache!)/1e6:null;return {epochId:l.id,creditsReserved:l.credits,creditsLimit:p.limits.credits,callsUsed:l.calls,callsLimit:p.limits.calls,usage,estimatedCost};};
 const variant=(id:string)=>{getRun(id);return (db.prepare('SELECT variant FROM workflow_variants WHERE run_id=?').get(id) as any)?.variant??'release';};
 const view=(id:string):RunView=>{const v=JSON.parse(getRun(id).view) as RunView;v.resources=resources(id);return v;};
 const putView=(v:RunView)=>db.prepare('UPDATE runs SET view=? WHERE id=?').run(JSON.stringify(v),v.runId);
 const requireEventCapacity=(runId:string)=>{if(view(runId).decisions.length>=128)throw new ControlError('EVENT_BOUND');};
 const event=(runId:string,stage:string,reasonCode:string,sourceId:string|null=null,details:Record<string,unknown>={})=>{requireEventCapacity(runId);const v=view(runId);const p=store.getPolicy();v.policyVersion=p.version;v.feedVersion=store.getFeed().version;v.decisions.push({sequence:v.decisions.length+1,stage,reasonCode,sourceId,policyVersion:p.version});db.prepare('INSERT INTO events(run_id,stage,reason,details) VALUES (?,?,?,?)').run(runId,stage,reasonCode,JSON.stringify({...details,provenance:{policyVersion:p.version,feedVersion:p.feedVersion,decisionSequence:v.decisions.length}}));putView(v);};
 const ports:HostPorts={
 currentClearance(runId,kind){const r=getRun(runId);if(variant(runId)==='blind-save'&&kind!=='tool')throw new ControlError('SAVE_ONLY_AUTHORITY');if(Date.now()>=r.deadline)throw new ControlError('DEADLINE');const p=store.getPolicy();if(!p.sourceRules.providerAllowed||!p.sourceRules.syntheticOnly||!p.sourceRules.audiences.includes('internal'))throw new ControlError('PROVIDER_CLEARANCE');if(kind==='actor'||kind==='checker'){if(!p.models.allowlist.includes(p.models[kind] as any))throw new ControlError('MODEL_ALLOWLIST');}if(kind==='tool'&&!p.sinkRules.internalAllowed)throw new ControlError('SINK_DENIED');if(variant(runId)==='release'&&(kind==='actor'||kind==='tool'))clearedSources(runId);if(variant(runId)==='blind'&&(kind==='actor'||kind==='tool'))revalidateBlind(runId);if(variant(runId)==='blind-save')saveAuthority(runId);return p;},
 reserveAttempt(input){const p=ports.currentClearance(input.runId,input.kind);if(!Number.isSafeInteger(input.requestBytes)||input.requestBytes<0||input.requestBytes>p.limits.requestBytes||!Number.isSafeInteger(input.deadline)||input.deadline<=Date.now())throw new ControlError('REQUEST_BOUND');const cap=input.kind==='actor'?p.limits.actorTokens:input.kind==='checker'?p.limits.checkerTokens:0;if(!Number.isSafeInteger(input.outputTokens)||input.outputTokens<0||input.outputTokens>cap)throw new ControlError('OUTPUT_BOUND');const credits=input.requestBytes+p.limits.responseBytes+16*input.outputTokens;const id=randomUUID();db.exec('BEGIN IMMEDIATE');try{const n=(db.prepare("SELECT count(*) n FROM attempts WHERE run_id=? AND outcome!='unsent'").get(input.runId) as any).n;if(n>=p.limits.runCalls)throw new ControlError('RUN_CALL_LIMIT');const result=db.prepare('UPDATE ledger SET credits=credits+?,calls=calls+1 WHERE credits+?<=? AND calls+1<=?').run(credits,credits,p.limits.credits,p.limits.calls);if(Number(result.changes)!==1)throw new ControlError('ALLOWANCE_EXHAUSTED');db.prepare('INSERT INTO attempts(id,run_id,kind,credits) VALUES (?,?,?,?)').run(id,input.runId,input.kind,credits);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return id;},
 markDispatched(id){db.exec('BEGIN IMMEDIATE');let runId:string;try{const a=db.prepare('SELECT * FROM attempts WHERE id=?').get(id) as any;if(!a||a.dispatched||a.outcome!=='reserved')throw new ControlError('ATTEMPT_STATE');const p=ports.currentClearance(a.run_id,a.kind);if(activeActions.has(a.run_id))throw new ControlError('ACTION_IN_FLIGHT');const l=db.prepare('SELECT credits,calls FROM ledger').get() as any;const n=(db.prepare("SELECT count(*) n FROM attempts WHERE run_id=? AND outcome!='unsent'").get(a.run_id) as any).n;
  // The reservation is already charged. Equality is admissible; dispatch never charges again.
  if(l.calls>p.limits.calls||l.credits>p.limits.credits)throw new ControlError('ALLOWANCE_EXHAUSTED');if(n>p.limits.runCalls)throw new ControlError('RUN_CALL_LIMIT');
  db.prepare("UPDATE attempts SET dispatched=1,outcome='unknown' WHERE id=?").run(id);runId=a.run_id;db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}activeActions.set(runId,id);},
 settleAttempt(id,result){const a=db.prepare('SELECT * FROM attempts WHERE id=?').get(id) as any;if(!a||a.dispatched&&result.outcome==='unsent')return;if(activeActions.get(a.run_id)===id)activeActions.delete(a.run_id);if(result.outcome==='unsent'&&!a.dispatched&&a.outcome!=='unsent'){db.exec('BEGIN IMMEDIATE');db.prepare('UPDATE ledger SET credits=credits-?,calls=calls-1').run(a.credits);db.prepare("UPDATE attempts SET outcome='unsent' WHERE id=?").run(id);db.exec('COMMIT');return;}if(a.dispatched)db.prepare('UPDATE attempts SET outcome=?,usage=? WHERE id=?').run(result.outcome,result.usage?JSON.stringify(result.usage):null,id);},
 emit(e){if(typeof e.runId==='string'){if(e.stage==='public_capture'){if(variant(e.runId)!=='blind'||typeof e.attemptId!=='string'||typeof e.serializedBody!=='string'||typeof e.profileId!=='string')throw new ControlError('CAPTURE_DENIED');const attempt=db.prepare('SELECT * FROM attempts WHERE id=?').get(e.attemptId) as any;if(!attempt||attempt.run_id!==e.runId||!attempt.dispatched||!['actor','checker'].includes(attempt.kind))throw new ControlError('CAPTURE_DENIED');validatePublicApplicationBody(e.profileId as ProfileId,attempt.kind,e.serializedBody);db.prepare('INSERT INTO blind_captures VALUES(?,?,?,?)').run(e.attemptId,e.runId,e.profileId,e.serializedBody);event(e.runId,'public_capture','application_dispatch',null,{attemptId:e.attemptId,profileId:e.profileId,mode:getModel().mode,dispatchStatus:'dispatched'});return;}event(e.runId,String(e.stage),String(e.reasonCode),null,{requestedModel:modelIdentity(e.requestedModel),modelVersion:modelIdentity(e.modelVersion),returnedModelHash:identityHash(e.modelVersion),responseId:null,responseIdHash:identityHash(e.responseId),promptHash:e.promptHash,schemaHash:e.schemaHash,inputHash:e.inputHash});}}
 };
 const clearance=ports.currentClearance;ports.currentClearance=(id,kind)=>measureControl(id,()=>clearance(id,kind));
 let model:ModelAdapter|undefined;const getModel=()=>model??(model=typeof options.modelAdapter==='function'?options.modelAdapter(ports):options.modelAdapter??createModelAdapter(ports));
 function privacy(text:string):string{const p=store.getPolicy();const patterns=[/\bsk-[A-Za-z0-9_-]{12,}\b/g,/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g,/\b(?:\d[ -]?){10,15}\b/g];if(p.controls.privacy==='block'&&patterns.some(re=>re.test(text)))throw new ControlError('PRIVACY_BLOCK');return p.controls.privacy==='redact'?patterns.reduce((s,re)=>s.replace(re,'[REDACTED]'),text):text;}
 function admission(text:string,verdict:Verdict|null,p:Policy,feed:Feed){
  let status:'admitted'|'quarantined'='admitted';let reason='semantic_disabled';
  if(p.controls.semantic){if(!verdict)throw new ControlError('CHECKER_REQUIRED');if(verdict.classification==='uncertain'||verdict.confidence<p.threshold)throw new ControlError('CHECKER_UNCERTAIN');status=verdict.classification==='active'?'quarantined':'admitted';reason=verdict.classification;}
  const signature=p.controls.signatures?feed.signatures.find(s=>text.toLowerCase().includes(s.pattern.toLowerCase())):undefined;
  const matchedSignature=signature&&reason!=='quoted'?{idHash:hash(signature.id),patternHash:hash(signature.pattern),reasonCodeHash:hash(signature.reasonCode)}:null;
  if(matchedSignature){status='quarantined';reason=signature!.reasonCode;}
  return {status,reason,matchedSignature};
 }
 function basis(p:Policy,feed:Feed,verdict:Verdict|null){return {policyVersion:p.version,feedVersion:feed.version,policyHash:hash(p),feedHash:hash(feed),semantic:p.controls.semantic,threshold:p.threshold,signatures:p.controls.signatures,verdict};}
 const BasisSchema=z.strictObject({policyVersion:z.number().int(),feedVersion:z.number().int(),policyHash:z.string().length(64),feedHash:z.string().length(64),semantic:z.boolean(),threshold:z.number(),signatures:z.boolean(),verdict:VerdictSchema.nullable()});
 async function admit(runId:string,sourceId:string,text:string,deadline:number){
  if(![`${runId}:notes`,`${runId}:facts`,`${runId}:advisory`].includes(sourceId))throw new ControlError('SOURCE_FORGERY');
  ports.currentClearance(runId,'checker');const cleared=privacy(text),initial=store.getPolicy(),initialFeed=store.getFeed();let verdict:Verdict|null=null;
  if(initial.controls.semantic){try{verdict=VerdictSchema.parse((await measureAsync(runId,'checker',()=>getModel().generate('checker',JSON.stringify({subject:cleared}),VerdictSchema,deadline,runId),modelIdentity(initial.models.checker))).json);}catch(error){throw new ControlError('CHECKER_FAILED_CLOSED',{origin:error instanceof ControlError?error.code:'INVALID_VERDICT',...(error instanceof ControlError?error.diagnostics:{})});}}
  const p=ports.currentClearance(runId,'checker'),feed=store.getFeed();if(privacy(text)!==cleared)throw new ControlError('ADMISSION_INPUT_CHANGED');
  const {status,reason,matchedSignature}=admission(cleared,verdict,p,feed);const initialDecision=admission(cleared,verdict,initial,initialFeed);
  if(status!==initialDecision.status)throw new ControlError('SOURCE_ADMISSION_INVALIDATED');
  const decisionBasis=basis(p,feed,verdict);const metadata={audiences:['internal'],synthetic:true,status,hash:hash(cleared),basis:decisionBasis};db.prepare('INSERT OR REPLACE INTO sources VALUES (?,?,?,?)').run(sourceId,runId,JSON.stringify(metadata),status==='admitted'?cleared:'');
  const v=view(runId);v.evidence.push({sourceId,status,summary:status==='quarantined'?'Whole advisory excluded before actor exposure':cleared});putView(v);event(runId,'inspection',reason,sourceId,{sourceHash:hash(text),clearedHash:hash(cleared),basis:decisionBasis,admission:{status,matchedSignature}});
 }
 function validDraft(runId:string,candidate:unknown):Draft{
  const plan=DraftPlanSchema.parse(candidate);const admitted=clearedSources(runId);const facts=admitted.find(r=>r.id===`${runId}:facts`);
  if(!facts||facts.text!==FACTS)throw new ControlError('ESSENTIAL_FACTS_MISSING');
  if(plan.sourceVersion!==ESSENTIAL_FACTS.sourceVersion||plan.targetVersion!==ESSENTIAL_FACTS.targetVersion||hash(plan.migration)!==hash(ESSENTIAL_FACTS.migration)||new Set(plan.steps).size!==plan.steps.length)throw new ControlError('DRAFT_FACTS');
  const rendered=renderDraft(plan);const draft=DraftSchema.parse({...rendered,body:privacy(rendered.body),breakingChange:privacy(rendered.breakingChange)});
  if(!draft.citations.includes(`${runId}:facts`)||draft.citations.some(id=>!admitted.some(r=>r.id===id)))throw new ControlError('DRAFT_CITATIONS');
  if(!store.getPolicy().sinkRules.internalAllowed)throw new ControlError('SINK_DENIED');event(runId,'output','DRAFT_PREPARATION_VERIFIED',null,{factsHash:hash(facts.text),migration:draft.migration,preparationStatus:draft.preparationStatus});return draft;
 }
 function clearedSources(runId:string){
  const p=store.getPolicy();const rows=db.prepare('SELECT * FROM sources WHERE run_id=?').all(runId) as any[];
  return rows.filter(row=>{let meta;try{meta=z.strictObject({audiences:z.array(z.literal('internal')).length(1),synthetic:z.literal(true),status:z.enum(['admitted','quarantined']),hash:z.string().length(64),basis:BasisSchema}).parse(JSON.parse(row.metadata));}catch{throw new ControlError('SOURCE_CLEARANCE');}
   if(row.run_id!==runId||![`${runId}:notes`,`${runId}:facts`,`${runId}:advisory`].includes(row.id)||!meta.audiences.every(a=>p.sourceRules.audiences.includes(a))||meta.hash!==hash(row.text)&&meta.status==='admitted')throw new ControlError('SOURCE_CLEARANCE');
   if(meta.status==='admitted'){const cleared=privacy(row.text);if(cleared!==row.text)throw new ControlError('ADMISSION_INPUT_CHANGED');const feed=store.getFeed();const decision=admission(cleared,meta.basis.verdict,p,feed),decisionBasis=basis(p,feed,meta.basis.verdict),outcome={status:decision.status,matchedSignature:decision.matchedSignature};if(decision.status!=='admitted'){event(runId,'inspection','SOURCE_ADMISSION_INVALIDATED',row.id,{basis:decisionBasis,admission:outcome});throw new ControlError('SOURCE_ADMISSION_INVALIDATED');}if(meta.basis.policyHash!==hash(p)||meta.basis.feedHash!==hash(feed)){meta.basis=decisionBasis;db.prepare('UPDATE sources SET metadata=? WHERE id=?').run(JSON.stringify(meta),row.id);event(runId,'inspection','SOURCE_REVALIDATED',row.id,{basis:meta.basis,admission:outcome});}}return meta.status==='admitted';});
 }
 async function processRun(runId:string,scenario:Scenario,advisory?:string){let client:Client|undefined;let child:StdioClientTransport|undefined;let saveAttempt:string|undefined;const overallStart=performance.now(),startedAt=new Date().toISOString();const cpu=cpus();const measurementRow=db.prepare('INSERT INTO events(run_id,stage,reason,details) VALUES (?,?,?,?)').run(runId,'measurements','measured','{}');measurements.set(runId,{eventId:Number(measurementRow.lastInsertRowid),scenario,hardware:{node:process.version,platform:process.platform,architecture:process.arch,osRelease:release().slice(0,128),cpuModel:(cpu[0]?.model??'Unavailable').slice(0,128),cpuCores:cpu.length||1,totalMemoryBytes:totalmem()},spans:[],aggregates:{},samplesTruncated:false});try{
  const deadline=getRun(runId).deadline as number;ports.currentClearance(runId,'tool');
  const busyMs=Math.max(0,Math.min(FIXTURE_BUSY_MS,Math.floor(Math.min(store.getPolicy().limits.attemptMs,deadline-Date.now())/4)));
  if(!fixtureInitialized){initializeEffectStore(options.fixtureDbPath,busyMs);fixtureInitialized=true;}
  ports.currentClearance(runId,'tool');
  child=new StdioClientTransport({command:process.execPath,args:[resolve(ROOT,'dist/fixture/server.js')],cwd:ROOT,env:{PROOFGATE_FIXTURE_DB:resolve(options.fixtureDbPath),PROOFGATE_RUN_ID:runId,PROOFGATE_SCENARIO:scenario,PROOFGATE_FIXTURE_INITIALIZED:'1',PROOFGATE_RUN_DEADLINE:String(deadline),PROOFGATE_FIXTURE_BUSY_MS:String(busyMs)},stderr:'pipe',maxBufferSize:store.getPolicy().limits.responseBytes});
  const pending=new Map<string|number|undefined,string>();let transport:Transport;
  transport={async start(){child!.onmessage=(message)=>{if('id' in message&&!('method' in message)){const attempt=pending.get(message.id);if(attempt){ports.settleAttempt(attempt,{usage:null,outcome:'known'});pending.delete(message.id);}}transport.onmessage?.(message);};child!.onerror=e=>transport.onerror?.(e);child!.onclose=()=>transport.onclose?.();await child!.start();},async send(message){const id=ports.reserveAttempt({runId,kind:'tool',requestBytes:Buffer.byteLength(JSON.stringify(message)+'\n'),outputTokens:0,deadline});try{ports.markDispatched(id);if('method' in message&&message.method==='tools/call'&&(message.params as any)?.name==='save_internal_draft')saveAttempt=id;if('id' in message)pending.set(message.id,id);await child!.send(message);if(!('id' in message))ports.settleAttempt(id,{usage:null,outcome:'known'});}catch(e){const a=db.prepare('SELECT dispatched FROM attempts WHERE id=?').get(id) as any;ports.settleAttempt(id,{usage:null,outcome:a.dispatched?'unknown':'unsent'});throw e;}},async close(){for(const id of pending.values())ports.settleAttempt(id,{usage:null,outcome:'unknown'});pending.clear();await child!.close();}};
  client=new Client({name:'proofgate-host',version:'0.1.0'});await client.connect(options.fixtureTransport?.(transport)??transport,{timeout:Math.min(store.getPolicy().limits.attemptMs,deadline-Date.now())});const catalog=await client.listTools(undefined,{timeout:Math.min(store.getPolicy().limits.attemptMs,deadline-Date.now())});
  if(catalog.tools.length!==3||new Set(catalog.tools.map(t=>t.name)).size!==3||catalog.tools.some(tool=>!Object.hasOwn(ToolRegistry,tool.name)))throw new ControlError('TOOL_CATALOG');
  const canonical=(obj:any):string=>JSON.stringify(obj&&typeof obj==='object'?Array.isArray(obj)?obj.map(x=>JSON.parse(canonical(x))):Object.fromEntries(Object.keys(obj).filter(k=>k!=='$schema').sort().map(k=>[k,JSON.parse(canonical(obj[k]))])):obj);
  for(const tool of catalog.tools){const entry=ToolRegistry[tool.name as ToolName];if(canonical(tool.inputSchema)!==canonical(jsonSchema(entry.args))||canonical(tool.outputSchema)!==canonical(jsonSchema(entry.result)))throw new ControlError('TOOL_SCHEMA');}
  await admit(runId,`${runId}:advisory`,advisory??ADVISORIES[scenario],deadline);
  const transcript:unknown[]=[];let saved=false;
  for(let turn=0;turn<store.getPolicy().limits.actorTurns;turn++){
   ports.currentClearance(runId,'actor');const sources=clearedSources(runId).map(s=>({sourceId:s.id,text:s.text}));
   const notes=sources.find(s=>s.sourceId===`${runId}:notes`);const facts=sources.find(s=>s.sourceId===`${runId}:facts`);
   const nextAction=!notes?'read_project_context':!facts?'read_dependency_evidence':facts.text!==FACTS?'incomplete':'save_internal_draft';
   const actorSaveArgs=z.strictObject({draft:DraftPlanSchema});const turnSchema=nextAction==='incomplete'?z.strictObject({kind:z.literal('incomplete'),reason:z.string().min(1).max(2000)}):z.strictObject({kind:z.literal('tool'),tool:z.literal(nextAction),args:nextAction==='save_internal_draft'?actorSaveArgs:ToolRegistry[nextAction].args});
   const input=JSON.stringify({task:{projectId:'proofgate-demo',dependency:'ProofLib',sourceVersion:'1.0.0',targetVersion:'2.0.0'},nextAction,completedReads:transcript,tools:Object.fromEntries(Object.entries(ToolRegistry).map(([name,entry])=>[name,jsonSchema(name==='save_internal_draft'?actorSaveArgs:entry.args)])),evidence:sources});
   const generated=await measureAsync(runId,'actor',()=>getModel().generate('actor',input,turnSchema,deadline,runId),modelIdentity(store.getPolicy().models.actor));event(runId,'actor_context','admitted_sources',null,{inputHash:createHash('sha256').update(input).digest('hex'),sources:sources.map(s=>({sourceId:s.sourceId,contentHash:hash(s.text)}))});
   const proposal=ProposalSchema.parse(generated.json);event(runId,'proposal',proposal.kind,null,{proposalHash:hash(proposal),schemaHash:hash(jsonSchema(turnSchema))});
   if(proposal.kind==='incomplete'){const v=view(runId);v.state='incomplete';v.error={code:'ESSENTIAL_FACTS_MISSING',message:'Required independent migration facts were unavailable. No draft saved.'};putView(v);return;}
   if(proposal.kind==='final'){if(!saved)throw new ControlError('FINAL_WITHOUT_EFFECT');return;}
   const entry=ToolRegistry[proposal.tool];let args:Record<string,unknown>;let draft:Draft|undefined;
   if(proposal.tool==='save_internal_draft'){if(saved)throw new ControlError('DUPLICATE_SAVE');draft=measureControl(runId,()=>validDraft(runId,proposal.args.draft));args=ToolRegistry.save_internal_draft.args.parse({draft});}else args=entry.args.parse(proposal.args);
   ports.currentClearance(runId,'tool');event(runId,'dispatch',proposal.tool);
   const result=await measureAsync(runId,'mcp',()=>client!.callTool({name:proposal.tool,arguments:args,_meta:{runId,callerId:'developer',audiences:['internal'],sinkId:'internal'}},undefined,{timeout:Math.min(store.getPolicy().limits.attemptMs,deadline-Date.now())}));
   if(result.isError||!Array.isArray(result.content)||result.content.length!==1||result.content[0]?.type!=='text'||typeof result.content[0].text!=='string'||Buffer.byteLength(result.content[0].text)>store.getPolicy().limits.jsonBytes)throw new ControlError('TOOL_RESULT');
   const parsed=entry.result.parse(result.structuredContent);if(JSON.stringify(parsed)!==JSON.stringify(JSON.parse(result.content[0].text)))throw new ControlError('TOOL_RESULT_MISMATCH');
   if(proposal.tool==='save_internal_draft'){
    const effectStore=openEffectStore(options.fixtureDbPath);let effects;try{effects=effectStore.read(runId);}finally{effectStore.close();}
    if(effects.length!==1||effects[0]?.sink_id!=='internal'||effects[0]?.id!==(parsed as any).draftId||hash(JSON.parse(effects[0].content))!==hash(draft))throw new ControlError('EFFECT_MISMATCH');
    saved=true;const v=view(runId);v.state='succeeded';v.draft=draft!;v.effects={savedCount:1,reconciled:true};putView(v);event(runId,'reconciliation','independent_save');return;
   }
   const source=parsed as {sourceId:string;text:string};const expected=proposal.tool==='read_project_context'?`${runId}:notes`:`${runId}:facts`;if(source.sourceId!==expected)throw new ControlError('SOURCE_FORGERY');await admit(runId,source.sourceId,source.text,deadline);transcript.push({tool:proposal.tool,status:'completed',sourceId:source.sourceId});
  }throw new ControlError('ACTOR_TURN_LIMIT');
 }catch(error){if(saveAttempt)ports.settleAttempt(saveAttempt,{usage:null,outcome:'unknown'});const code=error instanceof ControlError?error.code:error instanceof z.ZodError?'SCHEMA_REJECTED':'WORKFLOW_FAILED';const v=view(runId);v.state=code==='ESSENTIAL_FACTS_MISSING'?'incomplete':'blocked';v.error={code,message:'Workflow stopped at an enforced boundary. Inspect sanitized decisions.'};putView(v);event(runId,'blocked',code,null,error instanceof ControlError?{diagnostics:error.diagnostics??null}:{});}finally{await client?.close().catch(()=>{});if(!client)await child?.close().catch(()=>{});recordSpan(runId,{kind:'overall',unit:'ms',durationMs:performance.now()-overallStart,startedAt,capturedAt:new Date().toISOString(),outcome:view(runId).state==='blocked'?'rejected':'resolved',boundary:'processRun_entry_to_cleanup',requestedModel:null,returnedModel:null,responseId:null});measurements.delete(runId);}}
 const api={config:{requiresAuth:true}};
 type BlindRun={runId:string;taskId:Recipe['taskId'];advisory:string;advisoryStatus:'pending'|'admitted'|'quarantined';advisoryVerdict:Verdict|null;recipe:Recipe|null;recipeVerdict:Verdict|null;basis:{policyHash:string;feedHash:string;policyVersion:number;feedVersion:number;semantic:boolean;threshold:number;signatures:boolean}|null;result:ReturnType<typeof executeRecipe>|null;resultRevision:string|null;resultVersion:number|null;workspaceVersion:number|null;publicInputs:{profileId:ProfileId;input:string;mode:'live'|'offline';evidence:'constructor'}[];localExecutions:number;save:null|{actionRunId:string;resultRevision:string;state:'pending'|'confirmed'|'unknown'|'blocked';artifactId:string|null;acknowledged:boolean};};
 function blindRun(id:string):BlindRun{if(variant(id)!=='blind')throw new ControlError('VARIANT_MISMATCH');return JSON.parse((db.prepare('SELECT content FROM blind_runs WHERE run_id=?').get(id) as any).content);}
 const putBlind=(r:BlindRun)=>db.prepare('UPDATE blind_runs SET content=? WHERE run_id=?').run(JSON.stringify(r),r.runId);
 const workspace=()=>{const r=db.prepare('SELECT version,content FROM blind_workspace WHERE id=1').get() as any;return{version:r.version,...JSON.parse(r.content)} as ReturnType<typeof initialPrivate>&{version:number};};
 let workspaceBusy=false;
 function withWorkspace<T>(work:()=>T|Promise<T>):T|Promise<T>{if(workspaceBusy)throw new ControlError('ACTION_IN_FLIGHT');workspaceBusy=true;try{const result=work();if(result instanceof Promise)return result.finally(()=>{workspaceBusy=false;});workspaceBusy=false;return result;}catch(e){workspaceBusy=false;throw e;}}
 function revalidateBlind(id:string,requireBasis=false){const r=blindRun(id),p=store.getPolicy(),feed=store.getFeed();if(!p.sourceRules.providerAllowed||!p.sourceRules.audiences.includes('internal'))throw new ControlError('PROVIDER_CLEARANCE');if(requireBasis&&(!r.basis||r.basis.policyHash!==hash(p)||r.basis.feedHash!==hash(feed)))throw new ControlError('NEW_COMPOSITION_REQUIRED');if(r.advisoryStatus==='admitted'&&admission(privacy(r.advisory),r.advisoryVerdict,p,feed).status!=='admitted')throw new ControlError('SOURCE_ADMISSION_INVALIDATED');if(r.recipe){try{validateRecipe(r.recipe,r.taskId);}catch{throw new ControlError('RECIPE_DENIED');}if(r.recipeVerdict&&admission(JSON.stringify(r.recipe),r.recipeVerdict,p,feed).status!=='admitted')throw new ControlError('RECIPE_DENIED');}}
 function registerRun(id:string,workflow:'blind'|'blind-save',parentId:string|null=null,resultRevision:string|null=null){const p=store.getPolicy();const v:RunView={runId:id,state:'running',mode:workflow==='blind-save'?view(parentId!).mode:getModel().mode,synthetic:true,policyVersion:p.version,feedVersion:store.getFeed().version,evidence:[],decisions:[],draft:null,effects:{savedCount:0,reconciled:false},resources:resources(id),error:null};db.prepare('INSERT INTO runs VALUES(?,?,?,?)').run(id,'developer',JSON.stringify(v),Date.now()+p.limits.runMs);db.prepare('INSERT INTO workflow_variants VALUES(?,?,?,?)').run(id,workflow,parentId,resultRevision);}
 async function blindGenerate(id:string,kind:'actor'|'checker',input:string,schema:z.ZodType,profileId:ProfileId){ports.currentClearance(id,kind);const r=blindRun(id);r.publicInputs.push({profileId,input,mode:getModel().mode,evidence:'constructor'});putBlind(r);return (await measureBlindAsync(id,profileId==='blind-planner'?'planner':profileId==='blind-advisory-checker'?'advisory-checker':'recipe-checker',()=>getModel().generate(kind,input,schema,getRun(id).deadline,id,profileId),'generate_entry_to_resolution_or_rejection',store.getPolicy().models[kind])).json;}
 async function processBlind(id:string){beginBlindMeasurements(id);const start=performance.now(),startedAt=new Date().toISOString();try{let r=blindRun(id);const advisory=privacy(r.advisory);const p=store.getPolicy();let verdict:Verdict|null=null;if(p.controls.semantic){try{verdict=VerdictSchema.parse(await blindGenerate(id,'checker',buildAdvisoryInspection({stage:'advisory-checker',taskId:r.taskId,capabilities:publicCapabilities,advisory}),VerdictSchema,'blind-advisory-checker'));}catch{throw new ControlError('CHECKER_FAILED_CLOSED');}}r=blindRun(id);if(privacy(r.advisory)!==advisory)throw new ControlError('ADMISSION_INPUT_CHANGED');const decision=admission(advisory,verdict,store.getPolicy(),store.getFeed());r.advisory=advisory;r.advisoryStatus=decision.status;r.advisoryVerdict=verdict;putBlind(r);event(id,'inspection',decision.reason,null,{subject:'public_advisory',status:decision.status,semantic:store.getPolicy().controls.semantic});
 const proposed=await blindGenerate(id,'actor',buildPlanner({stage:'planner',taskId:r.taskId,capabilities:publicCapabilities,advisory:decision.status==='admitted'?advisory:null}),RecipeSchema,'blind-planner');let recipe:Recipe;try{recipe=validateRecipe(proposed,r.taskId);}catch{throw new ControlError('RECIPE_DENIED');}let recipeVerdict:Verdict|null=null;if(store.getPolicy().controls.semantic){try{recipeVerdict=VerdictSchema.parse(await blindGenerate(id,'checker',buildRecipeInspection({stage:'recipe-checker',taskId:r.taskId,capabilities:publicCapabilities,recipe}),VerdictSchema,'blind-recipe-checker'));}catch{throw new ControlError('CHECKER_FAILED_CLOSED');}}if(admission(JSON.stringify(recipe),recipeVerdict,store.getPolicy(),store.getFeed()).status!=='admitted')throw new ControlError('RECIPE_DENIED');r=blindRun(id);r.recipe=recipe;r.recipeVerdict=recipeVerdict;r.basis={policyHash:hash(store.getPolicy()),feedHash:hash(store.getFeed()),policyVersion:store.getPolicy().version,feedVersion:store.getFeed().version,semantic:store.getPolicy().controls.semantic,threshold:store.getPolicy().threshold,signatures:store.getPolicy().controls.signatures};putBlind(r);ports.currentClearance(id,'actor');await withWorkspace(()=>bindBlind(id));const v=view(id);v.state='succeeded';putView(v);event(id,'local','brief_rendered');
 }catch(e){const v=view(id);v.state='blocked';v.error={code:e instanceof ControlError?e.code:e instanceof z.ZodError?'SCHEMA_REJECTED':'BLIND_FAILED',message:'Workflow stopped at an enforced boundary.'};putView(v);event(id,'blocked',v.error.code);}finally{recordBlindSpan(id,'overall',start,startedAt,view(id).state==='blocked'?'rejected':'resolved','composition_entry_to_cleanup');blindMeasurements.delete(id);}}
 function bindBlind(id:string){beginBlindMeasurements(id);const start=performance.now(),startedAt=new Date().toISOString();let outcome:BlindSpan['outcome']='resolved';try{return bindBlindLocal(id);}catch(e){outcome='rejected';throw e;}finally{recordBlindSpan(id,'local',start,startedAt,outcome,'local_executor_entry_to_exit');}}
 function bindBlindLocal(id:string){const r=blindRun(id);if(!r.recipe)throw new ControlError('RECIPE_REQUIRED');revalidateBlind(id,true);const result=executeRecipe(r.recipe,()=>{r.localExecutions++;return workspace();});const w=workspace();r.result=result;r.resultRevision=randomUUID();db.prepare('UPDATE blind_result_sequence SET version=version+1 WHERE id=1').run();r.resultVersion=(db.prepare('SELECT version FROM blind_result_sequence WHERE id=1').get() as any).version;r.workspaceVersion=w.version;r.save=null;putBlind(r);return r;}
 function blindProjection(id:string){const r=blindRun(id),v=view(id),w=workspace();return bounded({...r,state:v.state,mode:v.mode,synthetic:true,error:v.error,decisions:v.decisions,resources:resources(id),independentEffects:observeBlind(id),saveAction:r.save?{runId:r.save.actionRunId,parentRunId:id,resultRevision:r.save.resultRevision,deadline:getRun(r.save.actionRunId).deadline,attempts:db.prepare('SELECT id,kind,dispatched,outcome,credits,usage FROM attempts WHERE run_id=?').all(r.save.actionRunId)}:null,result:r.workspaceVersion===w.version?r.result:null,resultRevision:r.workspaceVersion===w.version?r.resultRevision:null,resultCurrent:r.workspaceVersion===w.version,captures:(db.prepare('SELECT attempt_id,profile_id,body FROM blind_captures WHERE run_id=?').all(id) as any[]).map(c=>({attemptId:c.attempt_id,profileId:c.profile_id,serializedBody:c.body,mode:v.mode,evidence:'actual_application_dispatch',dispatchStatus:'dispatched',outcome:(db.prepare('SELECT outcome FROM attempts WHERE id=?').get(c.attempt_id) as any)?.outcome??'unknown'})),attempts:db.prepare('SELECT id,kind,dispatched,outcome,credits,usage FROM attempts WHERE run_id=?').all(id)});}
 app.post('/api/blind/runs',api,async(req,reply)=>{const b=BlindStartSchema.parse(req.body);if(jobs.size>=MAX_ACTIVE_RUNS)throw new ControlError('RUN_CAPACITY');const id=randomUUID();registerRun(id,'blind');const r:BlindRun={runId:id,taskId:b.taskId,advisory:b.advisory??DEFAULT_ADVISORY,advisoryStatus:'pending',advisoryVerdict:null,recipe:null,recipeVerdict:null,basis:null,result:null,resultRevision:null,resultVersion:null,workspaceVersion:null,publicInputs:[],localExecutions:0,save:null};db.prepare('INSERT INTO blind_runs VALUES(?,?)').run(id,JSON.stringify(r));const job=processBlind(id);jobs.set(id,job);job.finally(()=>jobs.delete(id));return reply.code(202).send({runId:id});});
 app.get('/api/blind/runs/:id',api,async(req)=>blindProjection((req.params as any).id));
 app.get('/api/blind/runs/:id/export',api,async(req)=>{const id=(req.params as any).id;blindRun(id);const v=blindProjection(id);const measurement=(runId:string)=>{const r=db.prepare("SELECT details FROM events WHERE run_id=? AND stage='blind_measurements' ORDER BY id DESC LIMIT 1").get(runId) as any;return r?JSON.parse(r.details):null;};const retained=db.prepare("SELECT stage,reason,details FROM events WHERE run_id=? AND stage!='blind_measurements' ORDER BY id LIMIT 257").all(id) as any[];const events=retained.map((e,i)=>{const details=JSON.parse(e.details),observed=v.decisions[i];const persisted=details?.provenance?.policyVersion;return{stage:e.stage,reason:e.reason,policyVersion:Number.isSafeInteger(persisted)&&persisted>=0?persisted:observed&&observed.stage===e.stage&&observed.reasonCode===e.reason&&Number.isSafeInteger(observed.policyVersion)?observed.policyVersion:null};}).filter(e=>e.stage!=='public_capture').slice(0,129);try{return bounded(projectBlindEvidence({view:v,policy:store.getPolicy(),feed:store.getFeed(),events,measurement:measurement(id),saveMeasurement:v.save?measurement(v.save.actionRunId):null}));}catch(e){throw new ControlError(e instanceof Error&&e.message==='CONTROL_RESPONSE_BOUND'?'CONTROL_RESPONSE_BOUND':'EVIDENCE_INVALID');}});
 app.get('/api/blind/workspace',api,async()=>bounded({synthetic:true,...workspace()}));
 function updateWorkspace(data:ReturnType<typeof initialPrivate>,expectedVersion:number){const w=workspace();if(w.version!==expectedVersion)throw new ControlError('STALE_WORKSPACE');db.prepare('UPDATE blind_workspace SET version=version+1,content=? WHERE id=1 AND version=?').run(JSON.stringify(data),expectedVersion);return bounded({synthetic:true,...workspace()});}
 app.put('/api/blind/private',api,async(req)=>{const b=PrivateUpdateSchema.parse(req.body);return withWorkspace(()=>{const w=workspace();return updateWorkspace({records:b.records,rules:w.rules},b.expectedVersion);});});
 app.put('/api/blind/rules',api,async(req)=>{const b=RulesUpdateSchema.parse(req.body);return withWorkspace(()=>{const w=workspace();return updateWorkspace({records:w.records,rules:b.rules},b.expectedVersion);});});
 app.post('/api/blind/reset',api,async(req)=>{z.strictObject({}).parse(req.body??{});return withWorkspace(()=>updateWorkspace(initialPrivate(),workspace().version));});
 app.post('/api/blind/runs/:id/rebind',api,async(req)=>{z.strictObject({}).parse(req.body??{});const id=(req.params as any).id;const r=blindRun(id);if(jobs.has(id)||activeActions.has(id)||r.save?.state==='pending'||r.save?.state==='unknown')throw new ControlError('ACTION_IN_FLIGHT');return withWorkspace(()=>{requireEventCapacity(id);beginBlindMeasurements(id);const start=performance.now(),at=new Date().toISOString();let outcome:BlindSpan['outcome']='resolved';db.exec('BEGIN IMMEDIATE');try{bindBlind(id);event(id,'local','rebound_without_models');const result=blindProjection(id);db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');outcome='rejected';throw e;}finally{recordBlindSpan(id,'overall',start,at,outcome,'rebind_entry_to_exit');blindMeasurements.delete(id);}});});
 function saveAuthority(id:string){const action=db.prepare('SELECT * FROM workflow_variants WHERE run_id=?').get(id) as any;const parent=blindRun(action.parent_id),w=workspace();if(!parent.save||parent.save.actionRunId!==id||parent.save.state!=='pending'||parent.resultRevision!==action.result_revision||parent.workspaceVersion!==w.version||!parent.result)throw new ControlError('STALE_RESULT');revalidateBlind(parent.runId,true);}
 function observeBlind(id:string){const r=blindRun(id);let reader:ReturnType<typeof openBlindEffectStore>|undefined;try{reader=openBlindEffectStore(options.fixtureDbPath);const matching=r.save?reader.readRevision(id,r.save.resultRevision):[];if(matching.length>16)throw new ControlError('EFFECT_BOUND');const exact=matching.length===1&&matching[0]!.action_run_id===r.save?.actionRunId&&matching[0]!.caller_id==='developer'&&matching[0]!.sink_id==='internal'&&matching[0]!.workspace_version===r.workspaceVersion&&matching[0]!.content===JSON.stringify(r.result);return{status:'observed',count:matching.length,hostAcknowledged:r.save?.acknowledged??false,matchesCanonicalBrief:r.save?exact:null,effects:matching.map(e=>({artifactId:e.id,effectId:e.effect_id,actionRunId:e.action_run_id,parentRunId:e.parent_run_id,resultRevision:e.result_revision,sink:'internal',contentHash:hash(JSON.parse(e.content))}))};}catch{return{status:'unavailable',count:null,hostAcknowledged:r.save?.acknowledged??false,matchesCanonicalBrief:null,effects:[]};}finally{reader?.close();}}
 async function performBlindSave(parentId:string,actionId:string){beginBlindMeasurements(actionId);const overallStart=performance.now(),overallAt=new Date().toISOString();let client:Client|undefined,child:StdioClientTransport|undefined;let saveAttempt:string|undefined;let confirmed=false;const pending=new Map<string|number|undefined,string>();try{
  const r=blindRun(parentId),deadline=getRun(actionId).deadline as number;saveAuthority(actionId);ports.currentClearance(actionId,'tool');const p=store.getPolicy();initializeBlindStore(options.fixtureDbPath,Math.max(0,Math.min(BLIND_BUSY_MS,Math.floor(Math.min(p.limits.attemptMs,deadline-Date.now())/5))));
  child=new StdioClientTransport({command:process.execPath,args:[resolve(ROOT,'dist/fixture/blind-server.js')],cwd:ROOT,env:{PROOFGATE_FIXTURE_DB:resolve(options.fixtureDbPath),PROOFGATE_RUN_ID:actionId,PROOFGATE_PARENT_RUN_ID:parentId,PROOFGATE_RESULT_REVISION:r.resultRevision!,PROOFGATE_WORKSPACE_VERSION:String(r.workspaceVersion),PROOFGATE_RUN_DEADLINE:String(deadline)},stderr:'pipe',maxBufferSize:p.limits.responseBytes});
  let transport:Transport;transport={async start(){child!.onmessage=message=>{if('id' in message&&!('method' in message)){const a=pending.get(message.id);if(a&&a!==saveAttempt){ports.settleAttempt(a,{usage:null,outcome:'known'});pending.delete(message.id);}}transport.onmessage?.(message);};child!.onerror=e=>transport.onerror?.(e);child!.onclose=()=>transport.onclose?.();await child!.start();},async send(message){const a=ports.reserveAttempt({runId:actionId,kind:'tool',requestBytes:Buffer.byteLength(JSON.stringify(message)+'\n'),outputTokens:0,deadline});let sent=false;try{ports.markDispatched(a);sent=true;if('method' in message&&message.method==='tools/call'){if((message.params as any)?.name!=='save_internal_brief')throw new ControlError('TOOL_DENIED');saveAttempt=a;}if('id' in message)pending.set(message.id,a);await child!.send(message);if(!('id' in message))ports.settleAttempt(a,{usage:null,outcome:'known'});}catch(e){ports.settleAttempt(a,{usage:null,outcome:sent?'unknown':'unsent'});throw e;}},async close(){for(const a of pending.values())ports.settleAttempt(a,{usage:null,outcome:'unknown'});pending.clear();await child!.close();}};
  const timeout=()=>Math.max(1,Math.min(store.getPolicy().limits.attemptMs,deadline-Date.now()));client=new Client({name:'proofgate-blind-host',version:'0.1.0'});await client.connect(options.fixtureTransport?.(transport)??transport,{timeout:timeout()});const catalog=await client.listTools(undefined,{timeout:timeout()});
  const canonical=(o:any):string=>JSON.stringify(o&&typeof o==='object'?Array.isArray(o)?o.map(x=>JSON.parse(canonical(x))):Object.fromEntries(Object.keys(o).filter(k=>k!=='$schema').sort().map(k=>[k,JSON.parse(canonical(o[k]))])):o);
  if(catalog.tools.length!==1||catalog.tools[0]!.name!=='save_internal_brief'||canonical(catalog.tools[0]!.inputSchema)!==canonical(jsonSchema(BlindSaveArgsSchema))||canonical(catalog.tools[0]!.outputSchema)!==canonical(jsonSchema(BlindSaveResultSchema)))throw new ControlError('TOOL_SCHEMA');
  saveAuthority(actionId);const meta=BlindSaveMetaSchema.parse({runId:actionId,parentRunId:parentId,resultRevision:r.resultRevision,workspaceVersion:r.workspaceVersion,callerId:'developer',sinkId:'internal'});const response=await measureBlindAsync(actionId,'mcp',()=>client!.callTool({name:'save_internal_brief',arguments:BlindSaveArgsSchema.parse({brief:r.result}),_meta:meta},undefined,{timeout:timeout()}),'mcp_call_entry_to_resolution_or_rejection');
  if(response.isError||!Array.isArray(response.content)||response.content.length!==1||response.content[0]?.type!=='text'||typeof response.content[0].text!=='string'||Buffer.byteLength(response.content[0].text)>store.getPolicy().limits.jsonBytes)throw new ControlError('TOOL_RESULT');const parsed=BlindSaveResultSchema.parse(response.structuredContent);if(JSON.stringify(parsed)!==JSON.stringify(JSON.parse(response.content[0].text)))throw new ControlError('TOOL_RESULT');
  const current=blindRun(parentId);current.save!.artifactId=parsed.artifactId;current.save!.acknowledged=true;putBlind(current);const observed=observeBlind(parentId);if(!observed.matchesCanonicalBrief||observed.effects[0]?.artifactId!==parsed.artifactId)throw new ControlError('EFFECT_MISMATCH');current.save!.state='confirmed';putBlind(current);if(saveAttempt){ports.settleAttempt(saveAttempt,{usage:null,outcome:'known'});for(const [key,a] of pending)if(a===saveAttempt)pending.delete(key);}confirmed=true;const v=view(actionId);v.state='succeeded';v.effects={savedCount:1,reconciled:true};putView(v);event(parentId,'reconciliation','independent_brief_save');
 }catch(e){if(confirmed)throw e;const r=blindRun(parentId);r.save!.state=saveAttempt?'unknown':'blocked';putBlind(r);if(saveAttempt)ports.settleAttempt(saveAttempt,{usage:null,outcome:'unknown'});const v=view(actionId);v.state='blocked';v.error={code:e instanceof ControlError?e.code:'SAVE_FAILED',message:'Save stopped at an enforced boundary; unknown dispatch is not replayed.'};putView(v);event(parentId,'save',saveAttempt?'unknown_save':'save_blocked');
 }finally{for(const a of pending.values())ports.settleAttempt(a,{usage:null,outcome:'unknown'});await client?.close().catch(()=>{});if(!client)await child?.close().catch(()=>{});recordBlindSpan(actionId,'overall',overallStart,overallAt,view(actionId).state==='blocked'?'rejected':'resolved','save_action_entry_to_cleanup');blindMeasurements.delete(actionId);}}
 app.post('/api/blind/runs/:id/save',api,async(req)=>{const b=SaveRequestSchema.parse(req.body),id=(req.params as any).id;return withWorkspace(async()=>{const r=blindRun(id);if(jobs.has(id)||activeActions.has(id))throw new ControlError('ACTION_IN_FLIGHT');if(!r.result||r.resultRevision!==b.resultRevision||r.workspaceVersion!==workspace().version)throw new ControlError('STALE_RESULT');if(r.save&&(r.save.state==='pending'||r.save.state==='unknown'||r.save.state==='confirmed'))throw new ControlError('DUPLICATE_SAVE');revalidateBlind(id,true);const p=store.getPolicy();if(!p.sinkRules.internalAllowed)throw new ControlError('SINK_DENIED');if(jobs.size>=MAX_ACTIVE_RUNS)throw new ControlError('RUN_CAPACITY');requireEventCapacity(id);const actionId=randomUUID();registerRun(actionId,'blind-save',id,r.resultRevision);r.save={actionRunId:actionId,resultRevision:r.resultRevision!,state:'pending',artifactId:null,acknowledged:false};putBlind(r);const job=performBlindSave(id,actionId);jobs.set(actionId,job);try{await job;}finally{jobs.delete(actionId);}return bounded({...blindProjection(id),independentEffects:observeBlind(id)});});});
 app.get('/api/blind/artifacts/:id',api,async(req)=>{const id=z.string().uuid().parse((req.params as any).id);let reader:ReturnType<typeof openBlindEffectStore>|undefined;try{reader=openBlindEffectStore(options.fixtureDbPath);const row=reader.artifact(id);if(!row||row.caller_id!=='developer'||row.sink_id!=='internal'||variant(row.parent_run_id)!=='blind')throw new ControlError('ARTIFACT_NOT_FOUND');return bounded({artifactId:row.id,actionRunId:row.action_run_id,parentRunId:row.parent_run_id,resultRevision:row.result_revision,workspaceVersion:row.workspace_version,sink:'internal',synthetic:true,brief:JSON.parse(row.content),contentHash:hash(JSON.parse(row.content))});}catch(e){throw e instanceof ControlError?e:new ControlError('ARTIFACT_NOT_FOUND');}finally{reader?.close();}});
 app.post('/api/blind/runs/:id/export',api,async(req)=>{z.strictObject({resultRevision:z.string().uuid(),destination:z.literal('external')}).parse(req.body);const id=(req.params as any).id;blindRun(id);return withWorkspace(()=>{event(id,'manual','external_export_refused');return bounded({allowed:false,code:'EXTERNAL_SINK_DENIED',evidence:'manual_deterministic_refusal',sinkEffects:0});});});
 function collectEvidence(runId:string):EvidenceExport{
  const v=view(runId),p=store.getPolicy(),feed=store.getFeed();
  const validHash=(x:unknown)=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x)?x:null;
  const sourceRef=(x:unknown)=>typeof x==='string'&&[`${runId}:notes`,`${runId}:facts`,`${runId}:advisory`].includes(x)?x:null;
  const parseDetails=(text:string)=>{if(Buffer.byteLength(text)>CONTROL_RESPONSE_BYTES)throw new ControlError('CONTROL_RESPONSE_BOUND');try{const d=JSON.parse(text);return d&&typeof d==='object'&&!Array.isArray(d)?d:{};}catch{return {};}};
  const knownStages=new Set(['inspection','actor','checker','actor_context','proposal','dispatch','output','reconciliation','blocked']);
  const knownReasons=new Set(['signature_match','benign','active','quoted','uncertain','offline','semantic_disabled','model_response','admitted_sources','tool','final','incomplete','read_project_context','read_dependency_evidence','save_internal_draft','DRAFT_PREPARATION_VERIFIED','independent_save','SOURCE_REVALIDATED','CHECKER_FAILED_CLOSED','CHECKER_UNCERTAIN','SOURCE_FORGERY','PRIVACY_BLOCK','ALLOWANCE_EXHAUSTED','RUN_CALL_LIMIT','DEADLINE','PROVIDER_CLEARANCE','SINK_DENIED','MODEL_ALLOWLIST','SCHEMA_REJECTED','WORKFLOW_FAILED','ACTOR_TURN_LIMIT','TOOL_RESULT','TOOL_RESULT_MISMATCH','EFFECT_MISMATCH','ESSENTIAL_FACTS_MISSING','DRAFT_FACTS','DRAFT_CITATIONS','SOURCE_CLEARANCE','SOURCE_ADMISSION_INVALIDATED','ADMISSION_INPUT_CHANGED','FINAL_WITHOUT_EFFECT','DUPLICATE_SAVE','TOOL_CATALOG','TOOL_SCHEMA','ACTION_IN_FLIGHT','CONTROL_RESPONSE_BOUND']);
  const rawEvents=db.prepare('SELECT * FROM events WHERE run_id=? ORDER BY id LIMIT 129').all(runId) as any[];
  const measured=rawEvents.find(e=>e.stage==='measurements'&&e.reason==='measured');const data=measured?parseDetails(measured.details):null;
  const spans:MeasuredSpan[]=Array.isArray(data?.spans)?data.spans.map((s:any)=>{const parsed=SpanSchema.safeParse({kind:s.kind,unit:s.unit,durationMs:s.durationMs,startedAt:s.startedAt,capturedAt:s.capturedAt,outcome:s.outcome,boundary:s.boundary,requestedModel:modelIdentity(s.requestedModel),returnedModel:modelIdentity(s.returnedModel),returnedModelHash:identityHash(s.returnedModel)??validHash(s.returnedModelHash),responseId:null,responseIdHash:identityHash(s.responseId)??validHash(s.responseIdHash)});if(!parsed.success)throw new ControlError('EVIDENCE_INVALID');return parsed.data;}):[];
  const rows=rawEvents.filter(e=>e.stage!=='measurements');
  const events=rows.map((e,i)=>{const d=parseDetails(e.details),b=BasisSchema.safeParse(d.basis),a=AdmissionOutcomeSchema.safeParse(d.admission),decision=v.decisions[i];return {sequence:i+1,stage:knownStages.has(e.stage)?e.stage:'unrecognized',reasonCode:b.success&&a.success&&a.data.matchedSignature?'signature_match':knownReasons.has(e.reason)?e.reason:'unrecognized',sourceId:sourceRef(decision?.sourceId),policyVersion:b.success?b.data.policyVersion:decision?.policyVersion??v.policyVersion,feedVersion:b.success?b.data.feedVersion:null,hashes:{sourceHash:validHash(d.sourceHash),clearedHash:validHash(d.clearedHash),inputHash:validHash(d.inputHash),schemaHash:validHash(d.schemaHash),promptHash:validHash(d.promptHash),proposalHash:validHash(d.proposalHash),policyHash:b.success?validHash(b.data.policyHash):null,feedHash:b.success?validHash(b.data.feedHash):null},admission:b.success?{semantic:b.data.semantic,threshold:b.data.threshold,signatures:b.data.signatures,classification:b.data.verdict?.classification??null,confidence:b.data.verdict?.confidence??null,status:a.success?a.data.status:null,matchedSignature:a.success?a.data.matchedSignature:null}:null};});
  const attempts=(db.prepare('SELECT * FROM attempts WHERE run_id=? ORDER BY rowid LIMIT 513').all(runId) as any[]).map(a=>({id:a.id,kind:a.kind,credits:a.credits,dispatched:a.dispatched===1,outcome:a.outcome,usage:a.usage?JSON.parse(a.usage):null}));
  let independentEffects:EvidenceExport['independentEffects']={status:'unavailable',count:null,hostAcknowledged:v.effects.reconciled&&v.state==='succeeded',matchesCanonicalDraft:null,effects:[]};
  try{const reader=openEffectStore(options.fixtureDbPath);try{const effects=reader.read(runId);if(effects.length>16||effects.some(e=>e.run_id!==runId||e.sink_id!=='internal'))throw new Error('invalid effects');independentEffects={status:'observed',count:effects.length,hostAcknowledged:independentEffects.hostAcknowledged,matchesCanonicalDraft:v.draft?effects.length===1&&hash(JSON.parse(effects[0]!.content))===hash(v.draft):null,effects:effects.map(e=>({effectId:e.id,sink:'internal',contentHash:hash(JSON.parse(e.content))}))};}finally{reader.close();}}catch{/* A missing or unreadable recorder is unavailable, never zero. */}
  const cleanPolicy=PolicySchema.parse({...p,models:{...p.models,actor:p.models.allowlist.includes(p.models.actor as any)?p.models.actor:'unavailable',checker:p.models.allowlist.includes(p.models.checker as any)?p.models.checker:'unavailable'},tariffs:{...p.tariffs,asOf:/^\d{4}-\d{2}-\d{2}(?:-unpriced)?$/.test(p.tariffs.asOf)?p.tariffs.asOf:'unavailable'}});
  const r=v.resources;let draft:EvidenceExport['draft']=null;
  if(v.draft){const parsed=DraftSchema.parse(v.draft);if(parsed.sourceVersion!=='1.0.0'||parsed.targetVersion!=='2.0.0'||parsed.citations.some(id=>!sourceRef(id)))throw new ControlError('EVIDENCE_INVALID');draft={sourceVersion:'1.0.0',targetVersion:'2.0.0',migration:parsed.migration,preparationStatus:parsed.preparationStatus,citations:parsed.citations,contentHash:hash(parsed)};}
  const hardware=data?.hardware;if(hardware&&Object.values(hardware).some(x=>typeof x==='string'&&/(?:[<>]|sk-|secret|credential|token|canary|signature)/i.test(x)))throw new ControlError('EVIDENCE_INVALID');const aggregates=(['deterministic','checker','actor','mcp','overall'] as const).flatMap(kind=>{const sample=spans.filter(s=>s.kind===kind);const a=data?.aggregates?.[kind];return a?[{kind,count:a.count,totalMs:a.totalMs}]:sample.length?[{kind,count:sample.length,totalMs:sample.reduce((n,s)=>n+s.durationMs,0)}]:[];});
  return controlSnapshot(EvidenceExportSchema.parse({schemaVersion:'proofgate-evidence-1',generatedAt:new Date().toISOString(),run:{runId:v.runId,mode:v.mode,synthetic:true,state:v.state,policyVersion:v.policyVersion,feedVersion:v.feedVersion},policy:{scope:'current_accepted',hash:hash(p),snapshot:cleanPolicy},feed:{scope:'current_accepted',version:feed.version,hash:hash(feed),signatures:feed.signatures.map(s=>({id:null,reasonCode:null,idHash:hash(s.id),patternHash:hash(s.pattern),reasonCodeHash:hash(s.reasonCode)}))},events,attempts,ledger:{scope:'whole_epoch',epochId:r.epochId,creditsReserved:r.creditsReserved,creditsLimit:r.creditsLimit,callsUsed:r.callsUsed,callsLimit:r.callsLimit,runUsage:r.usage,estimatedTariffCost:r.estimatedCost},independentEffects,draft,measurements:{status:spans.length?'measured':'unavailable',mode:v.mode,scenario:data?.scenario??null,hardware:hardware?{node:hardware.node,platform:hardware.platform,architecture:hardware.architecture,osRelease:hardware.osRelease,cpuModel:hardware.cpuModel,cpuCores:hardware.cpuCores,totalMemoryBytes:hardware.totalMemoryBytes}:null,spans,samplesTruncated:data?.samplesTruncated===true,aggregates,workload:{events:events.length,attempts:attempts.length,sources:v.evidence.length},models:spans.filter(s=>s.kind==='actor'||s.kind==='checker').map(s=>({role:s.kind,requestedModel:s.requestedModel,returnedModel:s.returnedModel,returnedModelHash:s.returnedModelHash,responseId:null,responseIdHash:s.responseIdHash}))}}));
 }
 app.addHook('onRequest',async(req,reply)=>{reply.header('Cache-Control','no-store').header('X-Content-Type-Options','nosniff');if(!(req.routeOptions.config as {requiresAuth?:boolean}).requiresAuth)return;const a=req.headers.authorization;const expected=Buffer.from(`Bearer ${options.token}`);const actual=Buffer.from(a??'');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return reply.code(401).send({code:'UNAUTHORIZED'});});
 app.setErrorHandler((err,req,reply)=>{const code=err instanceof ControlError?err.code:err instanceof z.ZodError?'SCHEMA_REJECTED':'REQUEST_FAILED';reply.code(code==='RUN_CAPACITY'?503:code.startsWith('STALE')?409:code==='RUN_NOT_FOUND'?404:400).send({code});});
 const bounded=controlSnapshot;
 app.get('/health',async()=>({status:'ok',synthetic:true}));
 app.post('/api/runs',api,async(req,reply)=>{const {scenario,advisory}=START_SCHEMA.parse(req.body);if(jobs.size>=MAX_ACTIVE_RUNS)throw new ControlError('RUN_CAPACITY');const runId=randomUUID();const p=store.getPolicy();const v:RunView={runId,state:'running',mode:getModel().mode,synthetic:true,policyVersion:p.version,feedVersion:store.getFeed().version,evidence:[],decisions:[],draft:null,effects:{savedCount:0,reconciled:false},resources:resources(runId),error:null};db.prepare('INSERT INTO runs VALUES (?,?,?,?)').run(runId,'developer',JSON.stringify(v),Date.now()+p.limits.runMs);const job=processRun(runId,scenario,advisory);jobs.set(runId,job);job.finally(()=>jobs.delete(runId));return reply.code(202).send({runId});});
 app.get('/api/runs/:id',api,async(req)=>{const id=(req.params as any).id;if(variant(id)!=='release')throw new ControlError('VARIANT_MISMATCH');const e=collectEvidence(id);return bounded({...view(id),decisions:e.events.map(event=>({sequence:event.sequence,stage:event.stage,reasonCode:event.reasonCode,sourceId:event.sourceId,policyVersion:event.policyVersion})),audit:{independentEffects:e.independentEffects,measurements:e.measurements}});});
 app.get('/api/runs/:id/export',api,async(req)=>{const id=(req.params as any).id;if(variant(id)!=='release')throw new ControlError('VARIANT_MISMATCH');return collectEvidence(id);});
 app.get('/api/policy',api,async()=>bounded(store.getPolicy()));app.put('/api/policy',api,async(req)=>{const b=z.strictObject({expectedVersion:z.number().int(),policy:PolicySchema}).parse(req.body);return store.activatePolicy(b.expectedVersion,b.policy);});
 app.get('/api/feed',api,async()=>bounded(FeedSchema.parse(store.getFeed())));app.put('/api/feed',api,async(req)=>{const b=z.strictObject({expectedVersion:z.number().int(),feed:FeedSchema}).parse(req.body);return store.activateFeed(b.expectedVersion,b.feed);});
 app.get('/',async(_,reply)=>reply.type('text/html').header('Content-Security-Policy',"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'").send(readFileSync(resolve(ROOT,'public/index.html'),'utf8')));app.get('/app.js',async(_,reply)=>reply.type('application/javascript').send(readFileSync(resolve(ROOT,'public/app.js'),'utf8')));
 app.get('/styles.css',async(_,reply)=>reply.type('text/css').send(readFileSync(resolve(ROOT,'public/styles.css'),'utf8')));
 return {app,store,ports,view,async waitForRun(id:string){await jobs.get(id);return view(id);},async close(){await Promise.all(jobs.values());await app.close();store.close();}};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const token=process.env.PROOFGATE_TOKEN;try{const host=createHost({token:token??'',hostDbPath:process.env.PROOFGATE_HOST_DB??'.proofgate/host.sqlite',fixtureDbPath:process.env.PROOFGATE_FIXTURE_DB??'.proofgate/fixture.sqlite'});await host.app.listen({host:'127.0.0.1',port:3100});console.log('ProofGate synthetic workbench: http://127.0.0.1:3100');}catch{console.error('Startup failed: set PROOFGATE_TOKEN (16+ characters) and check local paths.');process.exitCode=1;}
}
